// Generated by nex-gen. DO NOT EDIT!

import * as workflow from "@temporalio/workflow";
import { knowledgeBaseService } from "../service";
import type { GetPageInput, Page } from "../models";

/**
 * Fetch a page by id.
 *
 * @param endpoint - Endpoint for the service.
 * @param request - Request for the operation.
 */
export async function getPageRequest(
  endpoint: string,
  request: GetPageInput,
): Promise<workflow.NexusOperationHandle<Page>> {
  const client = workflow.createNexusServiceClient({
    service: knowledgeBaseService,
    endpoint: endpoint,
  });
  return await client.startOperation(knowledgeBaseService.operations.getPage, request);
}
