// Generated by nex-gen. DO NOT EDIT!

import * as workflow from "@temporalio/workflow";
import { knowledgeBaseService } from "../services";
import type { PutBlockOutput } from "../models";
import type { Block } from "../../content/block/models";

/**
 * Create or update a content block.
 *
 * @param endpoint - Endpoint for the service.
 * @param request - Request for the operation.
 */
export async function putBlockRequest(
  endpoint: string,
  request: Block,
): Promise<workflow.NexusOperationHandle<PutBlockOutput>> {
  const client = workflow.createNexusServiceClient({
    service: knowledgeBaseService,
    endpoint: endpoint,
  });
  return await client.startOperation(knowledgeBaseService.operations.putBlock, request);
}
