// Generated by nex-gen. DO NOT EDIT!

import type * as common from "@temporalio/common";
import type { temporal } from "@temporalio/proto";
import {
  retryPolicyToProto,
  taskQueueToProto,
  failureToProto,
  durationToProto,
  priorityToProto,
} from "./support";

export function requiredField<T>(
  value: T | null | undefined,
  owner: string,
  field: string,
): T {
  if (value == null) {
    throw new Error(`missing required field ${owner}.${field}`);
  }
  return value;
}

export interface ActivityOptions {
  taskQueue?: string;
  retryPolicy: common.RetryPolicy;
  scheduleToCloseTimeout?: common.Duration;
  priority?: common.Priority;
}

export function activityOptionsToProto(
  model: ActivityOptions | null | undefined,
): temporal.api.activity.v1.IActivityOptions | undefined {
  if (model == null) {
    return undefined;
  }
  return {
    taskQueue: model.taskQueue == null ? undefined : taskQueueToProto(model.taskQueue),
    retryPolicy: retryPolicyToProto(
      requiredField(model.retryPolicy, "ActivityOptions", "retryPolicy"),
    ),
    scheduleToCloseTimeout:
      model.scheduleToCloseTimeout == null
        ? undefined
        : durationToProto(model.scheduleToCloseTimeout),
    priority: model.priority == null ? undefined : priorityToProto(model.priority),
  };
}

export interface FailureContainer {
  failure?: Error;
}

export function failureContainerToProto(
  model: FailureContainer | null | undefined,
): temporal.api.command.v1.IFailWorkflowExecutionCommandAttributes | undefined {
  if (model == null) {
    return undefined;
  }
  return {
    failure: model.failure == null ? undefined : failureToProto(model.failure),
  };
}
