# Generated by nex-gen. DO NOT EDIT!

from __future__ import annotations

from . import service as _service
from .operations.get_user import get_user
from ._resources.user import update_email
from ._resources.user import rename
from .operations.set_profile import set_profile
from ._resources.user import deactivate

__all__ = [
    "deactivate",
    "get_user",
    "rename",
    "set_profile",
    "update_email",
]


__nexus_operation_registry__ = {
    (
        "TypeShowcase",
        "GetUser",
    ): _service.TypeShowcase.get_user,
    (
        "TypeShowcase",
        "UpdateEmail",
    ): _service.TypeShowcase.update_email,
    (
        "TypeShowcase",
        "Rename",
    ): _service.TypeShowcase.rename,
    (
        "TypeShowcase",
        "SetProfile",
    ): _service.TypeShowcase.set_profile,
    (
        "TypeShowcase",
        "Deactivate",
    ): _service.TypeShowcase.deactivate,
}
