//! The shared .NET JSON-Schema runtime, emitted once per package as
//! `Definitions.cs`.
//!
//! Every other target emits a schema-independent runtime alongside its models —
//! `definitions.go`, `definitions.ts`, `_definitions.py`, and Java's
//! `ValidationException` / `Violation` / `SpecNumbers` classes. .NET had none, so
//! each generated class carried its own inlined copy of the read helpers and
//! reported failures one at a time as a bare `JsonException`.
//!
//! This module supplies the .NET half of that contract: a single aggregating
//! error over a list of `Violation { Path, Reason }`, so every constraint failure
//! in a payload surfaces in one shot (P11) rather than first-failure-wins. The
//! message format deliberately matches Go's `ValidationError.Error()` —
//! `"<n> validation error(s): <path>: <reason>; …"` — so the same payload
//! produces the same diagnostic text across targets.
//!
//! See `specs/json-schema/generated-file-layout.md` ("The shared `definitions`
//! file").

use std::path::PathBuf;

use crate::generator::dotnet::dotnet_namespace;
use crate::planning::PlannedTypeFamily;
use crate::spec::ExternalTypeSpec;
use crate::workspace::{ApiSpecNode, ApiSpecTree};

/// The generated file name, at the package root regardless of how many input
/// files the package aggregates.
pub(in crate::generator) const DEFINITIONS_FILE_NAME: &str = "Definitions.cs";

/// Fallback runtime namespace when the emitted model namespaces share no common
/// prefix (reachable only via divergent `@nexus.namespace` overrides).
const FALLBACK_NAMESPACE: &str = "NexGen.Generated";

/// Renders `Definitions.cs` for a planned tree, or `None` when the tree has no
/// JSON-Schema models.
///
/// The `None` case keeps the runtime out of WIT/proto-sourced output, which
/// carries its own support files and no JSON validator.
pub(in crate::generator) fn render_definitions_file(
    tree: &ApiSpecTree<PlannedTypeFamily>,
) -> Option<(PathBuf, String)> {
    if !has_json_models(&tree.root) {
        return None;
    }
    Some((
        PathBuf::from(DEFINITIONS_FILE_NAME),
        render(&runtime_namespace(tree)),
    ))
}

/// The namespace the shared runtime is declared in — the longest namespace
/// prefix common to every emitted model namespace.
///
/// For a single input this is just that input's namespace, so the runtime lands
/// beside the models. For a multi-input package (e.g. `kb`, whose leaves span
/// `NexGen.Generated.Kb` and `NexGen.Generated.Content.Block`) it is the shared
/// root, which C# resolves implicitly from any descendant namespace.
pub(in crate::generator) fn runtime_namespace(tree: &ApiSpecTree<PlannedTypeFamily>) -> String {
    let mut namespaces = Vec::new();
    collect_namespaces(&tree.root, &mut namespaces);
    common_namespace_prefix(&namespaces).unwrap_or_else(|| FALLBACK_NAMESPACE.to_string())
}

fn collect_namespaces(node: &ApiSpecNode<PlannedTypeFamily>, namespaces: &mut Vec<String>) {
    match node {
        ApiSpecNode::Leaf(leaf) => namespaces.push(dotnet_namespace(&leaf.spec)),
        ApiSpecNode::Branch(branch) => {
            for child in branch.children.values() {
                collect_namespaces(child, namespaces);
            }
        }
    }
}

/// The longest dot-separated prefix shared by every namespace, or `None` when
/// the list is empty or the namespaces diverge at the first segment.
fn common_namespace_prefix(namespaces: &[String]) -> Option<String> {
    let (first, rest) = namespaces.split_first()?;
    let mut prefix = first.split('.').collect::<Vec<_>>();
    for namespace in rest {
        let segments = namespace.split('.').collect::<Vec<_>>();
        let shared = prefix
            .iter()
            .zip(segments.iter())
            .take_while(|(left, right)| left == right)
            .count();
        prefix.truncate(shared);
        if prefix.is_empty() {
            return None;
        }
    }
    Some(prefix.join("."))
}

fn has_json_models(node: &ApiSpecNode<PlannedTypeFamily>) -> bool {
    match node {
        ApiSpecNode::Leaf(leaf) => leaf
            .spec
            .external_types()
            .any(|(_, binding)| matches!(binding.external_type, ExternalTypeSpec::Json(_))),
        ApiSpecNode::Branch(branch) => branch.children.values().any(has_json_models),
    }
}

fn render(namespace: &str) -> String {
    format!(
        r#"// <auto-generated />
// Generated by nex-gen. DO NOT EDIT!
#nullable enable
#pragma warning disable CS1591

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Text.Json;

namespace {namespace}
{{

    /// <summary>
    /// A single constraint failure. <see cref="Path"/> is the JSON member path
    /// (dotted for nested members); <see cref="Reason"/> is a human-readable
    /// message naming the bound and the offending value.
    /// </summary>
    [GeneratedCode("nex-gen", null)]
    public sealed class Violation
    {{
        public Violation(string path, string reason)
        {{
            Path = path;
            Reason = reason;
        }}

        public string Path {{ get; }}

        public string Reason {{ get; }}

        /// <summary>
        /// Returns <c>"Path: Reason"</c>, or just <c>Reason</c> when the path is
        /// empty.
        /// </summary>
        public override string ToString() =>
            Path.Length == 0 ? Reason : Path + ": " + Reason;
    }}

    /// <summary>
    /// Aggregates every <see cref="Violation"/> found while (de)serializing a
    /// value, surfacing them all in one error rather than stopping at the first.
    /// </summary>
    [GeneratedCode("nex-gen", null)]
    public sealed class ValidationException : JsonException
    {{
        public ValidationException(IReadOnlyList<Violation> violations)
            : base(FormatMessage(violations))
        {{
            Violations = violations;
        }}

        /// <summary>
        /// Every violation found, never a partial first-failure.
        /// </summary>
        public IReadOnlyList<Violation> Violations {{ get; }}

        private static string FormatMessage(IReadOnlyList<Violation> violations)
        {{
            var parts = new string[violations.Count];
            for (var index = 0; index < violations.Count; index++)
            {{
                parts[index] = violations[index].ToString();
            }}
            return $"{{violations.Count}} validation error(s): {{string.Join("; ", parts)}}";
        }}
    }}

    /// <summary>
    /// Read helpers shared by every generated model. Internal because they are an
    /// implementation detail of the generated (de)serialization path rather than
    /// part of the contract surface.
    /// </summary>
    [GeneratedCode("nex-gen", null)]
    internal static class JsonRuntime
    {{
        /// <summary>
        /// The largest integer a JSON number carries losslessly (2^53-1) — the
        /// same cap every other target enforces.
        /// </summary>
        private const double MaxSafeInteger = 9007199254740991d;

        /// <summary>
        /// Reads an optional member out of the extension-data bag, falling back to
        /// <paramref name="defaultValue"/> when absent.
        /// </summary>
        internal static T? ReadOptionalValue<T>(
            IDictionary<string, object?> members,
            string name,
            T? defaultValue = default)
        {{
            if (!members.TryGetValue(name, out var value))
            {{
                return defaultValue;
            }}
            return ReadJsonValue<T>(value);
        }}

        internal static T? ReadJsonValue<T>(object? value)
        {{
            if (value is null)
            {{
                return default;
            }}
            if (typeof(T) == typeof(long?) || typeof(T) == typeof(long))
            {{
                return (T?)(object?)ReadJsonInteger(value);
            }}
            if (value is JsonElement json)
            {{
                return json.Deserialize<T>();
            }}
            if (value is T typed)
            {{
                return typed;
            }}
            return (T)value;
        }}

        /// <summary>
        /// Reads a JSON number as an integer, rejecting non-integral values and
        /// anything beyond the lossless integer range.
        /// </summary>
        internal static long? ReadJsonInteger(object? value)
        {{
            if (value is null)
            {{
                return default;
            }}
            double number;
            if (value is JsonElement json)
            {{
                if (json.ValueKind == JsonValueKind.Null)
                {{
                    return default;
                }}
                if (json.ValueKind != JsonValueKind.Number)
                {{
                    throw new JsonException("expected integer");
                }}
                number = json.GetDouble();
            }}
            else if (value is long longValue)
            {{
                number = longValue;
            }}
            else if (value is int intValue)
            {{
                number = intValue;
            }}
            else
            {{
                throw new JsonException("expected integer");
            }}
            if (double.IsNaN(number)
                || double.IsInfinity(number)
                || Math.Truncate(number) != number
                || Math.Abs(number) > MaxSafeInteger)
            {{
                throw new JsonException("expected integer");
            }}
            return (long)number;
        }}

        /// <summary>
        /// Rejects an explicit JSON <c>null</c> for a member the contract declares
        /// non-nullable.
        /// </summary>
        internal static void RejectNull(string name, object? value)
        {{
            if (value is null || value is JsonElement {{ ValueKind: JsonValueKind.Null }})
            {{
                throw new JsonException($"{{name}}: explicit null not allowed");
            }}
        }}
    }}

}}
"#
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn common_prefix_of_one_namespace_is_itself() {
        assert_eq!(
            common_namespace_prefix(&["NexGen.ChatService".to_string()]),
            Some("NexGen.ChatService".to_string())
        );
    }

    #[test]
    fn common_prefix_stops_at_the_shared_root() {
        let namespaces = [
            "NexGen.Generated.Kb".to_string(),
            "NexGen.Generated.Content.Block".to_string(),
            "NexGen.Generated.Tree.Category".to_string(),
        ];

        assert_eq!(
            common_namespace_prefix(&namespaces),
            Some("NexGen.Generated".to_string())
        );
    }

    #[test]
    fn divergent_namespaces_have_no_common_prefix() {
        let namespaces = [
            "Temporalio.Workflows".to_string(),
            "NexGen.Generated.Kb".to_string(),
        ];

        assert_eq!(common_namespace_prefix(&namespaces), None);
    }

    #[test]
    fn common_prefix_of_nothing_is_none() {
        assert_eq!(common_namespace_prefix(&[]), None);
    }

    #[test]
    fn does_not_treat_a_partial_segment_match_as_shared() {
        let namespaces = ["NexGen.Chat".to_string(), "NexGen.ChatService".to_string()];

        assert_eq!(
            common_namespace_prefix(&namespaces),
            Some("NexGen".to_string())
        );
    }

    #[test]
    fn renders_aggregating_error_over_violation_list() {
        let rendered = render("NexGen.Generated");

        assert!(rendered.contains("namespace NexGen.Generated\n{"));
        assert!(rendered.contains("public sealed class Violation"));
        assert!(rendered.contains("public sealed class ValidationException : JsonException"));
        assert!(rendered.contains("IReadOnlyList<Violation> Violations"));
        // Message shape matches Go's ValidationError.Error() for cross-target
        // diagnostic parity.
        assert!(rendered.contains("validation error(s): "));
    }
}
