// <auto-generated />
// Generated by nex-gen. DO NOT EDIT!
#nullable enable
#pragma warning disable CS1591

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using System.Threading.Tasks;
using Google.Protobuf.WellKnownTypes;
using Temporalio.Converters;
using Temporalio.Workflows;

namespace NexGen.ChatService
{

    [GeneratedCode("nex-gen", null)]
    public static class Operations
    {
        /// <summary>
        /// Post a message to a room.
        /// </summary>
        /// <param name="endpoint">Endpoint for the service.</param>
        [GeneratedCode("nex-gen", null)]
        public static async Task<SendMessageOutput> SendMessageAsync(string endpoint, SendMessageInput request)
        {
            var client = Workflow.CreateNexusWorkflowClient<IChatService>(endpoint);
            var result = await client.ExecuteNexusOperationAsync<SendMessageOutput>(svc => svc.SendMessage(request)).ConfigureAwait(true);
            return result;
        }

        /// <summary>
        /// Look up a room by id.
        /// </summary>
        /// <param name="endpoint">Endpoint for the service.</param>
        [GeneratedCode("nex-gen", null)]
        public static async Task<Room> GetRoomAsync(string endpoint, GetRoomInput request)
        {
            var client = Workflow.CreateNexusWorkflowClient<IChatService>(endpoint);
            var result = await client.ExecuteNexusOperationAsync<Room>(svc => svc.GetRoom(request)).ConfigureAwait(true);
            return result;
        }

        /// <summary>
        /// Liveness probe.
        /// </summary>
        /// <param name="endpoint">Endpoint for the service.</param>
        [GeneratedCode("nex-gen", null)]
        public static async Task PingAsync(string endpoint)
        {
            var client = Workflow.CreateNexusWorkflowClient<IChatService>(endpoint);
            await client.ExecuteNexusOperationAsync(svc => svc.Ping()).ConfigureAwait(true);
        }

    }

}
