// <auto-generated />
// Generated by nex-gen. DO NOT EDIT!
#nullable enable
#pragma warning disable CS1591

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using System.Threading.Tasks;
using Google.Protobuf.WellKnownTypes;
using Temporalio.Converters;
using Temporalio.Workflows;

namespace NexGen.FunctionExecution
{

    [GeneratedCode("nex-gen", null)]
    public static class Operations
    {
        [GeneratedCode("nex-gen", null)]
        private const string FunctionExecutionEndpoint = "function-execution";

        [GeneratedCode("nex-gen", null)]
        public static async Task<ExecuteFunctionResult> ExecuteFunctionAsync(ExecuteFunctionRequest request)
        {
            var client = Workflow.CreateNexusWorkflowClient<IFunctionExecution>(FunctionExecutionEndpoint);
            var result = await client.ExecuteNexusOperationAsync<ExecuteFunctionResult>(svc => svc.ExecuteFunction(request)).ConfigureAwait(true);
            return result;
        }

        [GeneratedCode("nex-gen", null)]
        public static async Task<ExecuteCountedFunctionResult> ExecuteCountedFunctionAsync(ExecuteCountedFunctionRequest request)
        {
            var client = Workflow.CreateNexusWorkflowClient<IFunctionExecution>(FunctionExecutionEndpoint);
            var result = await client.ExecuteNexusOperationAsync<ExecuteCountedFunctionResult>(svc => svc.ExecuteCountedFunction(request)).ConfigureAwait(true);
            return result;
        }

        [GeneratedCode("nex-gen", null)]
        public static async Task<ExecuteNamedFunctionResult> ExecuteNamedFunctionAsync(ExecuteNamedFunctionRequest request)
        {
            var client = Workflow.CreateNexusWorkflowClient<IFunctionExecution>(FunctionExecutionEndpoint);
            var result = await client.ExecuteNexusOperationAsync<ExecuteNamedFunctionResult>(svc => svc.ExecuteNamedFunction(request)).ConfigureAwait(true);
            return result;
        }

        [GeneratedCode("nex-gen", null)]
        public static async Task<ExecuteVarargsFunctionResult> ExecuteVarargsFunctionAsync(ExecuteVarargsFunctionRequest request)
        {
            var client = Workflow.CreateNexusWorkflowClient<IFunctionExecution>(FunctionExecutionEndpoint);
            var result = await client.ExecuteNexusOperationAsync<ExecuteVarargsFunctionResult>(svc => svc.ExecuteVarargsFunction(request)).ConfigureAwait(true);
            return result;
        }

        [GeneratedCode("nex-gen", null)]
        public static async Task<ExecuteNamedVarargsFunctionResult> ExecuteNamedVarargsFunctionAsync(ExecuteNamedVarargsFunctionRequest request)
        {
            var client = Workflow.CreateNexusWorkflowClient<IFunctionExecution>(FunctionExecutionEndpoint);
            var result = await client.ExecuteNexusOperationAsync<ExecuteNamedVarargsFunctionResult>(svc => svc.ExecuteNamedVarargsFunction(request)).ConfigureAwait(true);
            return result;
        }

    }

}
