// <auto-generated />
// Generated by nex-gen. DO NOT EDIT!
#nullable enable
#pragma warning disable CS1591

using System;
using System.Collections.Generic;
using NexusRpc;

namespace NexGen.FunctionExecution
{

    [NexusService("FunctionExecution")]
    internal interface IFunctionExecution
    {
        [NexusOperation("ExecuteFunction")]
        ExecuteFunctionResult ExecuteFunction(ExecuteFunctionRequest request);

        [NexusOperation("ExecuteCountedFunction")]
        ExecuteCountedFunctionResult ExecuteCountedFunction(ExecuteCountedFunctionRequest request);

        [NexusOperation("ExecuteNamedFunction")]
        ExecuteNamedFunctionResult ExecuteNamedFunction(ExecuteNamedFunctionRequest request);

        [NexusOperation("ExecuteVarargsFunction")]
        ExecuteVarargsFunctionResult ExecuteVarargsFunction(ExecuteVarargsFunctionRequest request);

        [NexusOperation("ExecuteNamedVarargsFunction")]
        ExecuteNamedVarargsFunctionResult ExecuteNamedVarargsFunction(ExecuteNamedVarargsFunctionRequest request);

    }

    public static class NexGenOperationRegistry
    {
        internal static IReadOnlyDictionary<string, ServiceDefinition> Services { get; } =
            new Dictionary<string, ServiceDefinition>
            {
                ["FunctionExecution"] = ServiceDefinition.FromType<IFunctionExecution>(),
            };

        public static IReadOnlyDictionary<(string Service, string Operation), OperationDefinition> Operations { get; } =
            new Dictionary<(string Service, string Operation), OperationDefinition>
            {
                [("FunctionExecution", "ExecuteFunction")] = Services["FunctionExecution"].Operations["ExecuteFunction"],
                [("FunctionExecution", "ExecuteCountedFunction")] = Services["FunctionExecution"].Operations["ExecuteCountedFunction"],
                [("FunctionExecution", "ExecuteNamedFunction")] = Services["FunctionExecution"].Operations["ExecuteNamedFunction"],
                [("FunctionExecution", "ExecuteVarargsFunction")] = Services["FunctionExecution"].Operations["ExecuteVarargsFunction"],
                [("FunctionExecution", "ExecuteNamedVarargsFunction")] = Services["FunctionExecution"].Operations["ExecuteNamedVarargsFunction"],
            };
    }

}
