// Code generated by nex-gen. DO NOT EDIT.
package typeshowcase

import (
	"go.temporal.io/sdk/workflow"
)

// --- Helpers ---

func nexGenNewNexusClient(endpoint string, service string) workflow.NexusClient {
	return workflow.NewNexusClient(endpoint, service)
}

// --- Datatypes ---

type getUserRequest struct {
	UserId           string
	ConsistencyToken *string
}

type updateEmailRequest struct {
	UserId string
	Email  string
}

type renameRequest struct {
	UserId      string
	DisplayName string
}

type setProfileRequest struct {
	UserId  string
	Profile UserProfile
}

type recordSyncRequest struct {
	UserId string
	Report SyncReport
}

type deactivateRequest struct {
	UserId string
	Reason *string
}

// --- Resources ---

type User struct {
	// Required.
	UserId string
	// Required.
	Email string
	// Required.
	DisplayName string
	// Required.
	Status UserStatus
	// Required.
	Profile UserProfile
}

func NewUser(userId string, email string, displayName string, status UserStatus, profile UserProfile) *User {
	return &User{
		UserId:      userId,
		Email:       email,
		DisplayName: displayName,
		Status:      status,
		Profile:     profile,
	}
}

func (u *User) UpdateEmail(ctx workflow.Context, email string) workflow.Future {
	return updateEmail(ctx, nexGenNewNexusClient("type-showcase", "TypeShowcase"), updateEmailRequest{UserId: u.UserId, Email: email})
}

func (u *User) Rename(ctx workflow.Context, displayName string) workflow.Future {
	return rename(ctx, nexGenNewNexusClient("type-showcase", "TypeShowcase"), renameRequest{UserId: u.UserId, DisplayName: displayName})
}

func (u *User) Deactivate(ctx workflow.Context, reason string) workflow.Future {
	var reasonPtr *string
	if reason != "" {
		reasonPtr = &reason
	}
	return deactivate(ctx, nexGenNewNexusClient("type-showcase", "TypeShowcase"), deactivateRequest{UserId: u.UserId, Reason: reasonPtr})
}

// --- Operations (internal) ---

func getUser(ctx workflow.Context, client workflow.NexusClient, request getUserRequest) workflow.Future {
	fut := client.ExecuteOperation(ctx, "GetUser", request, workflow.NexusOperationOptions{})
	return fut
}

func updateEmail(ctx workflow.Context, client workflow.NexusClient, request updateEmailRequest) workflow.Future {
	fut := client.ExecuteOperation(ctx, "UpdateEmail", request, workflow.NexusOperationOptions{})
	return fut
}

func rename(ctx workflow.Context, client workflow.NexusClient, request renameRequest) workflow.Future {
	fut := client.ExecuteOperation(ctx, "Rename", request, workflow.NexusOperationOptions{})
	return fut
}

func setProfile(ctx workflow.Context, client workflow.NexusClient, request setProfileRequest) workflow.Future {
	fut := client.ExecuteOperation(ctx, "SetProfile", request, workflow.NexusOperationOptions{})
	return fut
}

func recordSync(ctx workflow.Context, client workflow.NexusClient, request recordSyncRequest) workflow.Future {
	fut := client.ExecuteOperation(ctx, "RecordSync", request, workflow.NexusOperationOptions{})
	return fut
}

func deactivate(ctx workflow.Context, client workflow.NexusClient, request deactivateRequest) workflow.Future {
	fut := client.ExecuteOperation(ctx, "Deactivate", request, workflow.NexusOperationOptions{})
	return fut
}

// --- Service clients ---

type TypeShowcaseClient struct {
	client workflow.NexusClient
}

func NewTypeShowcaseClient(endpoint string) *TypeShowcaseClient {
	return &TypeShowcaseClient{client: nexGenNewNexusClient(endpoint, "TypeShowcase")}
}

// --- Operations (public API) ---

type UserStatus int32

const (
	UserStatusActive    UserStatus = 0
	UserStatusSuspended UserStatus = 1
	UserStatusDeleted   UserStatus = 2
)

type UserCapability int32

const (
	UserCapabilityReadProfile UserCapability = 1 << 0
	UserCapabilityUpdateEmail UserCapability = 1 << 1
	UserCapabilityDeactivate  UserCapability = 1 << 2
)

type NotificationTarget interface {
	isNotificationTarget()
}

type NotificationTargetEmail struct {
	Value string
}

func (NotificationTargetEmail) isNotificationTarget() {}

type NotificationTargetSms struct {
	Value string
}

func (NotificationTargetSms) isNotificationTarget() {}

type NotificationTargetNone struct{}

func (NotificationTargetNone) isNotificationTarget() {}

type UserProfile struct {
	// Required.
	Tags []string
	// Required.
	Metadata map[string]string
	// Required.
	Capabilities UserCapability
	// Required.
	SyncState Result[string, string]
	// Required.
	NotificationTarget NotificationTarget
	// Optional.
	Address *PostalAddress
}

type Result[T, E any] struct {
	// Optional.
	Result T
	// Optional.
	Error E
}

type PostalAddress struct {
	// Required.
	Street string
	// Required.
	City string
	// Required.
	Country string
	// Optional.
	Coordinates *Tuple2[float64, float64]
}

type Tuple2[T1, T2 any] struct {
	// Required.
	First T1
	// Required.
	Second T2
}

type SyncReport struct {
	// Required.
	Route []Tuple2[float64, float64]
	// Required.
	Attempts []Result[string, string]
	// Required.
	RegionStatus map[string]Result[string, string]
}

type GetUserOptions struct {
	// Required.
	UserId string
	// Optional.
	ConsistencyToken string
}

func GetUser(ctx workflow.Context, opts GetUserOptions) workflow.Future {
	var consistencyToken *string
	if opts.ConsistencyToken != "" {
		consistencyToken = &opts.ConsistencyToken
	}
	client := nexGenNewNexusClient("type-showcase", "TypeShowcase")
	return getUser(ctx, client, getUserRequest{
		UserId:           opts.UserId,
		ConsistencyToken: consistencyToken,
	})
}

type UpdateEmailOptions struct {
	// Required.
	UserId string
	// Required.
	Email string
}

func UpdateEmail(ctx workflow.Context, opts UpdateEmailOptions) workflow.Future {
	client := nexGenNewNexusClient("type-showcase", "TypeShowcase")
	return updateEmail(ctx, client, updateEmailRequest{
		UserId: opts.UserId,
		Email:  opts.Email,
	})
}

type RenameOptions struct {
	// Required.
	UserId string
	// Required.
	DisplayName string
}

func Rename(ctx workflow.Context, opts RenameOptions) workflow.Future {
	client := nexGenNewNexusClient("type-showcase", "TypeShowcase")
	return rename(ctx, client, renameRequest{
		UserId:      opts.UserId,
		DisplayName: opts.DisplayName,
	})
}

type SetProfileOptions struct {
	// Required.
	UserId string
	// Required.
	Profile UserProfile
}

func SetProfile(ctx workflow.Context, opts SetProfileOptions) workflow.Future {
	client := nexGenNewNexusClient("type-showcase", "TypeShowcase")
	return setProfile(ctx, client, setProfileRequest{
		UserId:  opts.UserId,
		Profile: opts.Profile,
	})
}

type RecordSyncOptions struct {
	// Required.
	UserId string
	// Required.
	Report SyncReport
}

func RecordSync(ctx workflow.Context, opts RecordSyncOptions) workflow.Future {
	client := nexGenNewNexusClient("type-showcase", "TypeShowcase")
	return recordSync(ctx, client, recordSyncRequest{
		UserId: opts.UserId,
		Report: opts.Report,
	})
}

type DeactivateOptions struct {
	// Required.
	UserId string
	// Optional.
	Reason string
}

func Deactivate(ctx workflow.Context, opts DeactivateOptions) workflow.Future {
	var reason *string
	if opts.Reason != "" {
		reason = &opts.Reason
	}
	client := nexGenNewNexusClient("type-showcase", "TypeShowcase")
	return deactivate(ctx, client, deactivateRequest{
		UserId: opts.UserId,
		Reason: reason,
	})
}
