// <auto-generated />
// Generated by nex-gen. DO NOT EDIT!
#nullable enable
#pragma warning disable CS1591

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Threading.Tasks;
using NexusRpc;
using NexGen.Generated.Content.Block;
using NexGen.Generated.Content.Page;
using NexGen.Generated.Tree.Category;

namespace NexGen.Generated.Kb
{

    [GeneratedCode("nex-gen", null)]
    [NexusService("example.kb.v1.KnowledgeBaseService")]
    internal interface IKnowledgeBaseService
    {
        /// <summary>
        /// Fetch a page by id.
        /// </summary>
        [GeneratedCode("nex-gen", null)]
        [NexusOperation("GetPage")]
        Page GetPage(GetPageInput request);

        /// <summary>
        /// Create or update a content block.
        /// </summary>
        [GeneratedCode("nex-gen", null)]
        [NexusOperation("PutBlock")]
        PutBlockOutput PutBlock(Block request);

        /// <summary>
        /// Fetch the category tree rooted at a category.
        /// </summary>
        [GeneratedCode("nex-gen", null)]
        [NexusOperation("GetCategoryTree")]
        Category GetCategoryTree(GetCategoryTreeInput request);

    }

}
