// Generated by nexgen v0.2.1. DO NOT EDIT!

import * as nexus from "nexus-rpc";
import type { temporal } from "@temporalio/proto";

/**
 * @experimental This API is experimental and subject to change.
 */
export const workflowService = nexus.service(
  "temporal.api.workflowservice.v1.WorkflowService",
  {
    /**
     * Signal a workflow, starting it first if needed.
     *
     * @experimental This API is experimental and subject to change.
     */
    signalWithStartWorkflow: nexus.operation<
      temporal.api.workflowservice.v1.ISignalWithStartWorkflowExecutionRequest,
      temporal.api.workflowservice.v1.ISignalWithStartWorkflowExecutionResponse
    >({ name: "SignalWithStartWorkflowExecution" }),
  },
);

export const operationRegistry = [
  {
    service: "temporal.api.workflowservice.v1.WorkflowService",
    operation: "SignalWithStartWorkflowExecution",
    inputType:
      "temporal.api.workflowservice.v1.SignalWithStartWorkflowExecutionRequest",
    outputType:
      "temporal.api.workflowservice.v1.SignalWithStartWorkflowExecutionResponse",
  },
] as const;
