// Code generated by nex-gen. DO NOT EDIT.
package temporalsystem

import (
	"errors"
	"time"

	common "go.temporal.io/api/common/v1"
	workflowservice "go.temporal.io/api/workflowservice/v1"
	"go.temporal.io/sdk/workflow"
)

// --- Datatypes ---

type startWorkflowRequest struct {
	// Required.
	Workflow string
	// Arguments for the workflow.
	Args []any
	// Required.
	WorkflowId string
	// Required.
	TaskQueue          string
	WorkflowStartDelay *time.Duration
}

func (m startWorkflowRequest) toProto(ctx workflow.Context) (*workflowservice.StartWorkflowExecutionRequest, error) {
	message := &workflowservice.StartWorkflowExecutionRequest{}
	{
		converted, err := workflowTypeToProto(ctx, &m.Workflow)
		if err != nil {
			return nil, err
		}
		message.WorkflowType = converted
	}
	{
		converted, err := payloadsToProto(ctx, m.Args)
		if err != nil {
			return nil, err
		}
		message.Input = converted
	}
	message.WorkflowId = m.WorkflowId
	{
		converted, err := taskQueueToProto(ctx, &m.TaskQueue)
		if err != nil {
			return nil, err
		}
		message.TaskQueue = converted
	}
	{
		converted, err := durationToProto(ctx, m.WorkflowStartDelay)
		if err != nil {
			return nil, err
		}
		message.WorkflowStartDelay = converted
	}
	message.Namespace = workflowNamespace(ctx)
	return message, nil
}

type cancelWorkflowRequest struct {
	// Required.
	WorkflowExecution WorkflowExecution
	Reason            *string
}

func (m cancelWorkflowRequest) toProto(ctx workflow.Context) (*workflowservice.RequestCancelWorkflowExecutionRequest, error) {
	message := &workflowservice.RequestCancelWorkflowExecutionRequest{}
	{
		converted, err := m.WorkflowExecution.toProto(ctx)
		if err != nil {
			return nil, err
		}
		message.WorkflowExecution = converted
	}
	if m.Reason != nil {
		message.Reason = (*m.Reason)
	}
	message.Namespace = workflowNamespace(ctx)
	return message, nil
}

// --- Resources ---

type StartedWorkflow struct {
	// Required.
	Namespace string
	// Required.
	WorkflowId string
	RunId      *string
}

func (u *StartedWorkflow) Cancel(ctx workflow.Context, reason *string) workflow.NexusOperationFuture {
	return cancelWorkflow(ctx, cancelWorkflowRequest{WorkflowExecution: WorkflowExecution{WorkflowId: u.WorkflowId, RunId: u.RunId}, Reason: reason})
}

func (u *StartedWorkflow) RestartWorkflow(ctx workflow.Context, workflow string, taskQueue string) workflow.NexusOperationFuture {
	return restartWorkflow(ctx, startWorkflowRequest{WorkflowId: u.WorkflowId, Workflow: workflow, TaskQueue: taskQueue})
}

func (u *StartedWorkflow) GetResult(ctx workflow.Context) workflow.NexusOperationFuture {
	panic("StartedWorkflow.GetResult is not yet implemented")
}

// --- Operations (internal) ---

func startWorkflow(ctx workflow.Context, request startWorkflowRequest) workflow.NexusOperationFuture {
	requestProto, err := request.toProto(ctx)
	if err != nil {
		return nexGenFailedNexusOperationFuture(ctx, err)
	}
	c := workflow.NewNexusClient("temporal-system", "StartWorkflowService")
	fut := c.ExecuteOperation(ctx, "StartWorkflow", requestProto, workflow.NexusOperationOptions{})
	return &nexGenNexusOperationFuture{operation: fut, get: func(ctx workflow.Context, valuePtr any) error {
		if valuePtr == nil {
			return fut.Get(ctx, nil)
		}
		var result workflowservice.StartWorkflowExecutionResponse
		if err := fut.Get(ctx, &result); err != nil {
			return err
		}
		namespace := requestProto.GetNamespace()
		runIdValue := result.GetRunId()
		var runId *string
		if runIdValue != "" {
			runId = &runIdValue
		}
		value := StartedWorkflow{
			Namespace:  namespace,
			WorkflowId: request.WorkflowId,
			RunId:      runId,
		}
		typedValue, ok := valuePtr.(*StartedWorkflow)
		if !ok {
			return nexGenFutureResultTypeError()
		}
		*typedValue = value
		return nil
	}}
}

func restartWorkflow(ctx workflow.Context, request startWorkflowRequest) workflow.NexusOperationFuture {
	requestProto, err := request.toProto(ctx)
	if err != nil {
		return nexGenFailedNexusOperationFuture(ctx, err)
	}
	c := workflow.NewNexusClient("temporal-system", "StartWorkflowService")
	fut := c.ExecuteOperation(ctx, "RestartWorkflow", requestProto, workflow.NexusOperationOptions{})
	return &nexGenNexusOperationFuture{operation: fut, get: func(ctx workflow.Context, valuePtr any) error {
		if valuePtr == nil {
			return fut.Get(ctx, nil)
		}
		var result workflowservice.StartWorkflowExecutionResponse
		if err := fut.Get(ctx, &result); err != nil {
			return err
		}
		namespace := requestProto.GetNamespace()
		runIdValue := result.GetRunId()
		var runId *string
		if runIdValue != "" {
			runId = &runIdValue
		}
		value := StartedWorkflow{
			Namespace:  namespace,
			WorkflowId: request.WorkflowId,
			RunId:      runId,
		}
		typedValue, ok := valuePtr.(*StartedWorkflow)
		if !ok {
			return nexGenFutureResultTypeError()
		}
		*typedValue = value
		return nil
	}}
}

func cancelWorkflow(ctx workflow.Context, request cancelWorkflowRequest) workflow.NexusOperationFuture {
	requestProto, err := request.toProto(ctx)
	if err != nil {
		return nexGenFailedNexusOperationFuture(ctx, err)
	}
	c := workflow.NewNexusClient("temporal-system", "StartWorkflowService")
	fut := c.ExecuteOperation(ctx, "CancelWorkflow", requestProto, workflow.NexusOperationOptions{})
	return &nexGenNexusOperationFuture{operation: fut, get: func(ctx workflow.Context, valuePtr any) error {
		if valuePtr == nil {
			return fut.Get(ctx, nil)
		}
		var result workflowservice.RequestCancelWorkflowExecutionResponse
		if err := fut.Get(ctx, &result); err != nil {
			return err
		}
		value, err := cancelWorkflowResponseFromProto(ctx, &result)
		if err != nil {
			return err
		}
		typedValue, ok := valuePtr.(*CancelWorkflowResponse)
		if !ok {
			return nexGenFutureResultTypeError()
		}
		*typedValue = value
		return nil
	}}
}

// --- Operations (public API) ---

type WorkflowExecution struct {
	// Required.
	WorkflowId string
	RunId      *string
}

func (m WorkflowExecution) toProto(ctx workflow.Context) (*common.WorkflowExecution, error) {
	message := &common.WorkflowExecution{}
	message.WorkflowId = m.WorkflowId
	if m.RunId != nil {
		message.RunId = (*m.RunId)
	}
	return message, nil
}

func workflowExecutionFromProto(ctx workflow.Context, proto *common.WorkflowExecution) (WorkflowExecution, error) {
	value := WorkflowExecution{}
	value.WorkflowId = proto.GetWorkflowId()
	converted := proto.GetRunId()
	value.RunId = &converted
	return value, nil
}

type CancelWorkflowResponse struct {
}

func (m CancelWorkflowResponse) toProto(ctx workflow.Context) (*workflowservice.RequestCancelWorkflowExecutionResponse, error) {
	message := &workflowservice.RequestCancelWorkflowExecutionResponse{}
	return message, nil
}

func cancelWorkflowResponseFromProto(ctx workflow.Context, proto *workflowservice.RequestCancelWorkflowExecutionResponse) (CancelWorkflowResponse, error) {
	value := CancelWorkflowResponse{}
	return value, nil
}

type StartWorkflowOptions struct {
	// Arguments for the workflow.
	Args               []any
	WorkflowStartDelay *time.Duration
}

func StartWorkflow[WorkflowF interface {
	~string | func(workflow.Context, ...any) any
}](
	ctx workflow.Context,
	workflow WorkflowF,
	workflowId string,
	taskQueue string,
	opts StartWorkflowOptions,
) workflow.NexusOperationFuture {
	return startWorkflow(ctx, startWorkflowRequest{
		Workflow:           nexGenFunctionName(workflow),
		Args:               opts.Args,
		WorkflowId:         workflowId,
		TaskQueue:          taskQueue,
		WorkflowStartDelay: opts.WorkflowStartDelay,
	})
}

// Input args: Arguments for the workflow.
func StartWorkflowWithArgs[WorkflowF interface {
	~string | func(workflow.Context, ...any) any
}](
	ctx workflow.Context,
	workflow WorkflowF,
	workflowId string,
	taskQueue string,
	opts StartWorkflowOptions,
	args ...any,
) workflow.NexusOperationFuture {
	if len(args) > 0 && opts.Args != nil {
		return nexGenFailedNexusOperationFuture(ctx, errors.New("cannot specify both positional arguments and args"))
	}
	if len(args) == 0 {
		args = opts.Args
	}
	return startWorkflow(ctx, startWorkflowRequest{
		Workflow:           nexGenFunctionName(workflow),
		Args:               args,
		WorkflowId:         workflowId,
		TaskQueue:          taskQueue,
		WorkflowStartDelay: opts.WorkflowStartDelay,
	})
}

type RestartWorkflowOptions struct {
	// Arguments for the workflow.
	Args               []any
	WorkflowStartDelay *time.Duration
}

func RestartWorkflow[WorkflowF interface {
	~string | func(workflow.Context, ...any) any
}](
	ctx workflow.Context,
	workflow WorkflowF,
	workflowId string,
	taskQueue string,
	opts RestartWorkflowOptions,
) workflow.NexusOperationFuture {
	return restartWorkflow(ctx, startWorkflowRequest{
		Workflow:           nexGenFunctionName(workflow),
		Args:               opts.Args,
		WorkflowId:         workflowId,
		TaskQueue:          taskQueue,
		WorkflowStartDelay: opts.WorkflowStartDelay,
	})
}

// Input args: Arguments for the workflow.
func RestartWorkflowWithArgs[WorkflowF interface {
	~string | func(workflow.Context, ...any) any
}](
	ctx workflow.Context,
	workflow WorkflowF,
	workflowId string,
	taskQueue string,
	opts RestartWorkflowOptions,
	args ...any,
) workflow.NexusOperationFuture {
	if len(args) > 0 && opts.Args != nil {
		return nexGenFailedNexusOperationFuture(ctx, errors.New("cannot specify both positional arguments and args"))
	}
	if len(args) == 0 {
		args = opts.Args
	}
	return restartWorkflow(ctx, startWorkflowRequest{
		Workflow:           nexGenFunctionName(workflow),
		Args:               args,
		WorkflowId:         workflowId,
		TaskQueue:          taskQueue,
		WorkflowStartDelay: opts.WorkflowStartDelay,
	})
}

type CancelWorkflowOptions struct {
	Reason *string
}

func CancelWorkflow(ctx workflow.Context, workflowExecution WorkflowExecution, opts CancelWorkflowOptions) workflow.NexusOperationFuture {
	return cancelWorkflow(ctx, cancelWorkflowRequest{
		WorkflowExecution: workflowExecution,
		Reason:            opts.Reason,
	})
}
