// <auto-generated />
// Generated by nexgen v0.2.2. DO NOT EDIT!
#nullable enable
#pragma warning disable CS1591

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using Temporalio.Converters;
using Nexgen.Support;

namespace Nexgen.StartWorkflowService
{

    [Temporalio.Converters.TemporalTransferTypeConverter(typeof(CancelWorkflowRequest.TransferTypeConverter))]
    [GeneratedCode("nexgen", null)]
    internal record CancelWorkflowRequest
    {
        internal CancelWorkflowRequest(WorkflowExecution workflowExecution, string @namespace)
        {
            WorkflowExecution = workflowExecution;
            Namespace = @namespace;
        }

        public WorkflowExecution WorkflowExecution { get; init; }
        public string? Reason { get; init; }
        public string Namespace { get; init; }

        internal static CancelWorkflowRequest FromTransferType(Temporalio.Api.WorkflowService.V1.RequestCancelWorkflowExecutionRequest wire)
        {
            return new CancelWorkflowRequest(WorkflowExecution.FromTransferType(wire.WorkflowExecution), wire.Namespace)
            {
                Reason = string.IsNullOrEmpty(wire.Reason) ? null : wire.Reason,
            };
        }

        internal Temporalio.Api.WorkflowService.V1.RequestCancelWorkflowExecutionRequest ToTransferType()
        {
            var proto = new Temporalio.Api.WorkflowService.V1.RequestCancelWorkflowExecutionRequest();
            proto.Namespace = Namespace;
            proto.WorkflowExecution = (Temporalio.Api.Common.V1.WorkflowExecution)WorkflowExecution.ToTransferType();
            if (Reason is { } reason)
            {
                proto.Reason = reason;
            }
            return proto;
        }

        public sealed class TransferTypeConverter : Temporalio.Converters.ITemporalTransferTypeConverter
        {
            public System.Type TransferType => typeof(Temporalio.Api.WorkflowService.V1.RequestCancelWorkflowExecutionRequest);

            public object? ToTransferType(object? value) => value is null ? null : ((CancelWorkflowRequest)value).ToTransferType();

            public object? FromTransferType(object? transferType) => transferType is null ? null : CancelWorkflowRequest.FromTransferType((Temporalio.Api.WorkflowService.V1.RequestCancelWorkflowExecutionRequest)transferType);
        }

    }

    [Temporalio.Converters.TemporalTransferTypeConverter(typeof(CancelWorkflowResponse.TransferTypeConverter))]
    [GeneratedCode("nexgen", null)]
    public record CancelWorkflowResponse
    {
        internal static CancelWorkflowResponse FromTransferType(Temporalio.Api.WorkflowService.V1.RequestCancelWorkflowExecutionResponse wire)
        {
            return new CancelWorkflowResponse();
        }

        internal Temporalio.Api.WorkflowService.V1.RequestCancelWorkflowExecutionResponse ToTransferType()
        {
            var proto = new Temporalio.Api.WorkflowService.V1.RequestCancelWorkflowExecutionResponse();
            return proto;
        }

        public sealed class TransferTypeConverter : Temporalio.Converters.ITemporalTransferTypeConverter
        {
            public System.Type TransferType => typeof(Temporalio.Api.WorkflowService.V1.RequestCancelWorkflowExecutionResponse);

            public object? ToTransferType(object? value) => value is null ? null : ((CancelWorkflowResponse)value).ToTransferType();

            public object? FromTransferType(object? transferType) => transferType is null ? null : CancelWorkflowResponse.FromTransferType((Temporalio.Api.WorkflowService.V1.RequestCancelWorkflowExecutionResponse)transferType);
        }

    }

    [Temporalio.Converters.TemporalTransferTypeConverter(typeof(StartWorkflowRequest.TransferTypeConverter))]
    [GeneratedCode("nexgen", null)]
    internal record StartWorkflowRequest
    {
        internal StartWorkflowRequest(string workflow, string workflowId, string taskQueue, string @namespace)
        {
            Workflow = workflow;
            WorkflowId = workflowId;
            TaskQueue = taskQueue;
            Namespace = @namespace;
        }

        public string Workflow { get; init; }
        public string WorkflowId { get; init; }
        public string TaskQueue { get; init; }
        public System.TimeSpan? WorkflowStartDelay { get; init; }
        public string Namespace { get; init; }

        internal static StartWorkflowRequest FromTransferType(Temporalio.Api.WorkflowService.V1.StartWorkflowExecutionRequest wire)
        {
            return new StartWorkflowRequest(Nexgen.Support.ProtoExtensions.FromWorkflowTypeProto(wire.WorkflowType), wire.WorkflowId, Nexgen.Support.ProtoExtensions.FromTaskQueueProto(wire.TaskQueue), wire.Namespace)
            {
                WorkflowStartDelay = wire.WorkflowStartDelay == null ? null : Nexgen.Support.ProtoExtensions.FromDurationProto(wire.WorkflowStartDelay),
            };
        }

        internal Temporalio.Api.WorkflowService.V1.StartWorkflowExecutionRequest ToTransferType()
        {
            var proto = new Temporalio.Api.WorkflowService.V1.StartWorkflowExecutionRequest();
            proto.Namespace = Namespace;
            proto.WorkflowType = Nexgen.Support.ProtoExtensions.ToWorkflowTypeProto(Workflow);
            proto.WorkflowId = WorkflowId;
            proto.TaskQueue = Nexgen.Support.ProtoExtensions.ToTaskQueueProto(TaskQueue);
            if (WorkflowStartDelay is { } workflowStartDelay)
            {
                proto.WorkflowStartDelay = workflowStartDelay.ToProto();
            }
            return proto;
        }

        public sealed class TransferTypeConverter : Temporalio.Converters.ITemporalTransferTypeConverter
        {
            public System.Type TransferType => typeof(Temporalio.Api.WorkflowService.V1.StartWorkflowExecutionRequest);

            public object? ToTransferType(object? value) => value is null ? null : ((StartWorkflowRequest)value).ToTransferType();

            public object? FromTransferType(object? transferType) => transferType is null ? null : StartWorkflowRequest.FromTransferType((Temporalio.Api.WorkflowService.V1.StartWorkflowExecutionRequest)transferType);
        }

    }

    [Temporalio.Converters.TemporalTransferTypeConverter(typeof(StartWorkflowResult.TransferTypeConverter))]
    [GeneratedCode("nexgen", null)]
    internal record StartWorkflowResult
    {
        public string? RunId { get; init; }

        internal static StartWorkflowResult FromTransferType(Temporalio.Api.WorkflowService.V1.StartWorkflowExecutionResponse wire)
        {
            return new StartWorkflowResult()
            {
                RunId = string.IsNullOrEmpty(wire.RunId) ? null : wire.RunId,
            };
        }

        internal Temporalio.Api.WorkflowService.V1.StartWorkflowExecutionResponse ToTransferType()
        {
            var proto = new Temporalio.Api.WorkflowService.V1.StartWorkflowExecutionResponse();
            if (RunId is { } runId)
            {
                proto.RunId = runId;
            }
            return proto;
        }

        public sealed class TransferTypeConverter : Temporalio.Converters.ITemporalTransferTypeConverter
        {
            public System.Type TransferType => typeof(Temporalio.Api.WorkflowService.V1.StartWorkflowExecutionResponse);

            public object? ToTransferType(object? value) => value is null ? null : ((StartWorkflowResult)value).ToTransferType();

            public object? FromTransferType(object? transferType) => transferType is null ? null : StartWorkflowResult.FromTransferType((Temporalio.Api.WorkflowService.V1.StartWorkflowExecutionResponse)transferType);
        }

    }

    [Temporalio.Converters.TemporalTransferTypeConverter(typeof(WorkflowExecution.TransferTypeConverter))]
    [GeneratedCode("nexgen", null)]
    public record WorkflowExecution
    {
        public WorkflowExecution(string workflowId)
        {
            WorkflowId = workflowId;
        }

        public string WorkflowId { get; init; }
        public string? RunId { get; init; }

        internal static WorkflowExecution FromTransferType(Temporalio.Api.Common.V1.WorkflowExecution wire)
        {
            return new WorkflowExecution(wire.WorkflowId)
            {
                RunId = string.IsNullOrEmpty(wire.RunId) ? null : wire.RunId,
            };
        }

        internal Temporalio.Api.Common.V1.WorkflowExecution ToTransferType()
        {
            var proto = new Temporalio.Api.Common.V1.WorkflowExecution();
            proto.WorkflowId = WorkflowId;
            if (RunId is { } runId)
            {
                proto.RunId = runId;
            }
            return proto;
        }

        public sealed class TransferTypeConverter : Temporalio.Converters.ITemporalTransferTypeConverter
        {
            public System.Type TransferType => typeof(Temporalio.Api.Common.V1.WorkflowExecution);

            public object? ToTransferType(object? value) => value is null ? null : ((WorkflowExecution)value).ToTransferType();

            public object? FromTransferType(object? transferType) => transferType is null ? null : WorkflowExecution.FromTransferType((Temporalio.Api.Common.V1.WorkflowExecution)transferType);
        }

    }

}
