// <auto-generated />
// Generated by nex-gen. DO NOT EDIT!
#nullable enable
#pragma warning disable CS1591

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using System.Threading.Tasks;
using Google.Protobuf.WellKnownTypes;
using Temporalio.Converters;
using Temporalio.Workflows;

namespace NexGen.StartWorkflowService
{

    [GeneratedCode("nex-gen", null)]
    public class StartWorkflowOptions
    {
        public StartWorkflowOptions(string workflow, string workflowId, string taskQueue)
        {
            Workflow = workflow;
            WorkflowId = workflowId;
            TaskQueue = taskQueue;
        }

        public string Workflow { get; set; }
        public string WorkflowId { get; set; }
        public string TaskQueue { get; set; }
        public System.TimeSpan? WorkflowStartDelay { get; set; }
    }

    [GeneratedCode("nex-gen", null)]
    public class RestartWorkflowOptions
    {
        public RestartWorkflowOptions(string workflow, string workflowId, string taskQueue)
        {
            Workflow = workflow;
            WorkflowId = workflowId;
            TaskQueue = taskQueue;
        }

        public string Workflow { get; set; }
        public string WorkflowId { get; set; }
        public string TaskQueue { get; set; }
        public System.TimeSpan? WorkflowStartDelay { get; set; }
    }

    [GeneratedCode("nex-gen", null)]
    public class CancelWorkflowOptions
    {
        public CancelWorkflowOptions(WorkflowExecution workflowExecution)
        {
            WorkflowExecution = workflowExecution;
        }

        public WorkflowExecution WorkflowExecution { get; set; }
        public string? Reason { get; set; }
    }

    [GeneratedCode("nex-gen", null)]
    public static class Operations
    {
        [GeneratedCode("nex-gen", null)]
        private const string StartWorkflowServiceEndpoint = "temporal-system";

        [GeneratedCode("nex-gen", null)]
        private static async Task<StartedWorkflow> StartWorkflowAsync(StartWorkflowRequest request)
        {
            var client = Workflow.CreateNexusWorkflowClient<IStartWorkflowService>(StartWorkflowServiceEndpoint);
            var result = await client.ExecuteNexusOperationAsync<StartWorkflowResult>(svc => svc.StartWorkflow(request)).ConfigureAwait(true);
            return new StartedWorkflow(request.Namespace, request.WorkflowId, string.IsNullOrEmpty(result.RunId) ? null : result.RunId);
        }

        /// <param name="options">Options for the operation.</param>
        [GeneratedCode("nex-gen", null)]
        public static Task<StartedWorkflow> StartWorkflowAsync(StartWorkflowOptions options)
        {
            var request = new StartWorkflowRequest(options.Workflow, options.WorkflowId, options.TaskQueue)
            {
                WorkflowStartDelay = options.WorkflowStartDelay,
            };
            return StartWorkflowAsync(request);
        }

        [GeneratedCode("nex-gen", null)]
        private static async Task<StartedWorkflow> RestartWorkflowAsync(StartWorkflowRequest request)
        {
            var client = Workflow.CreateNexusWorkflowClient<IStartWorkflowService>(StartWorkflowServiceEndpoint);
            var result = await client.ExecuteNexusOperationAsync<RestartWorkflowResult>(svc => svc.RestartWorkflow(request)).ConfigureAwait(true);
            return new StartedWorkflow(request.Namespace, request.WorkflowId, string.IsNullOrEmpty(result.RunId) ? null : result.RunId);
        }

        /// <param name="options">Options for the operation.</param>
        [GeneratedCode("nex-gen", null)]
        public static Task<StartedWorkflow> RestartWorkflowAsync(RestartWorkflowOptions options)
        {
            var request = new StartWorkflowRequest(options.Workflow, options.WorkflowId, options.TaskQueue)
            {
                WorkflowStartDelay = options.WorkflowStartDelay,
            };
            return RestartWorkflowAsync(request);
        }

        [GeneratedCode("nex-gen", null)]
        private static async Task<CancelWorkflowResponse> CancelWorkflowAsync(CancelWorkflowRequest request)
        {
            var client = Workflow.CreateNexusWorkflowClient<IStartWorkflowService>(StartWorkflowServiceEndpoint);
            var result = await client.ExecuteNexusOperationAsync<CancelWorkflowResponse>(svc => svc.CancelWorkflow(request)).ConfigureAwait(true);
            return result;
        }

        /// <param name="options">Options for the operation.</param>
        [GeneratedCode("nex-gen", null)]
        public static Task<CancelWorkflowResponse> CancelWorkflowAsync(CancelWorkflowOptions options)
        {
            var request = new CancelWorkflowRequest(options.WorkflowExecution)
            {
                Reason = options.Reason,
            };
            return CancelWorkflowAsync(request);
        }

    }

}
