// Code generated by nexus-api-gen. DO NOT EDIT.
package typeshowcase

import (
	"go.temporal.io/sdk/workflow"
)

const ServiceName = "TypeShowcase"
const Endpoint = "type-showcase"

const GetUserOp = "GetUser"
const UpdateEmailOp = "UpdateEmail"
const RenameOp = "Rename"
const SetProfileOp = "SetProfile"
const DeactivateOp = "Deactivate"

type UserStatus int32

const (
	UserStatusActive    UserStatus = 0
	UserStatusSuspended UserStatus = 1
	UserStatusDeleted   UserStatus = 2
)

type UserCapability int32

const (
	UserCapabilityReadProfile UserCapability = 1 << 0
	UserCapabilityUpdateEmail UserCapability = 1 << 1
	UserCapabilityDeactivate  UserCapability = 1 << 2
)

type NotificationTarget interface {
	isNotificationTarget()
}

type NotificationTargetEmail struct {
	Value string
}

func (NotificationTargetEmail) isNotificationTarget() {}

type NotificationTargetSms struct {
	Value string
}

func (NotificationTargetSms) isNotificationTarget() {}

type NotificationTargetNone struct{}

func (NotificationTargetNone) isNotificationTarget() {}

type GetUserRequest struct {
	UserId           string // required
	ConsistencyToken string
}

type UpdateEmailRequest struct {
	UserId string // required
	Email  string // required
}

type RenameRequest struct {
	UserId      string // required
	DisplayName string // required
}

type SetProfileRequest struct {
	UserId  string      // required
	Profile UserProfile // required
}

type UserProfile struct {
	Tags               []string           // required
	Metadata           map[string]string  // required
	Capabilities       UserCapability     // required
	SyncState          any                // required
	NotificationTarget NotificationTarget // required
	Address            *PostalAddress
}

type PostalAddress struct {
	Street      string // required
	City        string // required
	Country     string // required
	Coordinates *Coordinates
}

type Coordinates struct {
	First  float64 // required
	Second float64 // required
}

type DeactivateRequest struct {
	UserId string // required
	Reason string
}

type User struct {
	UserId      string      // required
	Email       string      // required
	DisplayName string      // required
	Status      UserStatus  // required
	Profile     UserProfile // required
}

func getUser(ctx workflow.Context, request GetUserRequest) (*User, error) {
	c := workflow.NewNexusClient(Endpoint, ServiceName)
	fut := c.ExecuteOperation(ctx, GetUserOp, request, workflow.NexusOperationOptions{})
	var result User
	if err := fut.Get(ctx, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func updateEmail(ctx workflow.Context, request UpdateEmailRequest) (*User, error) {
	c := workflow.NewNexusClient(Endpoint, ServiceName)
	fut := c.ExecuteOperation(ctx, UpdateEmailOp, request, workflow.NexusOperationOptions{})
	var result User
	if err := fut.Get(ctx, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func rename(ctx workflow.Context, request RenameRequest) (*User, error) {
	c := workflow.NewNexusClient(Endpoint, ServiceName)
	fut := c.ExecuteOperation(ctx, RenameOp, request, workflow.NexusOperationOptions{})
	var result User
	if err := fut.Get(ctx, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func setProfile(ctx workflow.Context, request SetProfileRequest) (*User, error) {
	c := workflow.NewNexusClient(Endpoint, ServiceName)
	fut := c.ExecuteOperation(ctx, SetProfileOp, request, workflow.NexusOperationOptions{})
	var result User
	if err := fut.Get(ctx, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func deactivate(ctx workflow.Context, request DeactivateRequest) error {
	c := workflow.NewNexusClient(Endpoint, ServiceName)
	fut := c.ExecuteOperation(ctx, DeactivateOp, request, workflow.NexusOperationOptions{})
	return fut.Get(ctx, nil)
}
