# Generated by nex-gen. DO NOT EDIT!

from __future__ import annotations

from . import services as _services
from .operations.activity_options_operation import activity_options_operation

__all__ = [
    "activity_options_operation",
]


__nexus_operation_registry__ = {
    (
        "TypeRoundtripService",
        "ActivityOptionsOperation",
    ): _services.TypeRoundtripService.activity_options_operation,
}
