# Generated by nexgen latest. DO NOT EDIT!

from __future__ import annotations

import dataclasses
import typing
import typing_extensions
import temporalio.converter

from ..._definitions import (
    Violation,
    _member_path,
    _parse_spec_integer,
    _transfer_type_convertible,
)


class _BlockStyleTransferTypeConverter(
    temporalio.converter.TransferTypeConverter["BlockStyle", typing.Any]
):
    @typing_extensions.override
    def from_transfer_type(
        self, value: typing.Any, type_hint: type["BlockStyle"]
    ) -> "BlockStyle":
        violations: list[Violation] = []
        if not isinstance(value, dict):
            raise temporalio.converter.create_payload_validation_error(
                [Violation(path="", reason="expected object")]
            )
        raw = typing.cast("dict[str, typing.Any]", value)

        bold_value: bool | None = None
        if "bold" in raw:
            bold_value_raw = raw["bold"]
            if bold_value_raw is None:
                violations.append(
                    Violation(path="bold", reason="explicit null not allowed")
                )
            else:
                if not isinstance(bold_value_raw, bool):
                    violations.append(Violation(path="bold", reason="expected boolean"))
                else:
                    bold_value = bold_value_raw

        indent_value: int | None = None
        if "indent" in raw:
            indent_value_raw = raw["indent"]
            if indent_value_raw is None:
                violations.append(
                    Violation(path="indent", reason="explicit null not allowed")
                )
            else:
                indent_value_parsed = _parse_spec_integer(
                    indent_value_raw, "indent", violations
                )
                if indent_value_parsed is not None:
                    indent_value = indent_value_parsed
                    if indent_value < 0:
                        violations.append(
                            Violation(
                                path="indent",
                                reason=f"must be >= 0, got {indent_value}",
                            )
                        )

        for key in raw:
            if key != "bold" and key != "indent":
                violations.append(
                    Violation(path=_member_path(key), reason="unknown field")
                )
        if violations:
            raise temporalio.converter.create_payload_validation_error(violations)
        return BlockStyle(
            bold=bold_value,
            indent=indent_value,
        )

    @typing_extensions.override
    def to_transfer_type(self, value: "BlockStyle") -> typing.Any:
        violations: list[Violation] = []
        out: dict[str, typing.Any] = {}
        if value.bold is not None:
            out["bold"] = value.bold
        if value.indent is not None:
            if abs(value.indent) > 9007199254740991:
                violations.append(
                    Violation(path="indent", reason="exceeds ±(2^53-1) integer cap")
                )
            if value.indent < 0:
                violations.append(
                    Violation(path="indent", reason=f"must be >= 0, got {value.indent}")
                )
            out["indent"] = value.indent
        if violations:
            raise temporalio.converter.create_payload_validation_error(violations)
        return out


@_transfer_type_convertible(_BlockStyleTransferTypeConverter)
@dataclasses.dataclass(slots=True, kw_only=True)
class BlockStyle:
    """Non-cyclic helper; stays in the content_block module. All members optional."""

    bold: bool | None = None

    indent: int | None = None
