# Generated by nex-gen. DO NOT EDIT!

from __future__ import annotations

from .services import ChatServiceClient
from . import services as _services

__all__ = [
    "ChatServiceClient",
]


__nexus_operation_registry__ = {
    (
        "example.chat.v1.ChatService",
        "SendMessage",
    ): _services.ChatService.send_message,
    (
        "example.chat.v1.ChatService",
        "GetRoom",
    ): _services.ChatService.get_room,
    (
        "example.chat.v1.ChatService",
        "Ping",
    ): _services.ChatService.ping,
}
