// Generated by nex-gen. DO NOT EDIT!
#nullable enable
#pragma warning disable CS1591

using System;
using System.Collections.Generic;

namespace NexusApiGen.UserService;

public class User
{
    public User(string userId, string email)
    {
        UserId = userId;
        Email = email;
    }

    public string UserId { get; }
    public string Email { get; }

    public User UpdateEmail(string email) => throw new NotSupportedException("Resource methods require a bound Nexus client.");

}

