// <auto-generated />
// Generated by nex-gen. DO NOT EDIT!
#nullable enable
#pragma warning disable CS1591

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace NexGen.UserService
{

    [GeneratedCode("nex-gen", null)]
    public class User
    {
        public User(string userId, string email)
        {
            UserId = userId;
            Email = email;
        }

        public string UserId { get; }
        public string Email { get; }

        [GeneratedCode("nex-gen", null)]
        public Task<User> UpdateEmailAsync(string email)
        {
            var request = new UpdateEmailOptions(UserId, email);
            return Operations.UpdateEmailAsync(request);
        }

    }

}
