// <auto-generated />
// Generated by nex-gen. DO NOT EDIT!
#nullable enable
#pragma warning disable CS1591

using System;
using NexusRpc;

namespace NexGen.UserService
{

    [NexusService("UserService")]
    internal interface IUserService
    {
        [NexusOperation("GetUser")]
        User GetUser(GetUserRequest request);

        [NexusOperation("UpdateEmail")]
        User UpdateEmail(UpdateEmailRequest request);

    }

}
