# Generated by nex-gen. DO NOT EDIT!

from __future__ import annotations

import typing
import pydantic

from ..._json import (
    emit_set_fields,
    reject_explicit_null,
)


class Category(pydantic.BaseModel):
    """A node in a self-recursive category tree. The root of this file is itself a type
    (pure JSON Schema file), named Category from the basename.
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        strict=True, populate_by_name=True, extra="forbid"
    )

    id: str = pydantic.Field()

    name: str = pydantic.Field()

    children: list[Category] | None = pydantic.Field(default=None)
    """Sub-categories. A within-file self-cycle via `$ref: '#'`; the possibly-empty array
    is the terminating edge, so it stays in this module.
    """

    _OPTIONAL_NON_NULLABLE_FIELDS: typing.ClassVar[frozenset[str]] = frozenset(
        {"children"}
    )

    @pydantic.model_validator(mode="wrap")
    @classmethod
    def _reject_null(
        cls,
        data: object,
        handler: typing.Callable[[object], typing.Any],
    ) -> typing.Any:
        return reject_explicit_null(cls, data, handler)

    @pydantic.model_serializer(mode="wrap")
    def _serialize(
        self,
        handler: typing.Callable[[pydantic.BaseModel], typing.Any],
    ) -> dict[str, object]:
        return emit_set_fields(self, handler)


class Palette(pydantic.BaseModel):
    """A dead $def - defined but never referenced anywhere. Still generated and exported as
    intended reusable API surface (see the $ref spec).
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        strict=True, populate_by_name=True, extra="forbid"
    )

    swatches: list[str] = pydantic.Field()

    @pydantic.model_serializer(mode="wrap")
    def _serialize(
        self,
        handler: typing.Callable[[pydantic.BaseModel], typing.Any],
    ) -> dict[str, object]:
        return emit_set_fields(self, handler)


_ = Category.model_rebuild()
