// Generated by nex-gen. DO NOT EDIT!

import * as workflow from "@temporalio/workflow";
import { typeShowcase } from "../services";
import type { UpdateEmailRequest } from "../models";
import "../resources";
import type { User } from "../resources";
import { nexusValue } from "../../nex-gen-runtime";

/**
 * @param request - Request for the operation.
 */
export async function updateEmail(request: UpdateEmailRequest): Promise<User> {
  const client = workflow.createNexusServiceClient({
    service: typeShowcase,
    endpoint: "type-showcase",
  });
  const requestProto = nexusValue("type-showcase.update-email-request", request);
  const handle = await client.startOperation(
    typeShowcase.operations.updateEmail,
    requestProto,
  );
  return await handle.result();
}
