// <auto-generated />
// Generated by nex-gen. DO NOT EDIT!
#nullable enable
#pragma warning disable CS1591

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.RegularExpressions;

namespace NexGen.ShowcaseService
{

    /// <summary>
    /// A nested object, open to forward-compatible extension.
    /// </summary>
    [GeneratedCode("nex-gen", null)]
    public class Address : IJsonOnDeserialized
    {
        public Address(string street)
        {
            Street = street;
        }

        [JsonPropertyName("street")]
        [JsonRequired]
        public string Street { get; init; }
        [JsonIgnore]
        public string? City
        {
            get => JsonRuntime.ReadOptionalValue<string?>(AdditionalProperties, "city");
            init
            {
                JsonRuntime.RejectNull("city", value);
                AdditionalProperties["city"] = value;
            }
        }
        [JsonIgnore]
        public long? Zip
        {
            get => JsonRuntime.ReadOptionalValue<long?>(AdditionalProperties, "zip");
            init
            {
                JsonRuntime.RejectNull("zip", value);
                AdditionalProperties["zip"] = value;
            }
        }

        [JsonExtensionData]
        public Dictionary<string, object?> AdditionalProperties { get; set; } = new Dictionary<string, object?>();

        /// <summary>
        /// Validates every constraint the contract declares on this type, throwing a
        /// single <see cref="ValidationException"/> carrying all violations rather
        /// than stopping at the first.
        /// </summary>
        public void Validate()
        {
            var violations = new List<Violation>();
            CollectViolations(violations, string.Empty);
            if (violations.Count > 0)
            {
                throw new ValidationException(violations);
            }
        }

        internal void CollectViolations(List<Violation> violations, string path)
        {
            if (Zip is long zipValue)
            {
                if (zipValue < -JsonRuntime.IntegerCap || zipValue > JsonRuntime.IntegerCap)
                {
                    violations.Add(new Violation(JsonRuntime.JoinPath(path, "zip"), "exceeds ±(2^53-1) integer cap"));
                }
            }
        }

        void IJsonOnDeserialized.OnDeserialized()
        {
            if (AdditionalProperties.TryGetValue("city", out var cityValue))
            {
                JsonRuntime.RejectNull("city", cityValue);
                if (cityValue is JsonElement json3 && json3.ValueKind != JsonValueKind.String)
                {
                    throw new JsonException($"{"city"}: expected string");
                }
                else if (cityValue is not JsonElement && cityValue is not string)
                {
                    throw new JsonException($"{"city"}: expected string");
                }
            }
            if (AdditionalProperties.TryGetValue("zip", out var zipValue))
            {
                JsonRuntime.RejectNull("zip", zipValue);
                _ = JsonRuntime.ReadJsonValue<long?>(zipValue);
            }
            Validate();
        }
    }


    /// <summary>
    /// A string map with member-count and key-shape constraints: 1 to 3 entries, each key at most 8 code points (minProperties/maxProperties/propertyNames on a map-shaped object).
    /// </summary>
    [GeneratedCode("nex-gen", null)]
    public class Attributes : IJsonOnDeserialized
    {
        [JsonExtensionData]
        public Dictionary<string, object?> AdditionalProperties { get; set; } = new Dictionary<string, object?>();

        /// <summary>
        /// Validates every constraint the contract declares on this type, throwing a
        /// single <see cref="ValidationException"/> carrying all violations rather
        /// than stopping at the first.
        /// </summary>
        public void Validate()
        {
            var violations = new List<Violation>();
            CollectViolations(violations, string.Empty);
            if (violations.Count > 0)
            {
                throw new ValidationException(violations);
            }
        }

        internal void CollectViolations(List<Violation> violations, string path)
        {
            var propertyCount = AdditionalProperties.Count;
            if (propertyCount < 1)
            {
                violations.Add(new Violation(path, "must have at least 1 properties, got " + propertyCount));
            }
            if (propertyCount > 3)
            {
                violations.Add(new Violation(path, "must have at most 3 properties, got " + propertyCount));
            }
            foreach (var propertyName in AdditionalProperties.Keys)
            {
                var nameLength = JsonRuntime.CodePointCount(propertyName);
                if (nameLength > 8)
                {
                    violations.Add(new Violation(JsonRuntime.JoinPath(path, propertyName), $"invalid property name \"{propertyName}\": must have length <= 8, got {nameLength}"));
                }
            }
        }

        void IJsonOnDeserialized.OnDeserialized()
        {
            foreach (var entry in AdditionalProperties)
            {
                if (entry.Value is JsonElement json3 && json3.ValueKind != JsonValueKind.String)
                {
                    throw new JsonException($"{entry.Key}: expected string");
                }
                else if (entry.Value is not JsonElement && entry.Value is not string)
                {
                    throw new JsonException($"{entry.Key}: expected string");
                }
            }
            Validate();
        }
    }


    /// <summary>
    /// A circle branch of the Shape tagged union.
    /// </summary>
    [GeneratedCode("nex-gen", null)]
    public class Circle
    {
        public Circle(double radius)
        {
            Radius = radius;
        }

        private string kindValue = "circle";

        [JsonPropertyName("kind")]
        [JsonRequired]
        public string Kind
        {
            get => kindValue;
            init
            {
                if (value != "circle")
                {
                    throw new JsonException("kind must equal \"circle\"");
                }
                kindValue = value;
            }
        }
        [JsonPropertyName("radius")]
        [JsonRequired]
        public double Radius { get; init; }

        [JsonExtensionData]
        public Dictionary<string, object?> AdditionalProperties { get; set; } = new Dictionary<string, object?>();
    }


    /// <summary>
    /// Contact details with a conditional requirement and a member-count bound: a shipping street requires a shipping zip (dependentRequired), and the object must carry 1 to 3 members (minProperties/maxProperties on a declared-property object). Also exercises the type-level `x-&lt;lang&gt;-name` override (the Stage 4 escape hatch): the emitted type is renamed to the derived name plus a per-language suffix (Go `ContactGo`, TS `ContactTs`, Python `ContactPy`, Java `ContactJava`) at its declaration and at every `$ref`, while the wire `$ref` name stays `Contact`.
    /// </summary>
    [GeneratedCode("nex-gen", null)]
    public class Contact : IJsonOnDeserialized
    {
        [JsonIgnore]
        public string? Email
        {
            get => JsonRuntime.ReadOptionalValue<string?>(AdditionalProperties, "email");
            init
            {
                JsonRuntime.RejectNull("email", value);
                AdditionalProperties["email"] = value;
            }
        }
        [JsonIgnore]
        public string? ShippingStreet
        {
            get => JsonRuntime.ReadOptionalValue<string?>(AdditionalProperties, "shippingStreet");
            init
            {
                JsonRuntime.RejectNull("shippingStreet", value);
                AdditionalProperties["shippingStreet"] = value;
            }
        }
        [JsonIgnore]
        public string? ShippingZip
        {
            get => JsonRuntime.ReadOptionalValue<string?>(AdditionalProperties, "shippingZip");
            init
            {
                JsonRuntime.RejectNull("shippingZip", value);
                AdditionalProperties["shippingZip"] = value;
            }
        }

        [JsonExtensionData]
        public Dictionary<string, object?> AdditionalProperties { get; set; } = new Dictionary<string, object?>();

        /// <summary>
        /// Validates every constraint the contract declares on this type, throwing a
        /// single <see cref="ValidationException"/> carrying all violations rather
        /// than stopping at the first.
        /// </summary>
        public void Validate()
        {
            var violations = new List<Violation>();
            CollectViolations(violations, string.Empty);
            if (violations.Count > 0)
            {
                throw new ValidationException(violations);
            }
        }

        internal void CollectViolations(List<Violation> violations, string path)
        {
            var propertyCount = AdditionalProperties.Count;
            if (propertyCount < 1)
            {
                violations.Add(new Violation(path, "must have at least 1 properties, got " + propertyCount));
            }
            if (propertyCount > 3)
            {
                violations.Add(new Violation(path, "must have at most 3 properties, got " + propertyCount));
            }
            if (AdditionalProperties.ContainsKey("shippingStreet") && !AdditionalProperties.ContainsKey("shippingZip"))
            {
                violations.Add(new Violation(JsonRuntime.JoinPath(path, "shippingZip"), "property \"shippingZip\" is required when \"shippingStreet\" is present"));
            }
        }

        void IJsonOnDeserialized.OnDeserialized()
        {
            if (AdditionalProperties.TryGetValue("email", out var emailValue))
            {
                JsonRuntime.RejectNull("email", emailValue);
                if (emailValue is JsonElement json3 && json3.ValueKind != JsonValueKind.String)
                {
                    throw new JsonException($"{"email"}: expected string");
                }
                else if (emailValue is not JsonElement && emailValue is not string)
                {
                    throw new JsonException($"{"email"}: expected string");
                }
            }
            if (AdditionalProperties.TryGetValue("shippingStreet", out var shippingStreetValue))
            {
                JsonRuntime.RejectNull("shippingStreet", shippingStreetValue);
                if (shippingStreetValue is JsonElement json3 && json3.ValueKind != JsonValueKind.String)
                {
                    throw new JsonException($"{"shippingStreet"}: expected string");
                }
                else if (shippingStreetValue is not JsonElement && shippingStreetValue is not string)
                {
                    throw new JsonException($"{"shippingStreet"}: expected string");
                }
            }
            if (AdditionalProperties.TryGetValue("shippingZip", out var shippingZipValue))
            {
                JsonRuntime.RejectNull("shippingZip", shippingZipValue);
                if (shippingZipValue is JsonElement json3 && json3.ValueKind != JsonValueKind.String)
                {
                    throw new JsonException($"{"shippingZip"}: expected string");
                }
                else if (shippingZipValue is not JsonElement && shippingZipValue is not string)
                {
                    throw new JsonException($"{"shippingZip"}: expected string");
                }
            }
            Validate();
        }
    }


    /// <summary>
    /// Arbitrary string key/value labels (typed map).
    /// </summary>
    [GeneratedCode("nex-gen", null)]
    public class Labels : IJsonOnDeserialized
    {
        [JsonExtensionData]
        public Dictionary<string, object?> AdditionalProperties { get; set; } = new Dictionary<string, object?>();

        /// <summary>
        /// Validates every constraint the contract declares on this type, throwing a
        /// single <see cref="ValidationException"/> carrying all violations rather
        /// than stopping at the first.
        /// </summary>
        public void Validate()
        {
            var violations = new List<Violation>();
            CollectViolations(violations, string.Empty);
            if (violations.Count > 0)
            {
                throw new ValidationException(violations);
            }
        }

        internal void CollectViolations(List<Violation> violations, string path)
        {
            var propertyCount = AdditionalProperties.Count;
            if (propertyCount > 50)
            {
                violations.Add(new Violation(path, "must have at most 50 properties, got " + propertyCount));
            }
        }

        void IJsonOnDeserialized.OnDeserialized()
        {
            foreach (var entry in AdditionalProperties)
            {
                if (entry.Value is JsonElement json3 && json3.ValueKind != JsonValueKind.String)
                {
                    throw new JsonException($"{entry.Key}: expected string");
                }
                else if (entry.Value is not JsonElement && entry.Value is not string)
                {
                    throw new JsonException($"{entry.Key}: expected string");
                }
            }
            Validate();
        }
    }


    /// <summary>
    /// A closed object; unknown members are rejected.
    /// </summary>
    [GeneratedCode("nex-gen", null)]
    public class Settings : IJsonOnDeserialized
    {
        [JsonIgnore]
        public string? Theme
        {
            get => JsonRuntime.ReadOptionalValue<string?>(AdditionalProperties, "theme");
            init
            {
                JsonRuntime.RejectNull("theme", value);
                AdditionalProperties["theme"] = value;
            }
        }
        [JsonIgnore]
        public long? FontSize
        {
            get => JsonRuntime.ReadOptionalValue<long?>(AdditionalProperties, "fontSize");
            init
            {
                JsonRuntime.RejectNull("fontSize", value);
                AdditionalProperties["fontSize"] = value;
            }
        }

        [JsonExtensionData]
        public Dictionary<string, object?> AdditionalProperties { get; set; } = new Dictionary<string, object?>();

        /// <summary>
        /// Validates every constraint the contract declares on this type, throwing a
        /// single <see cref="ValidationException"/> carrying all violations rather
        /// than stopping at the first.
        /// </summary>
        public void Validate()
        {
            var violations = new List<Violation>();
            CollectViolations(violations, string.Empty);
            if (violations.Count > 0)
            {
                throw new ValidationException(violations);
            }
        }

        internal void CollectViolations(List<Violation> violations, string path)
        {
            if (FontSize is long fontSizeValue)
            {
                if (fontSizeValue < -JsonRuntime.IntegerCap || fontSizeValue > JsonRuntime.IntegerCap)
                {
                    violations.Add(new Violation(JsonRuntime.JoinPath(path, "fontSize"), "exceeds ±(2^53-1) integer cap"));
                }
            }
        }

        void IJsonOnDeserialized.OnDeserialized()
        {
            foreach (var key in AdditionalProperties.Keys)
            {
                if (key != "theme" && key != "fontSize")
                {
                    throw new JsonException($"Unknown field `{key}`.");
                }
            }
            if (AdditionalProperties.TryGetValue("theme", out var themeValue))
            {
                JsonRuntime.RejectNull("theme", themeValue);
                if (themeValue is JsonElement json3 && json3.ValueKind != JsonValueKind.String)
                {
                    throw new JsonException($"{"theme"}: expected string");
                }
                else if (themeValue is not JsonElement && themeValue is not string)
                {
                    throw new JsonException($"{"theme"}: expected string");
                }
            }
            if (AdditionalProperties.TryGetValue("fontSize", out var fontSizeValue))
            {
                JsonRuntime.RejectNull("fontSize", fontSizeValue);
                _ = JsonRuntime.ReadJsonValue<long?>(fontSizeValue);
            }
            Validate();
        }
    }


    /// <summary>
    /// A closed sum type (discriminated union) of Circle | Square, tagged by the shared required `kind` const. Selection reads `kind` and routes to the matching branch; an unknown tag is a Violation.
    /// </summary>
    [GeneratedCode("nex-gen", null)]
    public class Shape
    {
        [JsonExtensionData]
        public Dictionary<string, object?> AdditionalProperties { get; set; } = new Dictionary<string, object?>();
    }


    /// <summary>
    /// Root object exercising the supported JSON-Schema feature subset: required and optional fields of every scalar type, optional+nullable and required+nullable members, arrays, a nested object via $ref, a typed-map, a closed object, an open (catch-all) object, a string const, a scalar default, and member docs.
    /// </summary>
    [GeneratedCode("nex-gen", null)]
    public class Showcase : IJsonOnDeserialized
    {
        public Showcase(string status, long tier, double scale, string name, long count, bool active, string? category)
        {
            Status = status;
            Tier = tier;
            Scale = scale;
            Name = name;
            Count = count;
            Active = active;
            Category = category;
        }

        /// <summary>
        /// Discriminator; always "showcase".
        /// </summary>
        private string kindValue = "showcase";

        [JsonPropertyName("kind")]
        [JsonRequired]
        public string Kind
        {
            get => kindValue;
            init
            {
                if (value != "showcase")
                {
                    throw new JsonException("kind must equal \"showcase\"");
                }
                kindValue = value;
            }
        }
        /// <summary>
        /// Integer const; always 1. Also exercises the single-`const` value override: `x-go-const-name`/`x-java-const-name` rename the emitted constant to the derived name plus a per-language suffix (Go `RevisionGo`, Java `REVISION_JAVA`) while the wire value stays `1`. TS/Python are inert here (no const override keyword — the value is emitted as a plain literal type).
        /// </summary>
        private long revisionValue = 1;

        [JsonPropertyName("revision")]
        [JsonRequired]
        public long Revision
        {
            get => revisionValue;
            init
            {
                if (value != 1)
                {
                    throw new JsonException("revision must equal 1");
                }
                revisionValue = value;
            }
        }
        /// <summary>
        /// Boolean const; always true.
        /// </summary>
        private bool enabledValue = true;

        [JsonPropertyName("enabled")]
        [JsonRequired]
        public bool Enabled
        {
            get => enabledValue;
            init
            {
                if (value != true)
                {
                    throw new JsonException("enabled must equal true");
                }
                enabledValue = value;
            }
        }
        /// <summary>
        /// Closed string value set. Also exercises the enum value-constant override: `x-go-enum-names`/`x-java-enum-names` rename the `active` value's emitted constant to the value name plus a per-language suffix (Go `ActiveGo`, Java `ACTIVE_JAVA`) while the wire value stays `active`. TS/Python are inert here (no enum override keyword).
        /// </summary>
        [JsonPropertyName("status")]
        [JsonRequired]
        public string Status { get; init; }
        /// <summary>
        /// Closed integer value set.
        /// </summary>
        [JsonPropertyName("tier")]
        [JsonRequired]
        public long Tier { get; init; }
        /// <summary>
        /// Closed number value set (exercises the Python float exception: emitted as plain float, validated by membership).
        /// </summary>
        [JsonPropertyName("scale")]
        [JsonRequired]
        public double Scale { get; init; }
        /// <summary>
        /// Required human-readable name, 1 to 64 code points.
        /// </summary>
        [JsonPropertyName("name")]
        [JsonRequired]
        public string Name { get; init; }
        /// <summary>
        /// Required integer scalar.
        /// </summary>
        [JsonPropertyName("count")]
        [JsonRequired]
        public long Count { get; init; }
        /// <summary>
        /// Required boolean scalar.
        /// </summary>
        [JsonPropertyName("active")]
        [JsonRequired]
        public bool Active { get; init; }
        /// <summary>
        /// Optional short name, at most 12 code points.
        /// </summary>
        [JsonIgnore]
        public string? Nickname
        {
            get => JsonRuntime.ReadOptionalValue<string?>(AdditionalProperties, "nickname");
            init
            {
                JsonRuntime.RejectNull("nickname", value);
                AdditionalProperties["nickname"] = value;
            }
        }
        /// <summary>
        /// Optional code, 2 to 5 code points. Counted in Unicode code points, so a multi-byte value (e.g. "a😀b", 3 code points / 6 UTF-8 bytes) is valid.
        /// </summary>
        [JsonIgnore]
        public string? Code
        {
            get => JsonRuntime.ReadOptionalValue<string?>(AdditionalProperties, "code");
            init
            {
                JsonRuntime.RejectNull("code", value);
                AdditionalProperties["code"] = value;
            }
        }
        /// <summary>
        /// Optional product code: 2 to 4 uppercase ASCII letters, anchored (`^[A-Z]{2,4}$`). Exercises the RE2-safe `pattern` gate.
        /// </summary>
        [JsonIgnore]
        public string? Sku
        {
            get => JsonRuntime.ReadOptionalValue<string?>(AdditionalProperties, "sku");
            init
            {
                JsonRuntime.RejectNull("sku", value);
                AdditionalProperties["sku"] = value;
            }
        }
        /// <summary>
        /// Optional two-word phrase separated by whitespace (`^\S+\s\S+$`). Exercises the loader's `\s`/`\S` → ASCII-class normalization and the per-target `$` end-anchor rewrite (Python `\Z` / Java `\z`), so a Unicode space (NBSP) and a trailing newline are rejected consistently across all four languages.
        /// </summary>
        [JsonIgnore]
        public string? Phrase
        {
            get => JsonRuntime.ReadOptionalValue<string?>(AdditionalProperties, "phrase");
            init
            {
                JsonRuntime.RejectNull("phrase", value);
                AdditionalProperties["phrase"] = value;
            }
        }
        /// <summary>
        /// Optional request identifier; asserted RFC 4122 UUID via `format: uuid`. Stays `string`-typed (format assertion, no materialization); the pinned regex is validated identically across all four languages.
        /// </summary>
        [JsonIgnore]
        public string? RequestId
        {
            get => JsonRuntime.ReadOptionalValue<string?>(AdditionalProperties, "requestId");
            init
            {
                JsonRuntime.RejectNull("requestId", value);
                AdditionalProperties["requestId"] = value;
            }
        }
        /// <summary>
        /// Optional contact address; asserted ASCII dot-atom `format: email` (single `@`, &gt;=2-label domain, total length &lt;= 254, guard-before-regex).
        /// </summary>
        [JsonIgnore]
        public string? ContactEmail
        {
            get => JsonRuntime.ReadOptionalValue<string?>(AdditionalProperties, "contactEmail");
            init
            {
                JsonRuntime.RejectNull("contactEmail", value);
                AdditionalProperties["contactEmail"] = value;
            }
        }
        /// <summary>
        /// Optional host name; asserted RFC 1123 `format: hostname` (LDH labels, total length &lt;= 253).
        /// </summary>
        [JsonIgnore]
        public string? Host
        {
            get => JsonRuntime.ReadOptionalValue<string?>(AdditionalProperties, "host");
            init
            {
                JsonRuntime.RejectNull("host", value);
                AdditionalProperties["host"] = value;
            }
        }
        /// <summary>
        /// Optional homepage; asserted RFC 3986 `format: uri` (scheme required, ASCII only; an IP-literal host is validated by the spliced ipv6 grammar).
        /// </summary>
        [JsonIgnore]
        public string? Homepage
        {
            get => JsonRuntime.ReadOptionalValue<string?>(AdditionalProperties, "homepage");
            init
            {
                JsonRuntime.RejectNull("homepage", value);
                AdditionalProperties["homepage"] = value;
            }
        }
        /// <summary>
        /// Optional gateway address; asserted dotted-quad IPv4 via format ipv4.
        /// </summary>
        [JsonIgnore]
        public string? Gateway
        {
            get => JsonRuntime.ReadOptionalValue<string?>(AdditionalProperties, "gateway");
            init
            {
                JsonRuntime.RejectNull("gateway", value);
                AdditionalProperties["gateway"] = value;
            }
        }
        /// <summary>
        /// Optional binary payload carried as a `contentEncoding: base64` string, materialized to native bytes (Go []byte, TS Uint8Array, Python bytes, Java byte[]). The wire is canonical padded standard base64; a malformed value is rejected by the pinned regex before decode.
        /// </summary>
        [JsonIgnore]
        public string? Blob
        {
            get => JsonRuntime.ReadOptionalValue<string?>(AdditionalProperties, "blob");
            init
            {
                JsonRuntime.RejectNull("blob", value);
                AdditionalProperties["blob"] = value;
            }
        }
        /// <summary>
        /// Optional binary payload carried as a `contentEncoding: base64url` string (URL-safe alphabet, unpadded, RFC 4648 §5), materialized to the same native bytes type. The same bytes encode to a different wire than base64 ("Pj4+" vs "Pj4-").
        /// </summary>
        [JsonIgnore]
        public string? UrlBlob
        {
            get => JsonRuntime.ReadOptionalValue<string?>(AdditionalProperties, "urlBlob");
            init
            {
                JsonRuntime.RejectNull("urlBlob", value);
                AdditionalProperties["urlBlob"] = value;
            }
        }
        /// <summary>
        /// Optional integer with a schema default.
        /// </summary>
        [JsonIgnore]
        public long? Retries
        {
            get => JsonRuntime.ReadOptionalValue<long?>(AdditionalProperties, "retries", 3);
            init
            {
                JsonRuntime.RejectNull("retries", value);
                AdditionalProperties["retries"] = value;
            }
        }
        [JsonIgnore]
        public bool? Verbose
        {
            get => JsonRuntime.ReadOptionalValue<bool?>(AdditionalProperties, "verbose");
            init
            {
                JsonRuntime.RejectNull("verbose", value);
                AdditionalProperties["verbose"] = value;
            }
        }
        /// <summary>
        /// Optional string with a schema default, surfaced on read.
        /// </summary>
        [JsonIgnore]
        public string? Greeting
        {
            get => JsonRuntime.ReadOptionalValue<string?>(AdditionalProperties, "greeting", "hello");
            init
            {
                JsonRuntime.RejectNull("greeting", value);
                AdditionalProperties["greeting"] = value;
            }
        }
        /// <summary>
        /// Optional boolean with a schema default.
        /// </summary>
        [JsonIgnore]
        public bool? Debug
        {
            get => JsonRuntime.ReadOptionalValue<bool?>(AdditionalProperties, "debug", false);
            init
            {
                JsonRuntime.RejectNull("debug", value);
                AdditionalProperties["debug"] = value;
            }
        }
        /// <summary>
        /// Deprecated legacy identifier; prefer `requestId`. Exercises the native deprecation marker (Go // Deprecated:, TS @deprecated, Java @Deprecated, Python PEP 702 @deprecated). Also exercises the property-level `x-&lt;lang&gt;-name` override (the Stage 4 escape hatch): the emitted member identifier is renamed to the derived name plus a per-language suffix (Go `LegacyIdGo`, TS `legacyIdTs`, Python `legacy_id_py`, Java `legacyIdJava`) while the wire name stays `legacyId` (json tag / alias / @JsonProperty).
        /// </summary>
        [JsonIgnore]
        public string? LegacyId
        {
            get => JsonRuntime.ReadOptionalValue<string?>(AdditionalProperties, "legacyId");
            init
            {
                JsonRuntime.RejectNull("legacyId", value);
                AdditionalProperties["legacyId"] = value;
            }
        }
        /// <summary>
        /// Optional and nullable; may be absent or explicitly null.
        /// </summary>
        [JsonIgnore]
        public string? MiddleName
        {
            get => JsonRuntime.ReadOptionalValue<string?>(AdditionalProperties, "middleName");
            init
            {
                AdditionalProperties["middleName"] = value;
            }
        }
        /// <summary>
        /// Required but nullable; may be explicitly cleared to null.
        /// </summary>
        [JsonPropertyName("category")]
        [JsonRequired]
        public string? Category { get; init; }
        /// <summary>
        /// Optional integer bounded to the inclusive range [1, 10].
        /// </summary>
        [JsonIgnore]
        public long? Priority
        {
            get => JsonRuntime.ReadOptionalValue<long?>(AdditionalProperties, "priority");
            init
            {
                JsonRuntime.RejectNull("priority", value);
                AdditionalProperties["priority"] = value;
            }
        }
        /// <summary>
        /// Optional integer that must be strictly greater than 0.
        /// </summary>
        [JsonIgnore]
        public long? Level
        {
            get => JsonRuntime.ReadOptionalValue<long?>(AdditionalProperties, "level");
            init
            {
                JsonRuntime.RejectNull("level", value);
                AdditionalProperties["level"] = value;
            }
        }
        /// <summary>
        /// Optional number that must be a non-negative multiple of 5.
        /// </summary>
        [JsonIgnore]
        public double? Ratio
        {
            get => JsonRuntime.ReadOptionalValue<double?>(AdditionalProperties, "ratio");
            init
            {
                JsonRuntime.RejectNull("ratio", value);
                AdditionalProperties["ratio"] = value;
            }
        }
        /// <summary>
        /// Optional integer that must be a multiple of 3.
        /// </summary>
        [JsonIgnore]
        public long? Step
        {
            get => JsonRuntime.ReadOptionalValue<long?>(AdditionalProperties, "step");
            init
            {
                JsonRuntime.RejectNull("step", value);
                AdditionalProperties["step"] = value;
            }
        }
        /// <summary>
        /// Ordered list of free-form tags; 1 to 5 entries.
        /// </summary>
        [JsonIgnore]
        public IReadOnlyList<string>? Tags
        {
            get => JsonRuntime.ReadOptionalValue<List<string>?>(AdditionalProperties, "tags");
            init
            {
                JsonRuntime.RejectNull("tags", value);
                AdditionalProperties["tags"] = value;
            }
        }
        /// <summary>
        /// Alternate names; each must be distinct.
        /// </summary>
        [JsonIgnore]
        public IReadOnlyList<string>? Aliases
        {
            get => JsonRuntime.ReadOptionalValue<List<string>?>(AdditionalProperties, "aliases");
            init
            {
                JsonRuntime.RejectNull("aliases", value);
                AdditionalProperties["aliases"] = value;
            }
        }
        /// <summary>
        /// Access roles; must contain between one and two "admin" entries.
        /// </summary>
        [JsonIgnore]
        public IReadOnlyList<string>? Roles
        {
            get => JsonRuntime.ReadOptionalValue<List<string>?>(AdditionalProperties, "roles");
            init
            {
                JsonRuntime.RejectNull("roles", value);
                AdditionalProperties["roles"] = value;
            }
        }
        /// <summary>
        /// Disjoint-kind union (oneOf sum type): the wire value is either a string or an integer, selected by its JSON token. Not a member of a discriminated union — the token itself is the selector.
        /// </summary>
        [JsonIgnore]
        public object? IdOrName
        {
            get => JsonRuntime.ReadOptionalValue<object?>(AdditionalProperties, "idOrName");
            init
            {
                JsonRuntime.RejectNull("idOrName", value);
                AdditionalProperties["idOrName"] = value;
            }
        }
        [JsonIgnore]
        public Shape? Shape
        {
            get => JsonRuntime.ReadOptionalValue<Shape?>(AdditionalProperties, "shape");
            init
            {
                JsonRuntime.RejectNull("shape", value);
                AdditionalProperties["shape"] = value;
            }
        }
        [JsonIgnore]
        public Address? Address
        {
            get => JsonRuntime.ReadOptionalValue<Address?>(AdditionalProperties, "address");
            init
            {
                JsonRuntime.RejectNull("address", value);
                AdditionalProperties["address"] = value;
            }
        }
        [JsonIgnore]
        public Labels? Labels
        {
            get => JsonRuntime.ReadOptionalValue<Labels?>(AdditionalProperties, "labels");
            init
            {
                JsonRuntime.RejectNull("labels", value);
                AdditionalProperties["labels"] = value;
            }
        }
        [JsonIgnore]
        public Settings? Settings
        {
            get => JsonRuntime.ReadOptionalValue<Settings?>(AdditionalProperties, "settings");
            init
            {
                JsonRuntime.RejectNull("settings", value);
                AdditionalProperties["settings"] = value;
            }
        }
        [JsonIgnore]
        public Attributes? Attributes
        {
            get => JsonRuntime.ReadOptionalValue<Attributes?>(AdditionalProperties, "attributes");
            init
            {
                JsonRuntime.RejectNull("attributes", value);
                AdditionalProperties["attributes"] = value;
            }
        }
        [JsonIgnore]
        public Contact? Contact
        {
            get => JsonRuntime.ReadOptionalValue<Contact?>(AdditionalProperties, "contact");
            init
            {
                JsonRuntime.RejectNull("contact", value);
                AdditionalProperties["contact"] = value;
            }
        }

        [JsonExtensionData]
        public Dictionary<string, object?> AdditionalProperties { get; set; } = new Dictionary<string, object?>();

        private static readonly Regex skuPattern = new Regex("^[A-Z]{2,4}\\z", RegexOptions.CultureInvariant);
        private static readonly Regex phrasePattern = new Regex("^[^\\t\\n\\x0B\\f\\r ]+[\\t\\n\\x0B\\f\\r ][^\\t\\n\\x0B\\f\\r ]+\\z", RegexOptions.CultureInvariant);

        /// <summary>
        /// Validates every constraint the contract declares on this type, throwing a
        /// single <see cref="ValidationException"/> carrying all violations rather
        /// than stopping at the first.
        /// </summary>
        public void Validate()
        {
            var violations = new List<Violation>();
            CollectViolations(violations, string.Empty);
            if (violations.Count > 0)
            {
                throw new ValidationException(violations);
            }
        }

        internal void CollectViolations(List<Violation> violations, string path)
        {
            if (Status != "active" && Status != "inactive" && Status != "pending")
            {
                violations.Add(new Violation(JsonRuntime.JoinPath(path, "status"), "must be one of [\"active\",\"inactive\",\"pending\"], got " + JsonRuntime.Quote(Status)));
            }
            if (Tier != 1 && Tier != 2 && Tier != 3)
            {
                violations.Add(new Violation(JsonRuntime.JoinPath(path, "tier"), "must be one of [1,2,3], got " + JsonRuntime.FormatNumber(Tier)));
            }
            if (Scale != 1.5 && Scale != 2.5)
            {
                violations.Add(new Violation(JsonRuntime.JoinPath(path, "scale"), "must be one of [1.5,2.5], got " + JsonRuntime.FormatNumber(Scale)));
            }
            var nameLength = JsonRuntime.CodePointCount(Name);
            if (nameLength < 1)
            {
                violations.Add(new Violation(JsonRuntime.JoinPath(path, "name"), "must have length >= 1, got " + nameLength));
            }
            if (nameLength > 64)
            {
                violations.Add(new Violation(JsonRuntime.JoinPath(path, "name"), "must have length <= 64, got " + nameLength));
            }
            if (Count < -JsonRuntime.IntegerCap || Count > JsonRuntime.IntegerCap)
            {
                violations.Add(new Violation(JsonRuntime.JoinPath(path, "count"), "exceeds ±(2^53-1) integer cap"));
            }
            if (Nickname is string nicknameValue)
            {
                var nicknameLength = JsonRuntime.CodePointCount(nicknameValue);
                if (nicknameLength > 12)
                {
                    violations.Add(new Violation(JsonRuntime.JoinPath(path, "nickname"), "must have length <= 12, got " + nicknameLength));
                }
            }
            if (Code is string codeValue)
            {
                var codeLength = JsonRuntime.CodePointCount(codeValue);
                if (codeLength < 2)
                {
                    violations.Add(new Violation(JsonRuntime.JoinPath(path, "code"), "must have length >= 2, got " + codeLength));
                }
                if (codeLength > 5)
                {
                    violations.Add(new Violation(JsonRuntime.JoinPath(path, "code"), "must have length <= 5, got " + codeLength));
                }
            }
            if (Sku is string skuValue)
            {
                if (!skuPattern.IsMatch(skuValue))
                {
                    violations.Add(new Violation(JsonRuntime.JoinPath(path, "sku"), "must match pattern ^[A-Z]{2,4}\\z, got " + skuValue));
                }
            }
            if (Phrase is string phraseValue)
            {
                if (!phrasePattern.IsMatch(phraseValue))
                {
                    violations.Add(new Violation(JsonRuntime.JoinPath(path, "phrase"), "must match pattern ^[^\\t\\n\\x0B\\f\\r ]+[\\t\\n\\x0B\\f\\r ][^\\t\\n\\x0B\\f\\r ]+\\z, got " + phraseValue));
                }
            }
            if (Retries is long retriesValue)
            {
                if (retriesValue < -JsonRuntime.IntegerCap || retriesValue > JsonRuntime.IntegerCap)
                {
                    violations.Add(new Violation(JsonRuntime.JoinPath(path, "retries"), "exceeds ±(2^53-1) integer cap"));
                }
            }
            if (Priority is long priorityValue)
            {
                if (priorityValue < -JsonRuntime.IntegerCap || priorityValue > JsonRuntime.IntegerCap)
                {
                    violations.Add(new Violation(JsonRuntime.JoinPath(path, "priority"), "exceeds ±(2^53-1) integer cap"));
                }
                if (priorityValue < 1)
                {
                    violations.Add(new Violation(JsonRuntime.JoinPath(path, "priority"), "must be >= 1, got " + JsonRuntime.FormatNumber(priorityValue)));
                }
                if (priorityValue > 10)
                {
                    violations.Add(new Violation(JsonRuntime.JoinPath(path, "priority"), "must be <= 10, got " + JsonRuntime.FormatNumber(priorityValue)));
                }
            }
            if (Level is long levelValue)
            {
                if (levelValue < -JsonRuntime.IntegerCap || levelValue > JsonRuntime.IntegerCap)
                {
                    violations.Add(new Violation(JsonRuntime.JoinPath(path, "level"), "exceeds ±(2^53-1) integer cap"));
                }
                if (levelValue <= 0)
                {
                    violations.Add(new Violation(JsonRuntime.JoinPath(path, "level"), "must be > 0, got " + JsonRuntime.FormatNumber(levelValue)));
                }
            }
            if (Ratio is double ratioValue)
            {
                if (ratioValue < 5)
                {
                    violations.Add(new Violation(JsonRuntime.JoinPath(path, "ratio"), "must be >= 5, got " + JsonRuntime.FormatNumber(ratioValue)));
                }
                if (ratioValue % 5 != 0)
                {
                    violations.Add(new Violation(JsonRuntime.JoinPath(path, "ratio"), "must be a multiple of 5, got " + JsonRuntime.FormatNumber(ratioValue)));
                }
            }
            if (Step is long stepValue)
            {
                if (stepValue < -JsonRuntime.IntegerCap || stepValue > JsonRuntime.IntegerCap)
                {
                    violations.Add(new Violation(JsonRuntime.JoinPath(path, "step"), "exceeds ±(2^53-1) integer cap"));
                }
                if (stepValue % 3 != 0)
                {
                    violations.Add(new Violation(JsonRuntime.JoinPath(path, "step"), "must be a multiple of 3, got " + JsonRuntime.FormatNumber(stepValue)));
                }
            }
            if (Tags is IReadOnlyList<string> tagsValue)
            {
                if (tagsValue.Count < 1)
                {
                    violations.Add(new Violation(JsonRuntime.JoinPath(path, "tags"), "must have at least 1 items, got " + tagsValue.Count));
                }
                if (tagsValue.Count > 5)
                {
                    violations.Add(new Violation(JsonRuntime.JoinPath(path, "tags"), "must have at most 5 items, got " + tagsValue.Count));
                }
            }
            if (Aliases is IReadOnlyList<string> aliasesValue)
            {
                JsonRuntime.CollectDuplicateItems(aliasesValue, JsonRuntime.JoinPath(path, "aliases"), violations);
            }
            if (Roles is IReadOnlyList<string> rolesValue)
            {
                var rolesMatchCount = JsonRuntime.CountMatchingItems(rolesValue, "admin");
                if (rolesMatchCount < 1)
                {
                    violations.Add(new Violation(JsonRuntime.JoinPath(path, "roles"), "too few matching items: at least 1, got " + rolesMatchCount));
                }
                if (rolesMatchCount > 2)
                {
                    violations.Add(new Violation(JsonRuntime.JoinPath(path, "roles"), "too many matching items: at most 2, got " + rolesMatchCount));
                }
            }
        }

        void IJsonOnDeserialized.OnDeserialized()
        {
            foreach (var key in AdditionalProperties.Keys)
            {
                if (key != "nickname" && key != "code" && key != "sku" && key != "phrase" && key != "requestId" && key != "contactEmail" && key != "host" && key != "homepage" && key != "gateway" && key != "blob" && key != "urlBlob" && key != "retries" && key != "verbose" && key != "greeting" && key != "debug" && key != "legacyId" && key != "middleName" && key != "priority" && key != "level" && key != "ratio" && key != "step" && key != "tags" && key != "aliases" && key != "roles" && key != "idOrName" && key != "shape" && key != "address" && key != "labels" && key != "settings" && key != "attributes" && key != "contact")
                {
                    throw new JsonException($"Unknown field `{key}`.");
                }
            }
            if (AdditionalProperties.TryGetValue("nickname", out var nicknameValue))
            {
                JsonRuntime.RejectNull("nickname", nicknameValue);
                if (nicknameValue is JsonElement json3 && json3.ValueKind != JsonValueKind.String)
                {
                    throw new JsonException($"{"nickname"}: expected string");
                }
                else if (nicknameValue is not JsonElement && nicknameValue is not string)
                {
                    throw new JsonException($"{"nickname"}: expected string");
                }
            }
            if (AdditionalProperties.TryGetValue("code", out var codeValue))
            {
                JsonRuntime.RejectNull("code", codeValue);
                if (codeValue is JsonElement json3 && json3.ValueKind != JsonValueKind.String)
                {
                    throw new JsonException($"{"code"}: expected string");
                }
                else if (codeValue is not JsonElement && codeValue is not string)
                {
                    throw new JsonException($"{"code"}: expected string");
                }
            }
            if (AdditionalProperties.TryGetValue("sku", out var skuValue))
            {
                JsonRuntime.RejectNull("sku", skuValue);
                if (skuValue is JsonElement json3 && json3.ValueKind != JsonValueKind.String)
                {
                    throw new JsonException($"{"sku"}: expected string");
                }
                else if (skuValue is not JsonElement && skuValue is not string)
                {
                    throw new JsonException($"{"sku"}: expected string");
                }
            }
            if (AdditionalProperties.TryGetValue("phrase", out var phraseValue))
            {
                JsonRuntime.RejectNull("phrase", phraseValue);
                if (phraseValue is JsonElement json3 && json3.ValueKind != JsonValueKind.String)
                {
                    throw new JsonException($"{"phrase"}: expected string");
                }
                else if (phraseValue is not JsonElement && phraseValue is not string)
                {
                    throw new JsonException($"{"phrase"}: expected string");
                }
            }
            if (AdditionalProperties.TryGetValue("requestId", out var requestIdValue))
            {
                JsonRuntime.RejectNull("requestId", requestIdValue);
                if (requestIdValue is JsonElement json3 && json3.ValueKind != JsonValueKind.String)
                {
                    throw new JsonException($"{"requestId"}: expected string");
                }
                else if (requestIdValue is not JsonElement && requestIdValue is not string)
                {
                    throw new JsonException($"{"requestId"}: expected string");
                }
            }
            if (AdditionalProperties.TryGetValue("contactEmail", out var contactEmailValue))
            {
                JsonRuntime.RejectNull("contactEmail", contactEmailValue);
                if (contactEmailValue is JsonElement json3 && json3.ValueKind != JsonValueKind.String)
                {
                    throw new JsonException($"{"contactEmail"}: expected string");
                }
                else if (contactEmailValue is not JsonElement && contactEmailValue is not string)
                {
                    throw new JsonException($"{"contactEmail"}: expected string");
                }
            }
            if (AdditionalProperties.TryGetValue("host", out var hostValue))
            {
                JsonRuntime.RejectNull("host", hostValue);
                if (hostValue is JsonElement json3 && json3.ValueKind != JsonValueKind.String)
                {
                    throw new JsonException($"{"host"}: expected string");
                }
                else if (hostValue is not JsonElement && hostValue is not string)
                {
                    throw new JsonException($"{"host"}: expected string");
                }
            }
            if (AdditionalProperties.TryGetValue("homepage", out var homepageValue))
            {
                JsonRuntime.RejectNull("homepage", homepageValue);
                if (homepageValue is JsonElement json3 && json3.ValueKind != JsonValueKind.String)
                {
                    throw new JsonException($"{"homepage"}: expected string");
                }
                else if (homepageValue is not JsonElement && homepageValue is not string)
                {
                    throw new JsonException($"{"homepage"}: expected string");
                }
            }
            if (AdditionalProperties.TryGetValue("gateway", out var gatewayValue))
            {
                JsonRuntime.RejectNull("gateway", gatewayValue);
                if (gatewayValue is JsonElement json3 && json3.ValueKind != JsonValueKind.String)
                {
                    throw new JsonException($"{"gateway"}: expected string");
                }
                else if (gatewayValue is not JsonElement && gatewayValue is not string)
                {
                    throw new JsonException($"{"gateway"}: expected string");
                }
            }
            if (AdditionalProperties.TryGetValue("blob", out var blobValue))
            {
                JsonRuntime.RejectNull("blob", blobValue);
                if (blobValue is JsonElement json3 && json3.ValueKind != JsonValueKind.String)
                {
                    throw new JsonException($"{"blob"}: expected string");
                }
                else if (blobValue is not JsonElement && blobValue is not string)
                {
                    throw new JsonException($"{"blob"}: expected string");
                }
            }
            if (AdditionalProperties.TryGetValue("urlBlob", out var urlBlobValue))
            {
                JsonRuntime.RejectNull("urlBlob", urlBlobValue);
                if (urlBlobValue is JsonElement json3 && json3.ValueKind != JsonValueKind.String)
                {
                    throw new JsonException($"{"urlBlob"}: expected string");
                }
                else if (urlBlobValue is not JsonElement && urlBlobValue is not string)
                {
                    throw new JsonException($"{"urlBlob"}: expected string");
                }
            }
            if (AdditionalProperties.TryGetValue("retries", out var retriesValue))
            {
                JsonRuntime.RejectNull("retries", retriesValue);
                _ = JsonRuntime.ReadJsonValue<long?>(retriesValue);
            }
            if (AdditionalProperties.TryGetValue("verbose", out var verboseValue))
            {
                JsonRuntime.RejectNull("verbose", verboseValue);
            }
            if (AdditionalProperties.TryGetValue("greeting", out var greetingValue))
            {
                JsonRuntime.RejectNull("greeting", greetingValue);
                if (greetingValue is JsonElement json3 && json3.ValueKind != JsonValueKind.String)
                {
                    throw new JsonException($"{"greeting"}: expected string");
                }
                else if (greetingValue is not JsonElement && greetingValue is not string)
                {
                    throw new JsonException($"{"greeting"}: expected string");
                }
            }
            if (AdditionalProperties.TryGetValue("debug", out var debugValue))
            {
                JsonRuntime.RejectNull("debug", debugValue);
            }
            if (AdditionalProperties.TryGetValue("legacyId", out var legacyIdValue))
            {
                JsonRuntime.RejectNull("legacyId", legacyIdValue);
                if (legacyIdValue is JsonElement json3 && json3.ValueKind != JsonValueKind.String)
                {
                    throw new JsonException($"{"legacyId"}: expected string");
                }
                else if (legacyIdValue is not JsonElement && legacyIdValue is not string)
                {
                    throw new JsonException($"{"legacyId"}: expected string");
                }
            }
            if (AdditionalProperties.TryGetValue("middleName", out var middleNameValue))
            {
            }
            if (AdditionalProperties.TryGetValue("priority", out var priorityValue))
            {
                JsonRuntime.RejectNull("priority", priorityValue);
                _ = JsonRuntime.ReadJsonValue<long?>(priorityValue);
            }
            if (AdditionalProperties.TryGetValue("level", out var levelValue))
            {
                JsonRuntime.RejectNull("level", levelValue);
                _ = JsonRuntime.ReadJsonValue<long?>(levelValue);
            }
            if (AdditionalProperties.TryGetValue("ratio", out var ratioValue))
            {
                JsonRuntime.RejectNull("ratio", ratioValue);
            }
            if (AdditionalProperties.TryGetValue("step", out var stepValue))
            {
                JsonRuntime.RejectNull("step", stepValue);
                _ = JsonRuntime.ReadJsonValue<long?>(stepValue);
            }
            if (AdditionalProperties.TryGetValue("tags", out var tagsValue))
            {
                JsonRuntime.RejectNull("tags", tagsValue);
                _ = JsonRuntime.ReadJsonValue<List<string>?>(tagsValue);
            }
            if (AdditionalProperties.TryGetValue("aliases", out var aliasesValue))
            {
                JsonRuntime.RejectNull("aliases", aliasesValue);
                _ = JsonRuntime.ReadJsonValue<List<string>?>(aliasesValue);
            }
            if (AdditionalProperties.TryGetValue("roles", out var rolesValue))
            {
                JsonRuntime.RejectNull("roles", rolesValue);
                _ = JsonRuntime.ReadJsonValue<List<string>?>(rolesValue);
            }
            if (AdditionalProperties.TryGetValue("idOrName", out var idOrNameValue))
            {
                JsonRuntime.RejectNull("idOrName", idOrNameValue);
            }
            if (AdditionalProperties.TryGetValue("shape", out var shapeValue))
            {
                JsonRuntime.RejectNull("shape", shapeValue);
                _ = JsonRuntime.ReadJsonValue<Shape?>(shapeValue);
            }
            if (AdditionalProperties.TryGetValue("address", out var addressValue))
            {
                JsonRuntime.RejectNull("address", addressValue);
                _ = JsonRuntime.ReadJsonValue<Address?>(addressValue);
            }
            if (AdditionalProperties.TryGetValue("labels", out var labelsValue))
            {
                JsonRuntime.RejectNull("labels", labelsValue);
                _ = JsonRuntime.ReadJsonValue<Labels?>(labelsValue);
            }
            if (AdditionalProperties.TryGetValue("settings", out var settingsValue))
            {
                JsonRuntime.RejectNull("settings", settingsValue);
                _ = JsonRuntime.ReadJsonValue<Settings?>(settingsValue);
            }
            if (AdditionalProperties.TryGetValue("attributes", out var attributesValue))
            {
                JsonRuntime.RejectNull("attributes", attributesValue);
                _ = JsonRuntime.ReadJsonValue<Attributes?>(attributesValue);
            }
            if (AdditionalProperties.TryGetValue("contact", out var contactValue))
            {
                JsonRuntime.RejectNull("contact", contactValue);
                _ = JsonRuntime.ReadJsonValue<Contact?>(contactValue);
            }
            Validate();
        }
    }


    [JsonUnmappedMemberHandling(JsonUnmappedMemberHandling.Disallow)]
    [GeneratedCode("nex-gen", null)]
    public class GetShowcaseInput
    {
        public GetShowcaseInput(string id)
        {
            Id = id;
        }

        [JsonPropertyName("id")]
        [JsonRequired]
        public string Id { get; init; }
    }


    /// <summary>
    /// A square branch of the Shape tagged union.
    /// </summary>
    [GeneratedCode("nex-gen", null)]
    public class Square
    {
        public Square(double side)
        {
            Side = side;
        }

        private string kindValue = "square";

        [JsonPropertyName("kind")]
        [JsonRequired]
        public string Kind
        {
            get => kindValue;
            init
            {
                if (value != "square")
                {
                    throw new JsonException("kind must equal \"square\"");
                }
                kindValue = value;
            }
        }
        [JsonPropertyName("side")]
        [JsonRequired]
        public double Side { get; init; }

        [JsonExtensionData]
        public Dictionary<string, object?> AdditionalProperties { get; set; } = new Dictionary<string, object?>();
    }


    /// <summary>
    /// Base-type extension via allOf: WidgetBase is flattened in and the extension branch adds fields, so Widget merges to one standalone object with the union of properties ({id, kind, name, size}) and required ([id, name]). The `size` member is itself an allOf that tightens two numeric bounds to a single interval [10, 20]; a value outside it is rejected by the merged constraint. No allOf survives past the loader.
    /// </summary>
    [GeneratedCode("nex-gen", null)]
    public class Widget : IJsonOnDeserialized
    {
        public Widget(string id, string name)
        {
            Id = id;
            Name = name;
        }

        [JsonPropertyName("id")]
        [JsonRequired]
        public string Id { get; init; }
        [JsonIgnore]
        public string? Kind
        {
            get => JsonRuntime.ReadOptionalValue<string?>(AdditionalProperties, "kind");
            init
            {
                JsonRuntime.RejectNull("kind", value);
                AdditionalProperties["kind"] = value;
            }
        }
        [JsonPropertyName("name")]
        [JsonRequired]
        public string Name { get; init; }
        /// <summary>
        /// Optional integer with two allOf branches tightened to [10, 20].
        /// </summary>
        [JsonIgnore]
        public long? Size
        {
            get => JsonRuntime.ReadOptionalValue<long?>(AdditionalProperties, "size");
            init
            {
                JsonRuntime.RejectNull("size", value);
                AdditionalProperties["size"] = value;
            }
        }

        [JsonExtensionData]
        public Dictionary<string, object?> AdditionalProperties { get; set; } = new Dictionary<string, object?>();

        /// <summary>
        /// Validates every constraint the contract declares on this type, throwing a
        /// single <see cref="ValidationException"/> carrying all violations rather
        /// than stopping at the first.
        /// </summary>
        public void Validate()
        {
            var violations = new List<Violation>();
            CollectViolations(violations, string.Empty);
            if (violations.Count > 0)
            {
                throw new ValidationException(violations);
            }
        }

        internal void CollectViolations(List<Violation> violations, string path)
        {
            if (Size is long sizeValue)
            {
                if (sizeValue < -JsonRuntime.IntegerCap || sizeValue > JsonRuntime.IntegerCap)
                {
                    violations.Add(new Violation(JsonRuntime.JoinPath(path, "size"), "exceeds ±(2^53-1) integer cap"));
                }
                if (sizeValue < 10)
                {
                    violations.Add(new Violation(JsonRuntime.JoinPath(path, "size"), "must be >= 10, got " + JsonRuntime.FormatNumber(sizeValue)));
                }
                if (sizeValue > 20)
                {
                    violations.Add(new Violation(JsonRuntime.JoinPath(path, "size"), "must be <= 20, got " + JsonRuntime.FormatNumber(sizeValue)));
                }
            }
        }

        void IJsonOnDeserialized.OnDeserialized()
        {
            if (AdditionalProperties.TryGetValue("kind", out var kindValue))
            {
                JsonRuntime.RejectNull("kind", kindValue);
                if (kindValue is JsonElement json3 && json3.ValueKind != JsonValueKind.String)
                {
                    throw new JsonException($"{"kind"}: expected string");
                }
                else if (kindValue is not JsonElement && kindValue is not string)
                {
                    throw new JsonException($"{"kind"}: expected string");
                }
            }
            if (AdditionalProperties.TryGetValue("size", out var sizeValue))
            {
                JsonRuntime.RejectNull("size", sizeValue);
                _ = JsonRuntime.ReadJsonValue<long?>(sizeValue);
            }
            Validate();
        }
    }


    /// <summary>
    /// A base object folded into Widget via allOf. It stays its own type; Widget copies its fields rather than referencing or subtyping it.
    /// </summary>
    [GeneratedCode("nex-gen", null)]
    public class WidgetBase : IJsonOnDeserialized
    {
        public WidgetBase(string id)
        {
            Id = id;
        }

        [JsonPropertyName("id")]
        [JsonRequired]
        public string Id { get; init; }
        [JsonIgnore]
        public string? Kind
        {
            get => JsonRuntime.ReadOptionalValue<string?>(AdditionalProperties, "kind");
            init
            {
                JsonRuntime.RejectNull("kind", value);
                AdditionalProperties["kind"] = value;
            }
        }

        [JsonExtensionData]
        public Dictionary<string, object?> AdditionalProperties { get; set; } = new Dictionary<string, object?>();

        void IJsonOnDeserialized.OnDeserialized()
        {
            if (AdditionalProperties.TryGetValue("kind", out var kindValue))
            {
                JsonRuntime.RejectNull("kind", kindValue);
                if (kindValue is JsonElement json3 && json3.ValueKind != JsonValueKind.String)
                {
                    throw new JsonException($"{"kind"}: expected string");
                }
                else if (kindValue is not JsonElement && kindValue is not string)
                {
                    throw new JsonException($"{"kind"}: expected string");
                }
            }
        }
    }

}
