// Code generated by nex-gen. DO NOT EDIT.
package functionexecution

import (
	"go.temporal.io/sdk/workflow"
)

const ServiceName = "FunctionExecution"
const Endpoint = "function-execution"

const ExecuteFunctionOp = "ExecuteFunction"
const ExecuteCountedFunctionOp = "ExecuteCountedFunction"
const ExecuteNamedFunctionOp = "ExecuteNamedFunction"
const ExecuteVarargsFunctionOp = "ExecuteVarargsFunction"
const ExecuteNamedVarargsFunctionOp = "ExecuteNamedVarargsFunction"

// --- Datatypes ---

type ExecuteFunctionRequest struct {
	// Required.
	Function string
	// Required. The name argument for the function.
	Name string
	// Required. The enabled argument for the function.
	Enabled bool
}

type ExecuteFunctionResult struct {
	// Required.
	Value string
}

type ExecuteCountedFunctionRequest struct {
	// Required.
	Function string
	// Required. The name argument for the function.
	Name string
	// Required. The count argument for the function.
	Count int32
}

type ExecuteCountedFunctionResult struct {
	// Required.
	Value string
}

type ExecuteNamedFunctionRequest struct {
	// Required.
	Function string
	// Required. The name argument for the function.
	Name string
	// Required. The enabled argument for the function.
	Enabled bool
}

type ExecuteNamedFunctionResult struct {
	// Required.
	Value string
}

type ExecuteVarargsFunctionRequest struct {
	// Required.
	Function string
	// Arguments for the function.
	Args []string
}

type ExecuteVarargsFunctionResult struct {
	// Required.
	Value string
}

type ExecuteNamedVarargsFunctionRequest struct {
	// Required.
	Function string
	// Arguments for the function.
	Args []string
}

type ExecuteNamedVarargsFunctionResult struct {
	// Required.
	Value string
}

// --- Operations (internal) ---

func executeFunction(ctx workflow.Context, request ExecuteFunctionRequest) (*ExecuteFunctionResult, error) {
	c := workflow.NewNexusClient(Endpoint, ServiceName)
	fut := c.ExecuteOperation(ctx, ExecuteFunctionOp, request, workflow.NexusOperationOptions{})
	var result ExecuteFunctionResult
	if err := fut.Get(ctx, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func executeCountedFunction(ctx workflow.Context, request ExecuteCountedFunctionRequest) (*ExecuteCountedFunctionResult, error) {
	c := workflow.NewNexusClient(Endpoint, ServiceName)
	fut := c.ExecuteOperation(ctx, ExecuteCountedFunctionOp, request, workflow.NexusOperationOptions{})
	var result ExecuteCountedFunctionResult
	if err := fut.Get(ctx, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func executeNamedFunction(ctx workflow.Context, request ExecuteNamedFunctionRequest) (*ExecuteNamedFunctionResult, error) {
	c := workflow.NewNexusClient(Endpoint, ServiceName)
	fut := c.ExecuteOperation(ctx, ExecuteNamedFunctionOp, request, workflow.NexusOperationOptions{})
	var result ExecuteNamedFunctionResult
	if err := fut.Get(ctx, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func executeVarargsFunction(ctx workflow.Context, request ExecuteVarargsFunctionRequest) (*ExecuteVarargsFunctionResult, error) {
	c := workflow.NewNexusClient(Endpoint, ServiceName)
	fut := c.ExecuteOperation(ctx, ExecuteVarargsFunctionOp, request, workflow.NexusOperationOptions{})
	var result ExecuteVarargsFunctionResult
	if err := fut.Get(ctx, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func executeNamedVarargsFunction(ctx workflow.Context, request ExecuteNamedVarargsFunctionRequest) (*ExecuteNamedVarargsFunctionResult, error) {
	c := workflow.NewNexusClient(Endpoint, ServiceName)
	fut := c.ExecuteOperation(ctx, ExecuteNamedVarargsFunctionOp, request, workflow.NexusOperationOptions{})
	var result ExecuteNamedVarargsFunctionResult
	if err := fut.Get(ctx, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// --- Operations (public API) ---

func ExecuteFunction(
	ctx workflow.Context,
	function string,
	name string,
	enabled bool,
) (*ExecuteFunctionResult, error) {
	return executeFunction(ctx, ExecuteFunctionRequest{
		Function: function,
		Name:     name,
		Enabled:  enabled,
	})
}

func ExecuteCountedFunction(
	ctx workflow.Context,
	function string,
	name string,
	count int32,
) (*ExecuteCountedFunctionResult, error) {
	return executeCountedFunction(ctx, ExecuteCountedFunctionRequest{
		Function: function,
		Name:     name,
		Count:    count,
	})
}

func ExecuteNamedFunction(
	ctx workflow.Context,
	function string,
	name string,
	enabled bool,
) (*ExecuteNamedFunctionResult, error) {
	return executeNamedFunction(ctx, ExecuteNamedFunctionRequest{
		Function: function,
		Name:     name,
		Enabled:  enabled,
	})
}

type ExecuteVarargsFunctionOptions struct {
	// Arguments for the function.
	Args []string
}

func ExecuteVarargsFunction(ctx workflow.Context, function string, opts ExecuteVarargsFunctionOptions) (*ExecuteVarargsFunctionResult, error) {
	return executeVarargsFunction(ctx, ExecuteVarargsFunctionRequest{
		Function: function,
		Args:     opts.Args,
	})
}

type ExecuteNamedVarargsFunctionOptions struct {
	// Arguments for the function.
	Args []string
}

func ExecuteNamedVarargsFunction(ctx workflow.Context, function string, opts ExecuteNamedVarargsFunctionOptions) (*ExecuteNamedVarargsFunctionResult, error) {
	return executeNamedVarargsFunction(ctx, ExecuteNamedVarargsFunctionRequest{
		Function: function,
		Args:     opts.Args,
	})
}
