// Code generated by nexgen v0.2.2. DO NOT EDIT.
package userservice

import (
	"go.temporal.io/sdk/workflow"
)

// --- Datatypes ---

type getUserRequest struct {
	UserId string
}

type updateEmailRequest struct {
	UserId string
	Email  string
}

// --- Resources ---

type User struct {
	// Required.
	UserId string
	// Required.
	Email string
}

func NewUser(userId string, email string) *User {
	return &User{
		UserId: userId,
		Email:  email,
	}
}

func (u *User) UpdateEmail(ctx workflow.Context, email string) workflow.Future {
	return updateEmail(ctx, updateEmailRequest{UserId: u.UserId, Email: email})
}

// --- Operations (internal) ---

func getUser(ctx workflow.Context, request getUserRequest) workflow.Future {
	c := workflow.NewNexusClient("user-service", "UserService")
	fut := c.ExecuteOperation(ctx, "GetUser", request, workflow.NexusOperationOptions{})
	return fut
}

func updateEmail(ctx workflow.Context, request updateEmailRequest) workflow.Future {
	c := workflow.NewNexusClient("user-service", "UserService")
	fut := c.ExecuteOperation(ctx, "UpdateEmail", request, workflow.NexusOperationOptions{})
	return fut
}

// --- Operations (public API) ---

type GetUserOptions struct {
	// Required.
	UserId string
}

func GetUser(ctx workflow.Context, opts GetUserOptions) workflow.Future {
	return getUser(ctx, getUserRequest{
		UserId: opts.UserId,
	})
}

type UpdateEmailOptions struct {
	// Required.
	UserId string
	// Required.
	Email string
}

func UpdateEmail(ctx workflow.Context, opts UpdateEmailOptions) workflow.Future {
	return updateEmail(ctx, updateEmailRequest{
		UserId: opts.UserId,
		Email:  opts.Email,
	})
}
