// Code generated by nex-gen. DO NOT EDIT.
package content

import (
	"encoding/json"

	nexgenjson "examples/go/json_schema/definitions/kb"
)

// A content block. The other half of the Page <-> Block cross-file cycle. The `page` back-reference is optional + nullable, which terminates the cycle so it is satisfiable.
type Block struct {
	BlockId string `json:"blockId"`
	// Non-negative position within the page. Exercises a numeric `minimum` bound over an integer field.
	Order int64       `json:"order"`
	Text  *string     `json:"text,omitempty"`
	Style *BlockStyle `json:"style,omitempty"`
	// Optional back-reference to the containing page - closes the Page <-> Block cycle. Optional + nullable, so this edge terminates.
	Page *Page `json:"page,omitempty"`
}

func (m Block) Validate() error {
	var errs []nexgenjson.Violation
	if m.Order < -nexgenjson.IntegerCap || m.Order > nexgenjson.IntegerCap {
		errs = append(errs, nexgenjson.Violation{"order", "exceeds ±(2^53-1) integer cap"})
	}
	if m.Style != nil {
		nexgenjson.MergeNested(&errs, "style", m.Style.Validate())
	}
	if len(errs) > 0 {
		return &nexgenjson.ValidationError{Violations: errs}
	}
	return nil
}

func (m *Block) UnmarshalJSON(data []byte) error {
	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	var errs []nexgenjson.Violation
	for k := range all {
		switch k {
		case "blockId", "order", "text", "style", "page":
		default:
			errs = append(errs, nexgenjson.Violation{k, "unknown field"})
		}
	}
	get := func(k string) *json.RawMessage {
		if v, ok := all[k]; ok {
			return &v
		}
		return nil
	}
	_ = get
	if v, ok := nexgenjson.ParseStringField(get("blockId"), "blockId", true, false, &errs); ok {
		m.BlockId = v
	}
	if v, ok := nexgenjson.ParseIntegerField(get("order"), "order", true, false, &errs); ok {
		m.Order = v
	}
	if v, ok := nexgenjson.ParseStringField(get("text"), "text", false, false, &errs); ok {
		m.Text = &v
	}
	if raw := get("style"); raw == nil {
	} else if nexgenjson.IsNull(*raw) {
		errs = append(errs, nexgenjson.Violation{"style", "explicit null not allowed"})
	} else {
		var tmp BlockStyle
		if err := json.Unmarshal(*raw, &tmp); err != nil {
			nexgenjson.MergeNested(&errs, "style", err)
		} else {
			m.Style = &tmp
		}
	}
	if raw := get("page"); raw == nil {
	} else if nexgenjson.IsNull(*raw) {
	} else {
		var tmp Page
		if err := json.Unmarshal(*raw, &tmp); err != nil {
			nexgenjson.MergeNested(&errs, "page", err)
		} else {
			m.Page = &tmp
		}
	}
	if len(errs) > 0 {
		return &nexgenjson.ValidationError{Violations: errs}
	}
	return nil
}

func (m Block) MarshalJSON() ([]byte, error) {
	var errs []nexgenjson.Violation
	nexgenjson.AddViolations(&errs, m.Validate())
	out := map[string]json.RawMessage{}
	nexgenjson.MarshalField(out, "blockId", m.BlockId, &errs)
	nexgenjson.MarshalField(out, "order", m.Order, &errs)
	if m.Text != nil {
		nexgenjson.MarshalField(out, "text", *m.Text, &errs)
	}
	if m.Style != nil {
		nexgenjson.MarshalField(out, "style", *m.Style, &errs)
	}
	if m.Page != nil {
		nexgenjson.MarshalField(out, "page", *m.Page, &errs)
	}
	if len(errs) > 0 {
		return nil, &nexgenjson.ValidationError{Violations: errs}
	}
	return json.Marshal(out)
}

// Non-cyclic helper; stays in the content_block module. All members optional.
type BlockStyle struct {
	Bold   *bool  `json:"bold,omitempty"`
	Indent *int64 `json:"indent,omitempty"`
}

func (m BlockStyle) Validate() error {
	var errs []nexgenjson.Violation
	if m.Indent != nil && (*m.Indent < -nexgenjson.IntegerCap || *m.Indent > nexgenjson.IntegerCap) {
		errs = append(errs, nexgenjson.Violation{"indent", "exceeds ±(2^53-1) integer cap"})
	}
	if len(errs) > 0 {
		return &nexgenjson.ValidationError{Violations: errs}
	}
	return nil
}

func (m *BlockStyle) UnmarshalJSON(data []byte) error {
	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	var errs []nexgenjson.Violation
	for k := range all {
		switch k {
		case "bold", "indent":
		default:
			errs = append(errs, nexgenjson.Violation{k, "unknown field"})
		}
	}
	get := func(k string) *json.RawMessage {
		if v, ok := all[k]; ok {
			return &v
		}
		return nil
	}
	_ = get
	if v, ok := nexgenjson.ParseBoolField(get("bold"), "bold", false, false, &errs); ok {
		m.Bold = &v
	}
	if v, ok := nexgenjson.ParseIntegerField(get("indent"), "indent", false, false, &errs); ok {
		m.Indent = &v
	}
	if len(errs) > 0 {
		return &nexgenjson.ValidationError{Violations: errs}
	}
	return nil
}

func (m BlockStyle) MarshalJSON() ([]byte, error) {
	var errs []nexgenjson.Violation
	nexgenjson.AddViolations(&errs, m.Validate())
	out := map[string]json.RawMessage{}
	if m.Bold != nil {
		nexgenjson.MarshalField(out, "bold", *m.Bold, &errs)
	}
	if m.Indent != nil {
		nexgenjson.MarshalField(out, "indent", *m.Indent, &errs)
	}
	if len(errs) > 0 {
		return nil, &nexgenjson.ValidationError{Violations: errs}
	}
	return json.Marshal(out)
}

// A page. One half of the Page <-> Block cross-file cycle. Because the cycle spans two input files, Page and Block hoist together into Python's _recursive.py; the non-cyclic PageMeta helper stays in this module.
type Page struct {
	PageId string   `json:"pageId"`
	Title  string   `json:"title"`
	Meta   PageMeta `json:"meta"`
	// Ordered content blocks. Cross-file `$ref` to block.json (same directory); the array is the terminating edge of the cycle.
	Blocks []Block `json:"blocks,omitempty"`
}

func (m Page) Validate() error {
	var errs []nexgenjson.Violation
	nexgenjson.MergeNested(&errs, "meta", m.Meta.Validate())
	if len(errs) > 0 {
		return &nexgenjson.ValidationError{Violations: errs}
	}
	return nil
}

func (m *Page) UnmarshalJSON(data []byte) error {
	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	var errs []nexgenjson.Violation
	for k := range all {
		switch k {
		case "pageId", "title", "meta", "blocks":
		default:
			errs = append(errs, nexgenjson.Violation{k, "unknown field"})
		}
	}
	get := func(k string) *json.RawMessage {
		if v, ok := all[k]; ok {
			return &v
		}
		return nil
	}
	_ = get
	if v, ok := nexgenjson.ParseStringField(get("pageId"), "pageId", true, false, &errs); ok {
		m.PageId = v
	}
	if v, ok := nexgenjson.ParseStringField(get("title"), "title", true, false, &errs); ok {
		m.Title = v
	}
	if raw := get("meta"); raw == nil {
		errs = append(errs, nexgenjson.Violation{"meta", "required"})
	} else if nexgenjson.IsNull(*raw) {
		errs = append(errs, nexgenjson.Violation{"meta", "explicit null not allowed"})
	} else {
		nexgenjson.MergeNested(&errs, "meta", json.Unmarshal(*raw, &m.Meta))
	}
	if raw := get("blocks"); raw == nil {
	} else if nexgenjson.IsNull(*raw) {
		errs = append(errs, nexgenjson.Violation{"blocks", "explicit null not allowed"})
	} else if err := json.Unmarshal(*raw, &m.Blocks); err != nil {
		errs = append(errs, nexgenjson.Violation{"blocks", "expected array"})
	}
	if len(errs) > 0 {
		return &nexgenjson.ValidationError{Violations: errs}
	}
	return nil
}

func (m Page) MarshalJSON() ([]byte, error) {
	var errs []nexgenjson.Violation
	nexgenjson.AddViolations(&errs, m.Validate())
	out := map[string]json.RawMessage{}
	nexgenjson.MarshalField(out, "pageId", m.PageId, &errs)
	nexgenjson.MarshalField(out, "title", m.Title, &errs)
	nexgenjson.MarshalField(out, "meta", m.Meta, &errs)
	if m.Blocks != nil {
		nexgenjson.MarshalField(out, "blocks", m.Blocks, &errs)
	}
	if len(errs) > 0 {
		return nil, &nexgenjson.ValidationError{Violations: errs}
	}
	return json.Marshal(out)
}

// Non-cyclic helper. Referenced only by Page, references nothing recursive, so it stays in the content_page module even though Page is hoisted.
type PageMeta struct {
	Author    string `json:"author"`
	WordCount *int64 `json:"wordCount,omitempty"`
}

func (m PageMeta) Validate() error {
	var errs []nexgenjson.Violation
	if m.WordCount != nil && (*m.WordCount < -nexgenjson.IntegerCap || *m.WordCount > nexgenjson.IntegerCap) {
		errs = append(errs, nexgenjson.Violation{"wordCount", "exceeds ±(2^53-1) integer cap"})
	}
	if len(errs) > 0 {
		return &nexgenjson.ValidationError{Violations: errs}
	}
	return nil
}

func (m *PageMeta) UnmarshalJSON(data []byte) error {
	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	var errs []nexgenjson.Violation
	for k := range all {
		switch k {
		case "author", "wordCount":
		default:
			errs = append(errs, nexgenjson.Violation{k, "unknown field"})
		}
	}
	get := func(k string) *json.RawMessage {
		if v, ok := all[k]; ok {
			return &v
		}
		return nil
	}
	_ = get
	if v, ok := nexgenjson.ParseStringField(get("author"), "author", true, false, &errs); ok {
		m.Author = v
	}
	if v, ok := nexgenjson.ParseIntegerField(get("wordCount"), "wordCount", false, false, &errs); ok {
		m.WordCount = &v
	}
	if len(errs) > 0 {
		return &nexgenjson.ValidationError{Violations: errs}
	}
	return nil
}

func (m PageMeta) MarshalJSON() ([]byte, error) {
	var errs []nexgenjson.Violation
	nexgenjson.AddViolations(&errs, m.Validate())
	out := map[string]json.RawMessage{}
	nexgenjson.MarshalField(out, "author", m.Author, &errs)
	if m.WordCount != nil {
		nexgenjson.MarshalField(out, "wordCount", *m.WordCount, &errs)
	}
	if len(errs) > 0 {
		return nil, &nexgenjson.ValidationError{Violations: errs}
	}
	return json.Marshal(out)
}
