// Generated by nexgen latest. DO NOT EDIT!

export { knowledgeBaseService, KnowledgeBaseServiceClient } from "./services";
export type { GetCategoryTreeInput, GetPageInput, PutBlockOutput } from "./models";
