// <auto-generated />
// Generated by nexgen v0.2.3. DO NOT EDIT!
#nullable enable
#pragma warning disable CS1591

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;

namespace Nexgen.TypeShowcase
{

    [GeneratedCode("nexgen", null)]
    public sealed class NexusResult<TOk, TErr>
    {
        private NexusResult(bool isOk, TOk? ok, TErr? err)
        {
            IsOk = isOk;
            Ok = ok;
            Err = err;
        }

        public bool IsOk { get; }
        public TOk? Ok { get; }
        public TErr? Err { get; }

        public static NexusResult<TOk, TErr> FromOk(TOk value) => new(true, value, default);
        public static NexusResult<TOk, TErr> FromErr(TErr value) => new(false, default, value);
    }

    [GeneratedCode("nexgen", null)]
    public enum UserStatus
    {
        Active = 0,
        Suspended = 1,
        Deleted = 2,
    }

    [GeneratedCode("nexgen", null)]
    [Flags]
    public enum UserCapability
    {
        None = 0,
        ReadProfile = 1 << 0,
        UpdateEmail = 1 << 1,
        Deactivate = 1 << 2,
    }

    [GeneratedCode("nexgen", null)]
    public abstract record NotificationTarget
    {
        private NotificationTarget() { }

        [GeneratedCode("nexgen", null)]
        public sealed record Email(string Value) : NotificationTarget;

        [GeneratedCode("nexgen", null)]
        public sealed record Sms(string Value) : NotificationTarget;

        [GeneratedCode("nexgen", null)]
        public sealed record None : NotificationTarget;
    }

    [GeneratedCode("nexgen", null)]
    public record DeactivateRequest
    {
        public DeactivateRequest(string userId)
        {
            UserId = userId;
        }

        public string UserId { get; init; }
        public string? Reason { get; init; }
    }

    [GeneratedCode("nexgen", null)]
    public record GetUserRequest
    {
        public GetUserRequest(string userId)
        {
            UserId = userId;
        }

        public string UserId { get; init; }
        public string? ConsistencyToken { get; init; }
    }

    [GeneratedCode("nexgen", null)]
    public record PostalAddress
    {
        public PostalAddress(string street, string city, string country)
        {
            Street = street;
            City = city;
            Country = country;
        }

        public string Street { get; init; }
        public string City { get; init; }
        public string Country { get; init; }
        public (double, double)? Coordinates { get; init; }
    }

    [GeneratedCode("nexgen", null)]
    public record RecordSyncRequest
    {
        public RecordSyncRequest(string userId, SyncReport report)
        {
            UserId = userId;
            Report = report;
        }

        public string UserId { get; init; }
        public SyncReport Report { get; init; }
    }

    [GeneratedCode("nexgen", null)]
    public record RenameRequest
    {
        public RenameRequest(string userId, string displayName)
        {
            UserId = userId;
            DisplayName = displayName;
        }

        public string UserId { get; init; }
        public string DisplayName { get; init; }
    }

    [GeneratedCode("nexgen", null)]
    public record SetProfileRequest
    {
        public SetProfileRequest(string userId, UserProfile profile)
        {
            UserId = userId;
            Profile = profile;
        }

        public string UserId { get; init; }
        public UserProfile Profile { get; init; }
    }

    [GeneratedCode("nexgen", null)]
    public record SyncReport
    {
        public SyncReport(IReadOnlyList<(double, double)> route, IReadOnlyList<NexusResult<string, string>> attempts, IReadOnlyDictionary<string, NexusResult<string, string>> regionStatus)
        {
            Route = route;
            Attempts = attempts;
            RegionStatus = regionStatus;
        }

        public IReadOnlyList<(double, double)> Route { get; init; }
        public IReadOnlyList<NexusResult<string, string>> Attempts { get; init; }
        public IReadOnlyDictionary<string, NexusResult<string, string>> RegionStatus { get; init; }
    }

    [GeneratedCode("nexgen", null)]
    public record UpdateEmailRequest
    {
        public UpdateEmailRequest(string userId, string email)
        {
            UserId = userId;
            Email = email;
        }

        public string UserId { get; init; }
        public string Email { get; init; }
    }

    [GeneratedCode("nexgen", null)]
    public record UserProfile
    {
        public UserProfile(IReadOnlyList<string> tags, IReadOnlyDictionary<string, string> metadata, UserCapability capabilities, NexusResult<string, string> syncState, NotificationTarget notificationTarget)
        {
            Tags = tags;
            Metadata = metadata;
            Capabilities = capabilities;
            SyncState = syncState;
            NotificationTarget = notificationTarget;
        }

        public IReadOnlyList<string> Tags { get; init; }
        public IReadOnlyDictionary<string, string> Metadata { get; init; }
        public UserCapability Capabilities { get; init; }
        public NexusResult<string, string> SyncState { get; init; }
        public NotificationTarget NotificationTarget { get; init; }
        public PostalAddress? Address { get; init; }
    }

}
