// Generated by nex-gen. DO NOT EDIT!
#nullable enable
#pragma warning disable CS1591

using System;
using System.Collections.Generic;

namespace NexGen.TypeShowcase
{

    public sealed class NexusResult<TOk, TErr>
    {
        private NexusResult(bool isOk, TOk? ok, TErr? err)
        {
            IsOk = isOk;
            Ok = ok;
            Err = err;
        }

        public bool IsOk { get; }
        public TOk? Ok { get; }
        public TErr? Err { get; }

        public static NexusResult<TOk, TErr> FromOk(TOk value) => new(true, value, default);
        public static NexusResult<TOk, TErr> FromErr(TErr value) => new(false, default, value);
    }

    public enum UserStatus
    {
        Active = 0,
        Suspended = 1,
        Deleted = 2,
    }

    [Flags]
    public enum UserCapability
    {
        None = 0,
        ReadProfile = 1 << 0,
        UpdateEmail = 1 << 1,
        Deactivate = 1 << 2,
    }

    public abstract class NotificationTarget
    {
        private NotificationTarget() { }

        public sealed class Email : NotificationTarget
        {
            public Email(string value) => Value = value;

            public string Value { get; }
        }

        public sealed class Sms : NotificationTarget
        {
            public Sms(string value) => Value = value;

            public string Value { get; }
        }

        public sealed class None : NotificationTarget
        {
            public None() { }
        }

    }

    internal class GetUserRequest
    {
        internal GetUserRequest(string userId)
        {
            UserId = userId;
        }

        public string UserId { get; init; }
        public string? ConsistencyToken { get; init; }
    }

    internal class UpdateEmailRequest
    {
        internal UpdateEmailRequest(string userId, string email)
        {
            UserId = userId;
            Email = email;
        }

        public string UserId { get; init; }
        public string Email { get; init; }
    }

    internal class RenameRequest
    {
        internal RenameRequest(string userId, string displayName)
        {
            UserId = userId;
            DisplayName = displayName;
        }

        public string UserId { get; init; }
        public string DisplayName { get; init; }
    }

    internal class SetProfileRequest
    {
        internal SetProfileRequest(string userId, UserProfile profile)
        {
            UserId = userId;
            Profile = profile;
        }

        public string UserId { get; init; }
        public UserProfile Profile { get; init; }
    }

    public class UserProfile
    {
        public UserProfile(IReadOnlyList<string> tags, IReadOnlyDictionary<string, string> metadata, UserCapability capabilities, NexusResult<string, string> syncState, NotificationTarget notificationTarget)
        {
            Tags = tags;
            Metadata = metadata;
            Capabilities = capabilities;
            SyncState = syncState;
            NotificationTarget = notificationTarget;
        }

        public IReadOnlyList<string> Tags { get; init; }
        public IReadOnlyDictionary<string, string> Metadata { get; init; }
        public UserCapability Capabilities { get; init; }
        public NexusResult<string, string> SyncState { get; init; }
        public NotificationTarget NotificationTarget { get; init; }
        public PostalAddress? Address { get; init; }
    }

    public class PostalAddress
    {
        public PostalAddress(string street, string city, string country)
        {
            Street = street;
            City = city;
            Country = country;
        }

        public string Street { get; init; }
        public string City { get; init; }
        public string Country { get; init; }
        public (double, double)? Coordinates { get; init; }
    }

    internal class DeactivateRequest
    {
        internal DeactivateRequest(string userId)
        {
            UserId = userId;
        }

        public string UserId { get; init; }
        public string? Reason { get; init; }
    }

}
