// Generated by nex-gen. DO NOT EDIT!
#nullable enable
#pragma warning disable CS1591

using System;
using System.Collections.Generic;
using System.Reflection;
using NexusRpc;

namespace NexGen.TypeShowcase
{

    [NexusService("TypeShowcase")]
    internal interface ITypeShowcase
    {
        [NexusOperation("GetUser")]
        User GetUser(GetUserRequest request);

        [NexusOperation("UpdateEmail")]
        User UpdateEmail(UpdateEmailRequest request);

        [NexusOperation("Rename")]
        User Rename(RenameRequest request);

        [NexusOperation("SetProfile")]
        User SetProfile(SetProfileRequest request);

        [NexusOperation("Deactivate")]
        void Deactivate(DeactivateRequest request);

    }

    public sealed class NexGenNexusOperation
    {
        public NexGenNexusOperation(string endpoint, string service, string operation, Type serviceType, MethodInfo method, Type? requestType, Type responseType)
        {
            Endpoint = endpoint;
            Service = service;
            Operation = operation;
            ServiceType = serviceType;
            Method = method;
            RequestType = requestType;
            ResponseType = responseType;
        }

        public string Endpoint { get; }
        public string Service { get; }
        public string Operation { get; }
        public Type ServiceType { get; }
        public MethodInfo Method { get; }
        public Type? RequestType { get; }
        public Type ResponseType { get; }
    }

    public static class NexGenOperationRegistry
    {
        public static IReadOnlyDictionary<(string Service, string Operation), NexGenNexusOperation> Operations { get; } =
            new Dictionary<(string Service, string Operation), NexGenNexusOperation>
            {
                [("TypeShowcase", "GetUser")] = new NexGenNexusOperation(
                    endpoint: "type-showcase",
                    service: "TypeShowcase",
                    operation: "GetUser",
                    serviceType: typeof(ITypeShowcase),
                    method: typeof(ITypeShowcase).GetMethod(nameof(ITypeShowcase.GetUser))!,
                    requestType: typeof(GetUserRequest),
                    responseType: typeof(User)),
                [("TypeShowcase", "UpdateEmail")] = new NexGenNexusOperation(
                    endpoint: "type-showcase",
                    service: "TypeShowcase",
                    operation: "UpdateEmail",
                    serviceType: typeof(ITypeShowcase),
                    method: typeof(ITypeShowcase).GetMethod(nameof(ITypeShowcase.UpdateEmail))!,
                    requestType: typeof(UpdateEmailRequest),
                    responseType: typeof(User)),
                [("TypeShowcase", "Rename")] = new NexGenNexusOperation(
                    endpoint: "type-showcase",
                    service: "TypeShowcase",
                    operation: "Rename",
                    serviceType: typeof(ITypeShowcase),
                    method: typeof(ITypeShowcase).GetMethod(nameof(ITypeShowcase.Rename))!,
                    requestType: typeof(RenameRequest),
                    responseType: typeof(User)),
                [("TypeShowcase", "SetProfile")] = new NexGenNexusOperation(
                    endpoint: "type-showcase",
                    service: "TypeShowcase",
                    operation: "SetProfile",
                    serviceType: typeof(ITypeShowcase),
                    method: typeof(ITypeShowcase).GetMethod(nameof(ITypeShowcase.SetProfile))!,
                    requestType: typeof(SetProfileRequest),
                    responseType: typeof(User)),
                [("TypeShowcase", "Deactivate")] = new NexGenNexusOperation(
                    endpoint: "type-showcase",
                    service: "TypeShowcase",
                    operation: "Deactivate",
                    serviceType: typeof(ITypeShowcase),
                    method: typeof(ITypeShowcase).GetMethod(nameof(ITypeShowcase.Deactivate))!,
                    requestType: typeof(DeactivateRequest),
                    responseType: typeof(void)),
            };
    }

}
