// <auto-generated />
// Generated by nex-gen. DO NOT EDIT!
#nullable enable
#pragma warning disable CS1591

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Threading.Tasks;
using NexusRpc;

namespace NexGen.FunctionExecution
{

    [GeneratedCode("nex-gen", null)]
    [NexusService("FunctionExecution")]
    internal interface IFunctionExecution
    {
        [GeneratedCode("nex-gen", null)]
        [NexusOperation("ExecuteFunction")]
        ExecuteFunctionResult ExecuteFunction(ExecuteFunctionRequest request);

        [GeneratedCode("nex-gen", null)]
        [NexusOperation("ExecuteCountedFunction")]
        ExecuteCountedFunctionResult ExecuteCountedFunction(ExecuteCountedFunctionRequest request);

        [GeneratedCode("nex-gen", null)]
        [NexusOperation("ExecuteNamedFunction")]
        ExecuteNamedFunctionResult ExecuteNamedFunction(ExecuteNamedFunctionRequest request);

        [GeneratedCode("nex-gen", null)]
        [NexusOperation("ExecuteVarargsFunction")]
        ExecuteVarargsFunctionResult ExecuteVarargsFunction(ExecuteVarargsFunctionRequest request);

        [GeneratedCode("nex-gen", null)]
        [NexusOperation("ExecuteNamedVarargsFunction")]
        ExecuteNamedVarargsFunctionResult ExecuteNamedVarargsFunction(ExecuteNamedVarargsFunctionRequest request);

    }

}
