# Generated by nex-gen. DO NOT EDIT!

from __future__ import annotations

import dataclasses
import typing


ContextT = typing.TypeVar("ContextT")
MetadataT = typing.TypeVar("MetadataT")
OutputT = typing.TypeVar("OutputT")


@dataclasses.dataclass(slots=True, kw_only=True)
class GenericRequest(typing.Generic[ContextT]):
    context: ContextT
    contexts: list[ContextT] | None = dataclasses.field(default_factory=list)
    by_name: dict[str, ContextT] | None = dataclasses.field(default_factory=dict)
    nested: Inner[ContextT]


@dataclasses.dataclass(slots=True)
class Inner(typing.Generic[ContextT]):
    value: ContextT


@dataclasses.dataclass(slots=True)
class GenericResponse(typing.Generic[ContextT, OutputT, MetadataT]):
    context: ContextT
    completion: OperationCompletionResult[OutputT]
    metadata: MetadataT | None = None


@dataclasses.dataclass(slots=True)
class OperationCompletionSuccess(typing.Generic[OutputT]):
    output: OutputT


@dataclasses.dataclass(slots=True)
class OperationCompletionFailure:
    message: str


OperationCompletionResult: typing.TypeAlias = (
    OperationCompletionSuccess[OutputT] | OperationCompletionFailure
)
