// Generated by nex-gen. DO NOT EDIT.
package json_schema.api.showcase;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.jspecify.annotations.Nullable;

@JsonSerialize(using = GetShowcaseInput.Serializer.class)
@JsonDeserialize(using = GetShowcaseInput.Deserializer.class)
public final class GetShowcaseInput {
    private final String id;

    public GetShowcaseInput(String id) {
        this.id = id;
    }

    public String getId() {
        return id;
    }

    @Override
    public boolean equals(@Nullable Object other) {
        if (this == other) {
            return true;
        }
        if (!(other instanceof GetShowcaseInput)) {
            return false;
        }
        GetShowcaseInput that = (GetShowcaseInput) other;
        return Objects.equals(this.id, that.id);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id);
    }

    @Override
    public String toString() {
        return "GetShowcaseInput{"
            + "id=" + id
            + "}";
    }

    public static final class Serializer extends com.fasterxml.jackson.databind.JsonSerializer<GetShowcaseInput> {
        @Override
        public void serialize(GetShowcaseInput value, JsonGenerator gen, SerializerProvider serializers) throws IOException {
            gen.writeStartObject();
            if (value.id != null) {
                gen.writeStringField("id", value.id);
            }
            gen.writeEndObject();
        }
    }

    public static final class Deserializer extends com.fasterxml.jackson.databind.JsonDeserializer<GetShowcaseInput> {
        @Override
        public GetShowcaseInput deserialize(JsonParser parser, DeserializationContext context) throws IOException {
            JsonNode node = parser.readValueAsTree();
            List<Violation> violations = new ArrayList<>();
            if (node == null || !node.isObject()) {
                violations.add(new Violation("", "expected object"));
                throw new ValidationException(violations);
            }
            Iterator<String> fieldNames = node.fieldNames();
            while (fieldNames.hasNext()) {
                String key = fieldNames.next();
                switch (key) {
                    case "id":
                        break;
                    default:
                        violations.add(new Violation(key, "unknown field"));
                }
            }
            String id = null;
            {
                JsonNode field = node.get("id");
                if (field == null) {
                    violations.add(new Violation("id", "required"));
                } else if (field.isNull()) {
                    violations.add(new Violation("id", "explicit null not allowed"));
                } else {
                    if (!field.isTextual()) {
                        violations.add(new Violation("id", "expected string"));
                    } else {
                        id = field.textValue();
                    }
                }
            }
            if (!violations.isEmpty()) {
                throw new ValidationException(violations);
            }
            return new GetShowcaseInput(id);
        }
    }
}
