# Generated by nex-gen. DO NOT EDIT!

from __future__ import annotations

from . import services as _services
from .operations.start_workflow import start_workflow
from ._resources.started_workflow import restart_workflow
from ._resources.started_workflow import cancel_workflow

__all__ = [
    "cancel_workflow",
    "restart_workflow",
    "start_workflow",
]


__nexus_operation_registry__ = {
    (
        "StartWorkflowService",
        "StartWorkflow",
    ): _services.StartWorkflowService.start_workflow,
    (
        "StartWorkflowService",
        "RestartWorkflow",
    ): _services.StartWorkflowService.restart_workflow,
    (
        "StartWorkflowService",
        "CancelWorkflow",
    ): _services.StartWorkflowService.cancel_workflow,
}
