# Generated by nex-gen. DO NOT EDIT!

from __future__ import annotations

import collections.abc
import typing

import nexusrpc
import temporalio.converter
from . import services as _services
from .operations.start_workflow import start_workflow
from ._resources.started_workflow import restart_workflow
from ._resources.started_workflow import cancel_workflow

__all__ = [
    "cancel_workflow",
    "restart_workflow",
    "start_workflow",
]


_InputT = typing.TypeVar("_InputT")
_OutputT = typing.TypeVar("_OutputT")


_SerializationContextFactory = collections.abc.Callable[
    [_InputT], temporalio.converter.SerializationContext
]


class _NexusOperationInfo(typing.Generic[_InputT, _OutputT]):
    def __init__(
        self,
        *,
        operation: nexusrpc.Operation[_InputT, _OutputT],
        serialization_context: _SerializationContextFactory[_InputT] | None = None,
    ) -> None:
        self.operation: nexusrpc.Operation[_InputT, _OutputT] = operation
        self.serialization_context: _SerializationContextFactory[_InputT] | None = (
            serialization_context
        )


__nexus_operation_registry__ = {
    (
        "StartWorkflowService",
        "StartWorkflow",
    ): _NexusOperationInfo(
        operation=_services.StartWorkflowService.start_workflow,
    ),
    (
        "StartWorkflowService",
        "RestartWorkflow",
    ): _NexusOperationInfo(
        operation=_services.StartWorkflowService.restart_workflow,
    ),
    (
        "StartWorkflowService",
        "CancelWorkflow",
    ): _NexusOperationInfo(
        operation=_services.StartWorkflowService.cancel_workflow,
    ),
}
