# Generated by nex-gen. DO NOT EDIT!
# pyright: reportAny=false

from __future__ import annotations

import collections.abc
import dataclasses
import typing
import typing_extensions
import datetime
import nex_gen_runtime
import temporalio.api.workflowservice.v1.request_response_pb2
import temporalio.workflow

from ..models import (
    CancelWorkflowRequest,
    StartWorkflowRequest,
    WorkflowExecution,
)


WorkflowArgs = typing_extensions.TypeVarTuple("WorkflowArgs")


@dataclasses.dataclass
class StartedWorkflow:
    namespace: str
    workflow_id: str
    run_id: str | None

    async def cancel(
        self,
        reason: str | None = None,
    ) -> None:
        request = CancelWorkflowRequest(
            workflow_execution=WorkflowExecution(
                workflow_id=self.workflow_id, run_id=self.run_id
            ),
            reason=reason,
        )
        handle = await _cancel_workflow(request)
        await handle

    async def restart_workflow(
        self,
        workflow: str
        | collections.abc.Callable[..., collections.abc.Awaitable[object]],
        task_queue: str,
    ) -> StartedWorkflow:
        request = StartWorkflowRequest(
            workflow_id=self.workflow_id,
            workflow=workflow,
            task_queue=task_queue,
        )
        return await _restart_workflow(request)

    async def get_result(
        self,
    ) -> collections.abc.Sequence[typing.Any]:
        raise NotImplementedError("started-workflow.get_result is not yet implemented")


async def _cancel_workflow(
    request: CancelWorkflowRequest,
) -> temporalio.workflow.NexusOperationHandle[
    temporalio.api.workflowservice.v1.request_response_pb2.RequestCancelWorkflowExecutionResponse,
]:
    nexus_client = temporalio.workflow.create_nexus_client(
        service="WorkflowService",
        endpoint="temporal-system",
    )
    return await nexus_client.start_operation(
        operation="CancelWorkflow",
        input=request.to_proto(),
        output_type=temporalio.api.workflowservice.v1.request_response_pb2.RequestCancelWorkflowExecutionResponse,
    )


async def cancel_workflow(
    *,
    workflow_execution: WorkflowExecution,
    reason: str | None = None,
) -> temporalio.workflow.NexusOperationHandle[
    temporalio.api.workflowservice.v1.request_response_pb2.RequestCancelWorkflowExecutionResponse,
]:
    request = CancelWorkflowRequest(
        workflow_execution=workflow_execution,
        reason=reason,
    )
    return await _cancel_workflow(request)


async def _restart_workflow(
    request: StartWorkflowRequest,
) -> StartedWorkflow:
    request_proto = request.to_proto()
    nexus_client = temporalio.workflow.create_nexus_client(
        service="WorkflowService",
        endpoint="temporal-system",
    )
    handle = await nexus_client.start_operation(
        operation="RestartWorkflow",
        input=request_proto,
        output_type=temporalio.api.workflowservice.v1.request_response_pb2.StartWorkflowExecutionResponse,
    )
    result = await handle
    return StartedWorkflow(
        namespace=request_proto.namespace,
        workflow_id=request.workflow_id,
        run_id=result.run_id or None,
    )


@typing.overload
async def restart_workflow(
    workflow: str,
    *positional_args: object,
    args: list[typing.Any] | None = ...,
    workflow_id: str,
    task_queue: str,
    workflow_start_delay: datetime.timedelta | None = ...,
) -> StartedWorkflow: ...


@typing.overload
async def restart_workflow(
    workflow: collections.abc.Callable[
        [typing.Any, typing_extensions.Unpack[WorkflowArgs]],
        collections.abc.Awaitable[object],
    ],
    *positional_args: typing_extensions.Unpack[WorkflowArgs],
    workflow_id: str,
    task_queue: str,
    workflow_start_delay: datetime.timedelta | None = ...,
) -> StartedWorkflow: ...


@typing.overload
async def restart_workflow(
    workflow: collections.abc.Callable[..., collections.abc.Awaitable[object]],
    *,
    args: list[typing.Any],
    workflow_id: str,
    task_queue: str,
    workflow_start_delay: datetime.timedelta | None = ...,
) -> StartedWorkflow: ...


async def restart_workflow(
    workflow: str | collections.abc.Callable[..., collections.abc.Awaitable[object]],
    *positional_args: object,
    args: list[typing.Any] | None = None,
    workflow_id: str,
    task_queue: str,
    workflow_start_delay: datetime.timedelta | None = None,
) -> StartedWorkflow:
    """
    Args:
        positional_args: Positional arguments for workflow. Cannot be set if args is
            set.
        args: List-form arguments for workflow. Cannot be set if positional_args are
            set. For typed workflow callables, list contents are not statically
            typechecked; pass workflow arguments positionally for precise typechecking.
    """
    if positional_args and args is not None:
        raise TypeError("cannot specify both positional arguments and args")
    normalized_args: list[typing.Any] | None = (
        list(positional_args) if positional_args else args
    )
    request = StartWorkflowRequest(
        workflow=workflow,
        args=normalized_args,
        workflow_id=workflow_id,
        task_queue=task_queue,
        workflow_start_delay=workflow_start_delay,
    )
    return await _restart_workflow(request)


nex_gen_runtime.register_nexus_type(
    StartedWorkflow, "WorkflowService::resource::started-workflow"
)
