<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <Nullable>enable</Nullable>
    <AssemblyName>NexGen.DotNetExamples</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="bin/**/*.cs;obj/**/*.cs;tests/**/*.cs;**/Support/*.cs;wit/workflow-service/*.cs;json_schema/definitions/**/*.cs" />
    <Compile Include="wit/workflow-service/Support/TemporalSupport.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.26.1" />
    <PackageReference Include="NexusRpc" Version="0.3.0" />
    <PackageReference Include="Temporalio" Version="1.14.1" />
  </ItemGroup>
</Project>
