// <auto-generated />
// Generated by nexgen. DO NOT EDIT!
#nullable enable
#pragma warning disable CS1591

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Threading.Tasks;
using NexusRpc;

namespace Temporalio.Workflows
{

    /// <remarks>WARNING: This API is experimental and may change in the future.</remarks>
    [GeneratedCode("nexgen", null)]
    [NexusService("temporal.api.workflowservice.v1.WorkflowService")]
    internal interface IWorkflowService
    {
        /// <summary>
        /// Signal a workflow, starting it first if needed.
        /// </summary>
        /// <returns>A workflow handle to the started workflow.</returns>
        /// <remarks>WARNING: This API is experimental and may change in the future.</remarks>
        [GeneratedCode("nexgen", null)]
        [NexusOperation("SignalWithStartWorkflowExecution")]
        SignalWithStartWorkflowResponse SignalWithStartWorkflow(SignalWithStartWorkflowRequest request);

    }

}
