// Generated by nexgen v0.2.1. DO NOT EDIT!

import * as workflow from "@temporalio/workflow";
import { typeShowcase } from "../services";
import type { RenameRequest } from "../models";
import { User } from "../resources";

/**
 * @param request - Request for the operation.
 */
export async function rename(request: RenameRequest): Promise<User> {
  const client = workflow.createNexusServiceClient({
    service: typeShowcase,
    endpoint: "type-showcase",
  });
  const requestProto = request;
  const handle = await client.startOperation(
    typeShowcase.operations.rename,
    requestProto,
  );
  const resource = await handle.result();
  return new User(
    resource.userId,
    resource.email,
    resource.displayName,
    resource.status,
    resource.profile,
  );
}
