// Generated by nex-gen. DO NOT EDIT!

import * as workflow from "@temporalio/workflow";
import { functionExecution } from "../service";
import type {
  ExecuteNamedVarargsFunctionRequest,
  ExecuteNamedVarargsFunctionResult,
} from "../models";
import { nexusValue } from "../../nex-gen-runtime";

/**
 * @param request - Request for the operation.
 */
export async function executeNamedVarargsFunction<
  FunctionFn extends (...args: any[]) => string = (...args: any[]) => string,
>(
  request: ExecuteNamedVarargsFunctionRequest<FunctionFn>,
): Promise<workflow.NexusOperationHandle<ExecuteNamedVarargsFunctionResult>> {
  const client = workflow.createNexusServiceClient({
    service: functionExecution,
    endpoint: "function-execution",
  });
  return await client.startOperation(
    functionExecution.operations.executeNamedVarargsFunction,
    nexusValue("function-execution.execute-named-varargs-function-request", request),
  );
}
