# Generated by nex-gen. DO NOT EDIT!

from __future__ import annotations

import temporalio.workflow

from ..models import GetPageInput
from ...content.page.models import Page


async def get_page_request(
    endpoint: str,
    request: GetPageInput,
) -> temporalio.workflow.NexusOperationHandle[Page,]:
    """Fetch a page by id."""
    nexus_client = temporalio.workflow.create_nexus_client(
        service="example.kb.v1.KnowledgeBaseService",
        endpoint=endpoint,
    )
    return await nexus_client.start_operation(
        operation="GetPage",
        input=request,
        output_type=Page,
    )
