# Generated by nex-gen. DO NOT EDIT!

from __future__ import annotations

import temporalio.workflow

from ...tree.category.models import Category
from ..models import GetCategoryTreeInput


async def get_category_tree_request(
    endpoint: str,
    request: GetCategoryTreeInput,
) -> temporalio.workflow.NexusOperationHandle[Category,]:
    """Fetch the category tree rooted at a category."""
    nexus_client = temporalio.workflow.create_nexus_client(
        service="example.kb.v1.KnowledgeBaseService",
        endpoint=endpoint,
    )
    return await nexus_client.start_operation(
        operation="GetCategoryTree",
        input=request,
        output_type=Category,
    )
