// Code generated by nex-gen. DO NOT EDIT.

import {
  isPlainObject,
  ValidationError,
  Violation,
  collect,
} from "./definitions";

// ---------------------------------------------------------------------------
// Models.
// ---------------------------------------------------------------------------

/**
 * A category node in the tree.
 *
 * Recursive within this file: `children` refers back to `Category`. The
 * self-reference is a bare annotation — TS interfaces reference themselves
 * freely, and the edge terminates because `children` is optional (an absent
 * value ends the chain), so a finite instance always exists.
 */
export interface Category {
  id: string;
  name: string;
  children?: Category[];
}

/**
 * A palette of color swatches.
 *
 * Dead `$def`: defined but never referenced. Still emitted and exported —
 * it is intended reusable API surface, not waste.
 */
export interface Palette {
  swatches: string[];
}

// ---------------------------------------------------------------------------
// Category (closed struct; within-file recursive self-reference).
// ---------------------------------------------------------------------------

export function parseCategory(raw: unknown): Category {
  const violations: Violation[] = [];
  if (!isPlainObject(raw)) {
    throw new ValidationError([{ path: "", reason: "expected object" }]);
  }

  // id: required string.
  let id: string = undefined as unknown as string;
  if (raw.id === undefined || raw.id === null) {
    violations.push({ path: "id", reason: "required" });
  } else if (typeof raw.id !== "string") {
    violations.push({ path: "id", reason: "expected string" });
  } else {
    id = raw.id;
  }

  // name: required string.
  let name: string = undefined as unknown as string;
  if (raw.name === undefined || raw.name === null) {
    violations.push({ path: "name", reason: "required" });
  } else if (typeof raw.name !== "string") {
    violations.push({ path: "name", reason: "expected string" });
  } else {
    name = raw.name;
  }

  // children: optional Category[] (recursive; absence ends the chain).
  let children: Category[] | undefined = undefined;
  if (raw.children === null) {
    violations.push({ path: "children", reason: "explicit null not allowed" });
  } else if (raw.children !== undefined) {
    if (!Array.isArray(raw.children)) {
      violations.push({ path: "children", reason: "expected array" });
    } else {
      children = [];
      raw.children.forEach((el, i) => {
        try {
          children!.push(parseCategory(el));
        } catch (e) {
          collect(violations, `children[${i}]`, e);
        }
      });
    }
  }

  // Closed struct: reject every unknown key.
  for (const k of Object.keys(raw)) {
    if (k !== "id" && k !== "name" && k !== "children") {
      violations.push({ path: k, reason: "unknown field" });
    }
  }

  if (violations.length) throw new ValidationError(violations);
  const out: Category = { id, name };
  if (children !== undefined) out.children = children;
  return out;
}

export function serializeCategory(value: Category): unknown {
  const out: Record<string, unknown> = { id: value.id, name: value.name };
  if (value.children !== undefined) {
    out.children = value.children.map((el) => serializeCategory(el));
  }
  return out;
}

// ---------------------------------------------------------------------------
// Palette (closed struct; dead $def).
// ---------------------------------------------------------------------------

export function parsePalette(raw: unknown): Palette {
  const violations: Violation[] = [];
  if (!isPlainObject(raw)) {
    throw new ValidationError([{ path: "", reason: "expected object" }]);
  }

  // swatches: required string[].
  let swatches: string[] = undefined as unknown as string[];
  if (raw.swatches === undefined || raw.swatches === null) {
    violations.push({ path: "swatches", reason: "required" });
  } else if (!Array.isArray(raw.swatches)) {
    violations.push({ path: "swatches", reason: "expected array" });
  } else {
    swatches = [];
    raw.swatches.forEach((el, i) => {
      if (typeof el !== "string") {
        violations.push({ path: `swatches[${i}]`, reason: "expected string" });
      } else {
        swatches.push(el);
      }
    });
  }

  // Closed struct: reject every unknown key.
  for (const k of Object.keys(raw)) {
    if (k !== "swatches") violations.push({ path: k, reason: "unknown field" });
  }

  if (violations.length) throw new ValidationError(violations);
  return { swatches };
}

export function serializePalette(value: Palette): unknown {
  return { swatches: value.swatches };
}
