// Generated by nexus-api-gen. DO NOT EDIT!

import * as workflow from "@temporalio/workflow";
import { WorkflowService } from "../service.ts";
import { requiredField, startWorkflowRequestToProto } from "../models.ts";
import type { StartWorkflowRequest } from "../models.ts";
import { StartedWorkflow } from "../resources.ts";

/**
 * @param request - Request for the operation.
 */
export async function startWorkflow<
  WorkflowFn extends (...args: any[]) => Promise<any> = (
    ...args: any[]
  ) => Promise<any>,
>(request: StartWorkflowRequest<WorkflowFn>): Promise<StartedWorkflow> {
  const client = workflow.createNexusServiceClient({
    service: WorkflowService,
    endpoint: "temporal-system",
  });
  const requestProto = startWorkflowRequestToProto(request) ?? {};
  const handle = await client.startOperation(
    WorkflowService.operations.startWorkflow,
    requestProto,
  );
  const result = await handle.result();
  return new StartedWorkflow(
    requiredField(requestProto.namespace, "resource", "namespace"),
    request.workflowId,
    result.runId ?? undefined,
  );
}
