# Generated by nex-gen. DO NOT EDIT!

from __future__ import annotations

import temporalio.workflow

from ..models import (
    GetRoomInput,
    Room,
)


async def get_room_request(
    endpoint: str,
    request: GetRoomInput,
) -> temporalio.workflow.NexusOperationHandle[Room,]:
    """Look up a room by id."""
    nexus_client = temporalio.workflow.create_nexus_client(
        service="example.chat.v1.ChatService",
        endpoint=endpoint,
    )
    return await nexus_client.start_operation(
        operation="GetRoom",
        input=request,
        output_type=Room,
    )
