# Generated by nex-gen. DO NOT EDIT!

from __future__ import annotations

from . import services as _services
from .operations.execute_function import execute_function
from .operations.execute_counted_function import execute_counted_function
from .operations.execute_named_function import execute_named_function
from .operations.execute_varargs_function import execute_varargs_function
from .operations.execute_named_varargs_function import execute_named_varargs_function

__all__ = [
    "execute_counted_function",
    "execute_function",
    "execute_named_function",
    "execute_named_varargs_function",
    "execute_varargs_function",
]


__nexus_operation_registry__ = {
    (
        "FunctionExecution",
        "ExecuteFunction",
    ): _services.FunctionExecution.execute_function,
    (
        "FunctionExecution",
        "ExecuteCountedFunction",
    ): _services.FunctionExecution.execute_counted_function,
    (
        "FunctionExecution",
        "ExecuteNamedFunction",
    ): _services.FunctionExecution.execute_named_function,
    (
        "FunctionExecution",
        "ExecuteVarargsFunction",
    ): _services.FunctionExecution.execute_varargs_function,
    (
        "FunctionExecution",
        "ExecuteNamedVarargsFunction",
    ): _services.FunctionExecution.execute_named_varargs_function,
}
