# Generated by nex-gen. DO NOT EDIT!

from __future__ import annotations

import datetime
import temporalio.workflow

from ..models import (
    StartWorkflowRequest,
    StartWorkflowResult,
)
from .._resources import StartedWorkflow


async def _start_workflow(
    request: StartWorkflowRequest,
) -> StartedWorkflow:
    nexus_client = temporalio.workflow.create_nexus_client(
        service="StartWorkflowService",
        endpoint="temporal-system",
    )
    handle = await nexus_client.start_operation(
        operation="StartWorkflow",
        input=request,
        output_type=StartWorkflowResult,
    )
    result = await handle
    return StartedWorkflow(
        namespace=request.namespace,
        workflow_id=request.workflow_id,
        run_id=result.run_id or None,
    )


async def start_workflow(
    *,
    workflow: str,
    workflow_id: str,
    task_queue: str,
    workflow_start_delay: datetime.timedelta | None = None,
) -> StartedWorkflow:
    request = StartWorkflowRequest(
        workflow=workflow,
        workflow_id=workflow_id,
        task_queue=task_queue,
        workflow_start_delay=workflow_start_delay,
    )
    return await _start_workflow(request)
