# Generated by nex-gen. DO NOT EDIT!
# pyright: reportAny=false

from __future__ import annotations

from nexusrpc import Operation, service
from .models import (
    GetUserRequest,
    UpdateEmailRequest,
)
from ._resources.user import User


@service
class UserService:
    get_user: Operation[
        GetUserRequest,
        User,
    ] = Operation(name="GetUser")

    update_email: Operation[
        UpdateEmailRequest,
        User,
    ] = Operation(name="UpdateEmail")
