// Generated by nexgen v0.2.1. DO NOT EDIT!

import * as nexus from "nexus-rpc";
import {
  getShowcaseInputTransferTypeConverter,
  showcaseTransferTypeConverter,
} from "./models";
import type { GetShowcaseInput, Showcase } from "./models";

/**
 * Fetch the showcase payload. Also exercises the service-level `x-<lang>-name`
 * override: the emitted service code identifier is renamed to the derived name plus a
 * per-language suffix (Go var `ShowcaseServiceGo`, TS const `showcaseServiceTs`, Python
 * class `ShowcaseServicePy`, Java interface `ShowcaseServiceJava`) while the wire
 * service name / `@Service` / `ServiceName` string stays
 * `example.showcase.v1.ShowcaseService`.
 */
export const showcaseServiceTs = nexus.service("example.showcase.v1.ShowcaseService", {
  /**
   * Fetch a showcase by id. Also exercises the operation-level `x-<lang>-name`
   * override: the emitted operation code identifier is renamed to the derived name plus
   * a per-language suffix (Go `GetShowcaseGo`, TS `getShowcaseTs`, Python
   * `get_showcase_py`, Java `getShowcaseJava`) while the wire operation name stays
   * `GetShowcase` and the synthesized I/O type stays `GetShowcaseInput` (derived from
   * the operation key, not the override).
   */
  getShowcaseTs: nexus.operation<GetShowcaseInput, Showcase>({
    name: "GetShowcase",
    inputType: { transferTypeConverter: getShowcaseInputTransferTypeConverter },
    outputType: { transferTypeConverter: showcaseTransferTypeConverter },
  }),
});
