// Generated by nex-gen. DO NOT EDIT!
#nullable enable
#pragma warning disable CS1591

using NexusRpc;

namespace NexusApiGen.TypeRoundtripService;

[NexusService("TypeRoundtripService")]
internal interface ITypeRoundtripService
{
    [NexusOperation("RetryPolicyOperation")]
    Temporalio.Common.RetryPolicy RetryPolicyOperation(Temporalio.Common.RetryPolicy request);

    [NexusOperation("ActivityOptionsOperation")]
    Temporalio.Api.Activity.V1.ActivityOptions ActivityOptionsOperation(Temporalio.Api.Activity.V1.ActivityOptions request);

}

