// Generated by nexus-api-gen. DO NOT EDIT!

import * as workflow from "@temporalio/workflow";
import type { temporal } from "@temporalio/proto";
import { TypeRoundtripService } from "../service.ts";
import { activityOptionsToProto } from "../models.ts";
import type { ActivityOptions } from "../models.ts";

/**
 * @param request - Request for the operation.
 */
export async function activityOptionsOperation(
  request: ActivityOptions,
): Promise<workflow.NexusOperationHandle<temporal.api.activity.v1.IActivityOptions>> {
  const client = workflow.createNexusServiceClient({
    service: TypeRoundtripService,
    endpoint: "temporal-system",
  });
  return await client.startOperation(
    TypeRoundtripService.operations.activityOptionsOperation,
    activityOptionsToProto(request) ?? {},
  );
}
