# Generated by nex-gen. DO NOT EDIT!

from __future__ import annotations

import collections.abc
import typing
import typing_extensions
import temporalio.workflow

from ..models import (
    ExecuteVarargsFunctionRequest,
    ExecuteVarargsFunctionResult,
)


FunctionArgs = typing_extensions.TypeVarTuple("FunctionArgs")


async def _execute_varargs_function(
    request: ExecuteVarargsFunctionRequest,
) -> temporalio.workflow.NexusOperationHandle[ExecuteVarargsFunctionResult,]:
    nexus_client = temporalio.workflow.create_nexus_client(
        service="FunctionExecution",
        endpoint="function-execution",
    )
    return await nexus_client.start_operation(
        operation="ExecuteVarargsFunction",
        input=request,
        output_type=ExecuteVarargsFunctionResult,
    )


# Overload case:
# - function callable with typed positional function arguments
@typing.overload
async def execute_varargs_function(
    function: collections.abc.Callable[[typing_extensions.Unpack[FunctionArgs]], str],
    *positional_args: typing_extensions.Unpack[FunctionArgs],
) -> temporalio.workflow.NexusOperationHandle[ExecuteVarargsFunctionResult]: ...


# Overload case:
# - function callable with list-form function arguments
@typing.overload
async def execute_varargs_function(
    function: collections.abc.Callable[..., str],
    *,
    args: list[typing.Any],
) -> temporalio.workflow.NexusOperationHandle[ExecuteVarargsFunctionResult]: ...


async def execute_varargs_function(
    function: collections.abc.Callable[..., str],
    *positional_args: object,
    args: list[typing.Any] | None = None,
) -> temporalio.workflow.NexusOperationHandle[ExecuteVarargsFunctionResult,]:
    """
    Args:
        positional_args: Positional arguments for function. Cannot be set if args is
            set.
        args: List-form arguments for function. Cannot be set if positional_args are
            set. For typed function callables, list contents are not statically
            typechecked; pass function arguments positionally for precise typechecking.
    """
    if positional_args and args is not None:
        raise TypeError("cannot specify both positional arguments and args")
    normalized_args: list[typing.Any] | None = (
        list(positional_args) if positional_args else args
    )
    request = ExecuteVarargsFunctionRequest(
        function=function,
        args=normalized_args,
    )
    return await _execute_varargs_function(request)
