// Generated by nex-gen. DO NOT EDIT!

import * as workflow from "@temporalio/workflow";
import { TypeShowcase } from "../service.ts";
import type { GetUserRequest } from "../models.ts";
import "../resources.ts";
import type { User } from "../resources.ts";
import { nexusValue } from "../../nex-gen-runtime.ts";

/**
 * @param request - Request for the operation.
 */
export async function getUser(request: GetUserRequest): Promise<User> {
  const client = workflow.createNexusServiceClient({
    service: TypeShowcase,
    endpoint: "type-showcase",
  });
  const requestProto = nexusValue("type-showcase.get-user-request", request);
  const handle = await client.startOperation(
    TypeShowcase.operations.getUser,
    requestProto,
  );
  return await handle.result();
}
