// Generated by nex-gen. DO NOT EDIT!

import * as workflow from "@temporalio/workflow";
import { TypeShowcase } from "../service.ts";
import type { RecordSyncRequest } from "../models.ts";
import { nexusValue } from "../../nex-gen-runtime.ts";

/**
 * @param request - Request for the operation.
 */
export async function recordSync(
  request: RecordSyncRequest,
): Promise<workflow.NexusOperationHandle<void>> {
  const client = workflow.createNexusServiceClient({
    service: TypeShowcase,
    endpoint: "type-showcase",
  });
  return await client.startOperation(
    TypeShowcase.operations.recordSync,
    nexusValue("type-showcase.record-sync-request", request),
  );
}
