// Generated by nexus-api-gen. DO NOT EDIT!

import * as workflow from "@temporalio/workflow";
import { TypeShowcase } from "../service.ts";
import type { UpdateEmailRequest } from "../models.ts";
import { User } from "../resources.ts";
import { nexusValue } from "../../nexus-api-gen-runtime.ts";

/**
 * @param request - Request for the operation.
 */
export async function updateEmail(request: UpdateEmailRequest): Promise<User> {
  const client = workflow.createNexusServiceClient({
    service: TypeShowcase,
    endpoint: "type-showcase",
  });
  const requestProto = nexusValue("type-showcase.update-email-request", request);
  const handle = await client.startOperation(
    TypeShowcase.operations.updateEmail,
    requestProto,
  );
  return await handle.result();
}
