// Generated by nexgen latest. DO NOT EDIT!

export function requiredField<T>(
  value: T | null | undefined,
  owner: string,
  field: string,
): T {
  if (value == null) {
    throw new Error(`missing required field ${owner}.${field}`);
  }
  return value;
}

export interface GetUserRequest {
  userId: string;
}

export interface UpdateEmailRequest {
  userId: string;
  email: string;
}
