// Generated by nex-gen. DO NOT EDIT!

import { Temporal as TemporalApi } from "@js-temporal/polyfill";
import * as __nexGenDefinitions from "./definitions";

/**
 * Temporal
 * Root object materializing the four RFC 3339 temporal formats as native typed fields: date-time (offset & sub-second precision preserved), date, time (offset preserved when present), and duration (time-only, canonicalized). Covers required, optional, and nullable members of each.
 */
export interface Temporal {
  /**
   * Required event timestamp; materialized date-time (offset required, sub-second precision & offset preserved on round-trip).
   */
  createdAt: TemporalApi.ZonedDateTime;
  /**
   * Required calendar date; materialized date (YYYY-MM-DD, lossless).
   */
  birthday: TemporalApi.PlainDate;
  /**
   * Required wall-clock time; materialized time (offset preserved when present, otherwise offset-less).
   */
  alarm: string;
  /**
   * Required time-only duration; materialized duration, canonicalized to PT…H…M…S (e.g. PT90M → PT1H30M).
   */
  timeout: TemporalApi.Duration;
  /**
   * Optional date-time.
   */
  updatedAt?: TemporalApi.ZonedDateTime;
  /**
   * Optional date.
   */
  expiresOn?: TemporalApi.PlainDate;
  /**
   * Optional time.
   */
  reminder?: string;
  /**
   * Optional duration.
   */
  retryDelay?: TemporalApi.Duration;
  /**
   * Optional and nullable date-time (may be absent or explicitly null).
   */
  deletedAt?: TemporalApi.ZonedDateTime | null;
  /**
   * Optional and nullable date.
   */
  archivedOn?: TemporalApi.PlainDate | null;
}

export class TemporalMapper {
  public fromIntermediate(raw: unknown): Temporal {
    const violations: __nexGenDefinitions.Violation[] = [];
    if (!__nexGenDefinitions.isPlainObject(raw)) {
      throw new __nexGenDefinitions.ValidationError([
        { path: "", reason: "expected object" },
      ]);
    }

    let createdAt: TemporalApi.ZonedDateTime =
      undefined as unknown as TemporalApi.ZonedDateTime;
    if (raw.createdAt === undefined || raw.createdAt === null) {
      violations.push({ path: "createdAt", reason: "required" });
    } else {
      if (typeof raw.createdAt !== "string") {
        violations.push({ path: "createdAt", reason: "expected string" });
      } else {
        const parsed = __nexGenDefinitions.parseTemporalDateTime(
          raw.createdAt,
          "createdAt",
          violations,
        );
        if (parsed !== undefined) {
          createdAt = parsed;
        }
      }
    }

    let birthday: TemporalApi.PlainDate = undefined as unknown as TemporalApi.PlainDate;
    if (raw.birthday === undefined || raw.birthday === null) {
      violations.push({ path: "birthday", reason: "required" });
    } else {
      if (typeof raw.birthday !== "string") {
        violations.push({ path: "birthday", reason: "expected string" });
      } else {
        const parsed = __nexGenDefinitions.parseTemporalDate(
          raw.birthday,
          "birthday",
          violations,
        );
        if (parsed !== undefined) {
          birthday = parsed;
        }
      }
    }

    let alarm: string = undefined as unknown as string;
    if (raw.alarm === undefined || raw.alarm === null) {
      violations.push({ path: "alarm", reason: "required" });
    } else {
      if (typeof raw.alarm !== "string") {
        violations.push({ path: "alarm", reason: "expected string" });
      } else {
        const parsed = __nexGenDefinitions.parseTemporalTime(
          raw.alarm,
          "alarm",
          violations,
        );
        if (parsed !== undefined) {
          alarm = parsed;
        }
      }
    }

    let timeout: TemporalApi.Duration = undefined as unknown as TemporalApi.Duration;
    if (raw.timeout === undefined || raw.timeout === null) {
      violations.push({ path: "timeout", reason: "required" });
    } else {
      if (typeof raw.timeout !== "string") {
        violations.push({ path: "timeout", reason: "expected string" });
      } else {
        const parsed = __nexGenDefinitions.parseTemporalDuration(
          raw.timeout,
          "timeout",
          violations,
        );
        if (parsed !== undefined) {
          timeout = parsed;
        }
      }
    }

    let updatedAt: TemporalApi.ZonedDateTime | undefined = undefined as unknown as
      | TemporalApi.ZonedDateTime
      | undefined;
    if (raw.updatedAt === null) {
      violations.push({ path: "updatedAt", reason: "explicit null not allowed" });
    } else if (raw.updatedAt !== undefined) {
      if (typeof raw.updatedAt !== "string") {
        violations.push({ path: "updatedAt", reason: "expected string" });
      } else {
        const parsed = __nexGenDefinitions.parseTemporalDateTime(
          raw.updatedAt,
          "updatedAt",
          violations,
        );
        if (parsed !== undefined) {
          updatedAt = parsed;
        }
      }
    }

    let expiresOn: TemporalApi.PlainDate | undefined = undefined as unknown as
      | TemporalApi.PlainDate
      | undefined;
    if (raw.expiresOn === null) {
      violations.push({ path: "expiresOn", reason: "explicit null not allowed" });
    } else if (raw.expiresOn !== undefined) {
      if (typeof raw.expiresOn !== "string") {
        violations.push({ path: "expiresOn", reason: "expected string" });
      } else {
        const parsed = __nexGenDefinitions.parseTemporalDate(
          raw.expiresOn,
          "expiresOn",
          violations,
        );
        if (parsed !== undefined) {
          expiresOn = parsed;
        }
      }
    }

    let reminder: string | undefined = undefined as unknown as string | undefined;
    if (raw.reminder === null) {
      violations.push({ path: "reminder", reason: "explicit null not allowed" });
    } else if (raw.reminder !== undefined) {
      if (typeof raw.reminder !== "string") {
        violations.push({ path: "reminder", reason: "expected string" });
      } else {
        const parsed = __nexGenDefinitions.parseTemporalTime(
          raw.reminder,
          "reminder",
          violations,
        );
        if (parsed !== undefined) {
          reminder = parsed;
        }
      }
    }

    let retryDelay: TemporalApi.Duration | undefined = undefined as unknown as
      | TemporalApi.Duration
      | undefined;
    if (raw.retryDelay === null) {
      violations.push({ path: "retryDelay", reason: "explicit null not allowed" });
    } else if (raw.retryDelay !== undefined) {
      if (typeof raw.retryDelay !== "string") {
        violations.push({ path: "retryDelay", reason: "expected string" });
      } else {
        const parsed = __nexGenDefinitions.parseTemporalDuration(
          raw.retryDelay,
          "retryDelay",
          violations,
        );
        if (parsed !== undefined) {
          retryDelay = parsed;
        }
      }
    }

    let deletedAt: TemporalApi.ZonedDateTime | null | undefined =
      undefined as unknown as TemporalApi.ZonedDateTime | null | undefined;
    if (raw.deletedAt !== undefined) {
      if (raw.deletedAt === null) {
        deletedAt = null;
      } else {
        if (typeof raw.deletedAt !== "string") {
          violations.push({ path: "deletedAt", reason: "expected string" });
        } else {
          const parsed = __nexGenDefinitions.parseTemporalDateTime(
            raw.deletedAt,
            "deletedAt",
            violations,
          );
          if (parsed !== undefined) {
            deletedAt = parsed;
          }
        }
      }
    }

    let archivedOn: TemporalApi.PlainDate | null | undefined = undefined as unknown as
      | TemporalApi.PlainDate
      | null
      | undefined;
    if (raw.archivedOn !== undefined) {
      if (raw.archivedOn === null) {
        archivedOn = null;
      } else {
        if (typeof raw.archivedOn !== "string") {
          violations.push({ path: "archivedOn", reason: "expected string" });
        } else {
          const parsed = __nexGenDefinitions.parseTemporalDate(
            raw.archivedOn,
            "archivedOn",
            violations,
          );
          if (parsed !== undefined) {
            archivedOn = parsed;
          }
        }
      }
    }

    for (const key of Object.keys(raw)) {
      if (
        key !== "createdAt" &&
        key !== "birthday" &&
        key !== "alarm" &&
        key !== "timeout" &&
        key !== "updatedAt" &&
        key !== "expiresOn" &&
        key !== "reminder" &&
        key !== "retryDelay" &&
        key !== "deletedAt" &&
        key !== "archivedOn"
      ) {
        violations.push({ path: key, reason: "unknown field" });
      }
    }

    if (violations.length) {
      throw new __nexGenDefinitions.ValidationError(violations);
    }
    const out: Temporal = { createdAt, birthday, alarm, timeout };
    if (updatedAt !== undefined) {
      out.updatedAt = updatedAt;
    }
    if (expiresOn !== undefined) {
      out.expiresOn = expiresOn;
    }
    if (reminder !== undefined) {
      out.reminder = reminder;
    }
    if (retryDelay !== undefined) {
      out.retryDelay = retryDelay;
    }
    if (deletedAt !== undefined) {
      out.deletedAt = deletedAt;
    }
    if (archivedOn !== undefined) {
      out.archivedOn = archivedOn;
    }
    return out;
  }

  public toIntermediate(value: Temporal): unknown {
    const violations: __nexGenDefinitions.Violation[] = [];
    const out: Record<string, unknown> = {};
    out.createdAt = __nexGenDefinitions.serializeTemporalDateTime(value.createdAt);
    out.birthday = __nexGenDefinitions.serializeTemporalDate(value.birthday);
    out.alarm = value.alarm;
    out.timeout = __nexGenDefinitions.serializeTemporalDuration(value.timeout);
    if (value.updatedAt !== undefined) {
      out.updatedAt = __nexGenDefinitions.serializeTemporalDateTime(value.updatedAt);
    }
    if (value.expiresOn !== undefined) {
      out.expiresOn = __nexGenDefinitions.serializeTemporalDate(value.expiresOn);
    }
    if (value.reminder !== undefined) {
      out.reminder = value.reminder;
    }
    if (value.retryDelay !== undefined) {
      out.retryDelay = __nexGenDefinitions.serializeTemporalDuration(value.retryDelay);
    }
    if (value.deletedAt !== undefined) {
      out.deletedAt =
        value.deletedAt === null
          ? null
          : __nexGenDefinitions.serializeTemporalDateTime(value.deletedAt);
    }
    if (value.archivedOn !== undefined) {
      out.archivedOn =
        value.archivedOn === null
          ? null
          : __nexGenDefinitions.serializeTemporalDate(value.archivedOn);
    }
    if (violations.length) {
      throw new __nexGenDefinitions.ValidationError(violations);
    }
    return out;
  }
}
