// Generated by nexgen latest. DO NOT EDIT.
package json_schema.api.kb.kb;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.temporal.failure.ApplicationFailure;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import json_schema.api.kb.SpecNumbers;
import json_schema.api.kb.Violation;
import org.jspecify.annotations.Nullable;

@JsonSerialize(using = GetPageInput.Serializer.class)
@JsonDeserialize(using = GetPageInput.Deserializer.class)
public final class GetPageInput {
    private final String pageId;

    public GetPageInput(String pageId) {
        this.pageId = pageId;
    }

    public String getPageId() {
        return pageId;
    }

    @Override
    public boolean equals(@Nullable Object other) {
        if (this == other) {
            return true;
        }
        if (!(other instanceof GetPageInput)) {
            return false;
        }
        GetPageInput that = (GetPageInput) other;
        return Objects.equals(this.pageId, that.pageId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(pageId);
    }

    @Override
    public String toString() {
        return "GetPageInput{"
            + "pageId=" + pageId
            + "}";
    }

    public static final class Serializer extends com.fasterxml.jackson.databind.JsonSerializer<GetPageInput> {
        @Override
        public void serialize(GetPageInput value, JsonGenerator gen, SerializerProvider serializers) throws IOException {
            gen.writeStartObject();
            if (value.pageId != null) {
                gen.writeStringField("pageId", value.pageId);
            }
            gen.writeEndObject();
        }
    }

    public static final class Deserializer extends com.fasterxml.jackson.databind.JsonDeserializer<GetPageInput> {
        @Override
        public GetPageInput deserialize(JsonParser parser, DeserializationContext context) throws IOException {
            JsonNode node = SpecNumbers.readExactTree(parser);
            List<Violation> violations = new ArrayList<>();
            if (node == null || !node.isObject()) {
                violations.add(new Violation("", "expected object"));
                // TODO: Use PayloadValidationException.newPayloadValidationException once it is available in an SDK release.
                throw ApplicationFailure.newNonRetryableFailure("Payload validation failed", "PayloadValidationError", violations);
            }
            Iterator<String> fieldNames = node.fieldNames();
            while (fieldNames.hasNext()) {
                String key = fieldNames.next();
                switch (key) {
                    case "pageId":
                        break;
                    default:
                        violations.add(new Violation(key, "unknown field"));
                }
            }
            String pageId = null;
            {
                JsonNode field = node.get("pageId");
                if (field == null) {
                    violations.add(new Violation("pageId", "required"));
                } else if (field.isNull()) {
                    violations.add(new Violation("pageId", "explicit null not allowed"));
                } else {
                    if (!field.isTextual()) {
                        violations.add(new Violation("pageId", "expected string"));
                    } else {
                        pageId = field.textValue();
                    }
                }
            }
            if (!violations.isEmpty()) {
                // TODO: Use PayloadValidationException.newPayloadValidationException once it is available in an SDK release.
                throw ApplicationFailure.newNonRetryableFailure("Payload validation failed", "PayloadValidationError", violations);
            }
            return new GetPageInput(pageId);
        }
    }
}
