// <auto-generated />
// Generated by nex-gen. DO NOT EDIT!
#nullable enable
#pragma warning disable CS1591

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;
using NexGen.Generated.Content.Block;

namespace NexGen.Generated.Content.Page
{

    /// <summary>
    /// A page. One half of the Page &lt;-&gt; Block cross-file cycle. Because the cycle spans two input files, Page and Block hoist together into Python's _recursive.py; the non-cyclic PageMeta helper stays in this module.
    /// </summary>
    [GeneratedCode("nex-gen", null)]
    public class Page : IJsonOnDeserialized
    {
        public Page(string pageId, string title, global::NexGen.Generated.Content.Page.PageMeta meta)
        {
            PageId = pageId;
            Title = title;
            Meta = meta;
        }

        [JsonPropertyName("pageId")]
        [JsonRequired]
        public string PageId { get; init; }
        [JsonPropertyName("title")]
        [JsonRequired]
        public string Title { get; init; }
        [JsonPropertyName("meta")]
        [JsonRequired]
        public global::NexGen.Generated.Content.Page.PageMeta Meta { get; init; }
        /// <summary>
        /// Ordered content blocks. Cross-file `$ref` to block.json (same directory); the array is the terminating edge of the cycle.
        /// </summary>
        [JsonIgnore]
        public IReadOnlyList<global::NexGen.Generated.Content.Block.Block>? Blocks
        {
            get => JsonRuntime.ReadOptionalValue<List<global::NexGen.Generated.Content.Block.Block>?>(AdditionalProperties, "blocks");
            init
            {
                JsonRuntime.RejectNull("blocks", value);
                AdditionalProperties["blocks"] = value;
            }
        }

        [JsonExtensionData]
        public Dictionary<string, object?> AdditionalProperties { get; set; } = new Dictionary<string, object?>();

        void IJsonOnDeserialized.OnDeserialized()
        {
            foreach (var key in AdditionalProperties.Keys)
            {
                if (key != "blocks")
                {
                    throw new JsonException($"Unknown field `{key}`.");
                }
            }
            if (AdditionalProperties.TryGetValue("blocks", out var blocksValue))
            {
                JsonRuntime.RejectNull("blocks", blocksValue);
                _ = JsonRuntime.ReadJsonValue<List<global::NexGen.Generated.Content.Block.Block>?>(blocksValue);
            }
        }
    }


    /// <summary>
    /// Non-cyclic helper. Referenced only by Page, references nothing recursive, so it stays in the content_page module even though Page is hoisted.
    /// </summary>
    [GeneratedCode("nex-gen", null)]
    public class PageMeta : IJsonOnDeserialized
    {
        public PageMeta(string author)
        {
            Author = author;
        }

        [JsonPropertyName("author")]
        [JsonRequired]
        public string Author { get; init; }
        [JsonIgnore]
        public long? WordCount
        {
            get => JsonRuntime.ReadOptionalValue<long?>(AdditionalProperties, "wordCount");
            init
            {
                JsonRuntime.RejectNull("wordCount", value);
                AdditionalProperties["wordCount"] = value;
            }
        }

        [JsonExtensionData]
        public Dictionary<string, object?> AdditionalProperties { get; set; } = new Dictionary<string, object?>();

        void IJsonOnDeserialized.OnDeserialized()
        {
            foreach (var key in AdditionalProperties.Keys)
            {
                if (key != "wordCount")
                {
                    throw new JsonException($"Unknown field `{key}`.");
                }
            }
            if (AdditionalProperties.TryGetValue("wordCount", out var wordCountValue))
            {
                JsonRuntime.RejectNull("wordCount", wordCountValue);
                _ = JsonRuntime.ReadJsonValue<long?>(wordCountValue);
            }
        }
    }

}
