// Generated by nexgen. DO NOT EDIT!

import type * as common from "@temporalio/common";
import type { temporal } from "@temporalio/proto";
import {
  workflowTypeToProto,
  taskQueueToProto,
  workflowNamespace,
  durationToProto,
} from "./support";

export function requiredField<T>(
  value: T | null | undefined,
  owner: string,
  field: string,
): T {
  if (value == null) {
    throw new Error(`missing required field ${owner}.${field}`);
  }
  return value;
}

export interface StartWorkflowResult {
  runId?: string;
}

export function startWorkflowResultFromProto(
  proto:
    | temporal.api.workflowservice.v1.IStartWorkflowExecutionResponse
    | null
    | undefined,
): StartWorkflowResult | undefined {
  if (proto == null) {
    return undefined;
  }
  return {
    runId: proto.runId ?? undefined,
  };
}

export function startWorkflowResultToProto(
  model: StartWorkflowResult | null | undefined,
): temporal.api.workflowservice.v1.IStartWorkflowExecutionResponse | undefined {
  if (model == null) {
    return undefined;
  }
  return {
    runId: model.runId,
  };
}

export interface StartWorkflowRequest {
  workflow: string;
  workflowId: string;
  taskQueue: string;
  workflowStartDelay?: common.Duration;
}

export function startWorkflowRequestToProto(
  model: StartWorkflowRequest | null | undefined,
): temporal.api.workflowservice.v1.IStartWorkflowExecutionRequest | undefined {
  if (model == null) {
    return undefined;
  }
  return {
    workflowType: workflowTypeToProto(
      requiredField(model.workflow, "StartWorkflowRequest", "workflow"),
    ),
    workflowId: requiredField(model.workflowId, "StartWorkflowRequest", "workflowId"),
    taskQueue: taskQueueToProto(
      requiredField(model.taskQueue, "StartWorkflowRequest", "taskQueue"),
    ),
    workflowStartDelay:
      model.workflowStartDelay == null
        ? undefined
        : durationToProto(model.workflowStartDelay),
    namespace: workflowNamespace(),
  };
}

export interface RestartWorkflowResult {
  runId?: string;
}

export function restartWorkflowResultFromProto(
  proto:
    | temporal.api.workflowservice.v1.IStartWorkflowExecutionResponse
    | null
    | undefined,
): RestartWorkflowResult | undefined {
  if (proto == null) {
    return undefined;
  }
  return {
    runId: proto.runId ?? undefined,
  };
}

export function restartWorkflowResultToProto(
  model: RestartWorkflowResult | null | undefined,
): temporal.api.workflowservice.v1.IStartWorkflowExecutionResponse | undefined {
  if (model == null) {
    return undefined;
  }
  return {
    runId: model.runId,
  };
}

export type CancelWorkflowResponse = Record<string, never>;

export function cancelWorkflowResponseToProto(
  model: CancelWorkflowResponse | null | undefined,
): temporal.api.workflowservice.v1.IRequestCancelWorkflowExecutionResponse | undefined {
  if (model == null) {
    return undefined;
  }
  return {};
}

export interface CancelWorkflowRequest {
  workflowExecution: WorkflowExecution;
  reason?: string;
}

export function cancelWorkflowRequestToProto(
  model: CancelWorkflowRequest | null | undefined,
): temporal.api.workflowservice.v1.IRequestCancelWorkflowExecutionRequest | undefined {
  if (model == null) {
    return undefined;
  }
  return {
    workflowExecution:
      workflowExecutionToProto(
        requiredField(
          model.workflowExecution,
          "CancelWorkflowRequest",
          "workflowExecution",
        ),
      ) ?? {},
    reason: model.reason,
    namespace: workflowNamespace(),
  };
}

export interface WorkflowExecution {
  workflowId: string;
  runId?: string;
}

export function workflowExecutionFromProto(
  proto: temporal.api.common.v1.IWorkflowExecution | null | undefined,
): WorkflowExecution | undefined {
  if (proto == null) {
    return undefined;
  }
  return {
    workflowId: requiredField(
      proto.workflowId === "" ? undefined : proto.workflowId,
      "WorkflowExecution",
      "workflowId",
    ),
    runId: proto.runId ?? undefined,
  };
}

export function workflowExecutionToProto(
  model: WorkflowExecution | null | undefined,
): temporal.api.common.v1.IWorkflowExecution | undefined {
  if (model == null) {
    return undefined;
  }
  return {
    workflowId: requiredField(model.workflowId, "WorkflowExecution", "workflowId"),
    runId: model.runId,
  };
}
