// <auto-generated />
// Generated by nex-gen. DO NOT EDIT!
#nullable enable
#pragma warning disable CS1591

using System;
using System.CodeDom.Compiler;
using NexusRpc;

namespace NexGen.Generated.Tree.Category
{

}
