// Generated by nex-gen. DO NOT EDIT!

import type { Violation } from "./definitions";
import {
  ValidationError,
  isPlainObject,
  parseTemporalDateTime,
  parseTemporalDate,
  parseTemporalTime,
  parseTemporalDuration,
  serializeTemporalDateTime,
} from "./definitions";

export function requiredField<T>(
  value: T | null | undefined,
  owner: string,
  field: string,
): T {
  if (value == null) {
    throw new Error(`missing required field ${owner}.${field}`);
  }
  return value;
}

/**
 * Temporal
 * Root object materializing the four RFC 3339 temporal formats as native typed fields: date-time (offset & sub-second precision preserved), date, time (offset preserved when present), and duration (time-only, canonicalized). Covers required, optional, and nullable members of each.
 */
export interface Temporal {
  /**
   * Required event timestamp; materialized date-time (offset required, sub-second precision & offset preserved on round-trip).
   */
  createdAt: Date;
  /**
   * Required calendar date; materialized date (YYYY-MM-DD, lossless).
   */
  birthday: string;
  /**
   * Required wall-clock time; materialized time (offset preserved when present, otherwise offset-less).
   */
  alarm: string;
  /**
   * Required time-only duration; materialized duration, canonicalized to PT…H…M…S (e.g. PT90M → PT1H30M).
   */
  timeout: string;
  /**
   * Optional date-time.
   */
  updatedAt?: Date;
  /**
   * Optional date.
   */
  expiresOn?: string;
  /**
   * Optional time.
   */
  reminder?: string;
  /**
   * Optional duration.
   */
  retryDelay?: string;
  /**
   * Optional and nullable date-time (may be absent or explicitly null).
   */
  deletedAt?: Date | null;
  /**
   * Optional and nullable date.
   */
  archivedOn?: string | null;
}

export class TemporalMapper {
  public fromIntermediate(raw: unknown): Temporal {
    const violations: Violation[] = [];
    if (!isPlainObject(raw)) {
      throw new ValidationError([{ path: "", reason: "expected object" }]);
    }

    let createdAt: Date = undefined as unknown as Date;
    if (raw.createdAt === undefined || raw.createdAt === null) {
      violations.push({ path: "createdAt", reason: "required" });
    } else {
      if (typeof raw.createdAt !== "string") {
        violations.push({ path: "createdAt", reason: "expected string" });
      } else {
        const parsed = parseTemporalDateTime(raw.createdAt, "createdAt", violations);
        if (parsed !== undefined) {
          createdAt = parsed;
        }
      }
    }

    let birthday: string = undefined as unknown as string;
    if (raw.birthday === undefined || raw.birthday === null) {
      violations.push({ path: "birthday", reason: "required" });
    } else {
      if (typeof raw.birthday !== "string") {
        violations.push({ path: "birthday", reason: "expected string" });
      } else {
        const parsed = parseTemporalDate(raw.birthday, "birthday", violations);
        if (parsed !== undefined) {
          birthday = parsed;
        }
      }
    }

    let alarm: string = undefined as unknown as string;
    if (raw.alarm === undefined || raw.alarm === null) {
      violations.push({ path: "alarm", reason: "required" });
    } else {
      if (typeof raw.alarm !== "string") {
        violations.push({ path: "alarm", reason: "expected string" });
      } else {
        const parsed = parseTemporalTime(raw.alarm, "alarm", violations);
        if (parsed !== undefined) {
          alarm = parsed;
        }
      }
    }

    let timeout: string = undefined as unknown as string;
    if (raw.timeout === undefined || raw.timeout === null) {
      violations.push({ path: "timeout", reason: "required" });
    } else {
      if (typeof raw.timeout !== "string") {
        violations.push({ path: "timeout", reason: "expected string" });
      } else {
        const parsed = parseTemporalDuration(raw.timeout, "timeout", violations);
        if (parsed !== undefined) {
          timeout = parsed;
        }
      }
    }

    let updatedAt: Date | undefined = undefined as unknown as Date | undefined;
    if (raw.updatedAt === null) {
      violations.push({ path: "updatedAt", reason: "explicit null not allowed" });
    } else if (raw.updatedAt !== undefined) {
      if (typeof raw.updatedAt !== "string") {
        violations.push({ path: "updatedAt", reason: "expected string" });
      } else {
        const parsed = parseTemporalDateTime(raw.updatedAt, "updatedAt", violations);
        if (parsed !== undefined) {
          updatedAt = parsed;
        }
      }
    }

    let expiresOn: string | undefined = undefined as unknown as string | undefined;
    if (raw.expiresOn === null) {
      violations.push({ path: "expiresOn", reason: "explicit null not allowed" });
    } else if (raw.expiresOn !== undefined) {
      if (typeof raw.expiresOn !== "string") {
        violations.push({ path: "expiresOn", reason: "expected string" });
      } else {
        const parsed = parseTemporalDate(raw.expiresOn, "expiresOn", violations);
        if (parsed !== undefined) {
          expiresOn = parsed;
        }
      }
    }

    let reminder: string | undefined = undefined as unknown as string | undefined;
    if (raw.reminder === null) {
      violations.push({ path: "reminder", reason: "explicit null not allowed" });
    } else if (raw.reminder !== undefined) {
      if (typeof raw.reminder !== "string") {
        violations.push({ path: "reminder", reason: "expected string" });
      } else {
        const parsed = parseTemporalTime(raw.reminder, "reminder", violations);
        if (parsed !== undefined) {
          reminder = parsed;
        }
      }
    }

    let retryDelay: string | undefined = undefined as unknown as string | undefined;
    if (raw.retryDelay === null) {
      violations.push({ path: "retryDelay", reason: "explicit null not allowed" });
    } else if (raw.retryDelay !== undefined) {
      if (typeof raw.retryDelay !== "string") {
        violations.push({ path: "retryDelay", reason: "expected string" });
      } else {
        const parsed = parseTemporalDuration(raw.retryDelay, "retryDelay", violations);
        if (parsed !== undefined) {
          retryDelay = parsed;
        }
      }
    }

    let deletedAt: Date | null | undefined = undefined as unknown as
      | Date
      | null
      | undefined;
    if (raw.deletedAt !== undefined) {
      if (raw.deletedAt === null) {
        deletedAt = null;
      } else {
        if (typeof raw.deletedAt !== "string") {
          violations.push({ path: "deletedAt", reason: "expected string" });
        } else {
          const parsed = parseTemporalDateTime(raw.deletedAt, "deletedAt", violations);
          if (parsed !== undefined) {
            deletedAt = parsed;
          }
        }
      }
    }

    let archivedOn: string | null | undefined = undefined as unknown as
      | string
      | null
      | undefined;
    if (raw.archivedOn !== undefined) {
      if (raw.archivedOn === null) {
        archivedOn = null;
      } else {
        if (typeof raw.archivedOn !== "string") {
          violations.push({ path: "archivedOn", reason: "expected string" });
        } else {
          const parsed = parseTemporalDate(raw.archivedOn, "archivedOn", violations);
          if (parsed !== undefined) {
            archivedOn = parsed;
          }
        }
      }
    }

    for (const key of Object.keys(raw)) {
      if (
        key !== "createdAt" &&
        key !== "birthday" &&
        key !== "alarm" &&
        key !== "timeout" &&
        key !== "updatedAt" &&
        key !== "expiresOn" &&
        key !== "reminder" &&
        key !== "retryDelay" &&
        key !== "deletedAt" &&
        key !== "archivedOn"
      ) {
        violations.push({ path: key, reason: "unknown field" });
      }
    }

    if (violations.length) {
      throw new ValidationError(violations);
    }
    const out: Temporal = { createdAt, birthday, alarm, timeout };
    if (updatedAt !== undefined) {
      out.updatedAt = updatedAt;
    }
    if (expiresOn !== undefined) {
      out.expiresOn = expiresOn;
    }
    if (reminder !== undefined) {
      out.reminder = reminder;
    }
    if (retryDelay !== undefined) {
      out.retryDelay = retryDelay;
    }
    if (deletedAt !== undefined) {
      out.deletedAt = deletedAt;
    }
    if (archivedOn !== undefined) {
      out.archivedOn = archivedOn;
    }
    return out;
  }

  public toIntermediate(value: Temporal): unknown {
    const violations: Violation[] = [];
    const out: Record<string, unknown> = {};
    out.createdAt = serializeTemporalDateTime(value.createdAt);
    out.birthday = value.birthday;
    out.alarm = value.alarm;
    out.timeout = value.timeout;
    if (value.updatedAt !== undefined) {
      out.updatedAt = serializeTemporalDateTime(value.updatedAt);
    }
    if (value.expiresOn !== undefined) {
      out.expiresOn = value.expiresOn;
    }
    if (value.reminder !== undefined) {
      out.reminder = value.reminder;
    }
    if (value.retryDelay !== undefined) {
      out.retryDelay = value.retryDelay;
    }
    if (value.deletedAt !== undefined) {
      out.deletedAt =
        value.deletedAt === null ? null : serializeTemporalDateTime(value.deletedAt);
    }
    if (value.archivedOn !== undefined) {
      out.archivedOn = value.archivedOn === null ? null : value.archivedOn;
    }
    if (violations.length) {
      throw new ValidationError(violations);
    }
    return out;
  }
}
