// Generated by nexus-api-gen. DO NOT EDIT!

import * as common from "@temporalio/common";
import type { temporal } from "@temporalio/proto";
import {
  workflowTypeToProto,
  taskQueueToProto,
  workflowNamespace,
  durationToProto,
} from "./support.ts";

export function requiredField<T>(
  value: T | null | undefined,
  owner: string,
  field: string,
): T {
  if (value == null) {
    throw new Error(`missing required field ${owner}.${field}`);
  }
  return value;
}

function configuredPayloadConverter(): common.PayloadConverter {
  const activator = (
    globalThis as typeof globalThis & {
      __TEMPORAL_ACTIVATOR__?: {
        payloadConverter?: common.PayloadConverter;
      };
    }
  ).__TEMPORAL_ACTIVATOR__;
  if (activator?.payloadConverter == null) {
    throw new Error("payload converter is unavailable outside workflow context");
  }
  return activator.payloadConverter;
}

function requestArgsToPayloads(
  args: ReadonlyArray<unknown> | undefined,
): temporal.api.common.v1.IPayloads | undefined {
  if (args == null) {
    return undefined;
  }
  const payloads = common.toPayloads(configuredPayloadConverter(), ...args);
  return payloads == null ? undefined : { payloads };
}

export type ReplaceStartWorkflowRequest<Base, New> = Omit<Base, "args" | "workflow"> &
  New;

export type StartWorkflowRequest<
  WorkflowFn extends (...args: any[]) => Promise<any> = (
    ...args: any[]
  ) => Promise<any>,
> = ReplaceStartWorkflowRequest<
  {
    workflow: string | WorkflowFn;
    /**
     * Arguments for workflow.
     */
    args?: ReadonlyArray<unknown> | Readonly<Parameters<WorkflowFn>>;
    workflowId: string;
    taskQueue: string;
    workflowStartDelay?: common.Duration;
  },
  | {
      workflow: string;
      /**
       * Arguments for workflow.
       */
      args?: ReadonlyArray<unknown>;
    }
  | ({
      workflow: WorkflowFn;
    } & (Parameters<WorkflowFn> extends [any, ...any[]]
      ? {
          /**
           * Arguments for workflow.
           */
          args: Parameters<WorkflowFn> | Readonly<Parameters<WorkflowFn>>;
        }
      : {
          /**
           * Arguments for workflow.
           */
          args?: Parameters<WorkflowFn> | Readonly<Parameters<WorkflowFn>>;
        }))
>;

export function startWorkflowRequestToProto<
  WorkflowFn extends (...args: any[]) => Promise<any> = (
    ...args: any[]
  ) => Promise<any>,
>(
  model: StartWorkflowRequest<WorkflowFn> | null | undefined,
): temporal.api.workflowservice.v1.IStartWorkflowExecutionRequest | undefined {
  if (model == null) {
    return undefined;
  }
  return {
    workflowType: workflowTypeToProto(
      requiredField(model.workflow, "StartWorkflowRequest", "workflow"),
    ),
    input: requestArgsToPayloads(model.args),
    workflowId: requiredField(model.workflowId, "StartWorkflowRequest", "workflowId"),
    taskQueue: taskQueueToProto(
      requiredField(model.taskQueue, "StartWorkflowRequest", "taskQueue"),
    ),
    workflowStartDelay:
      model.workflowStartDelay == null
        ? undefined
        : durationToProto(model.workflowStartDelay),
    namespace: workflowNamespace(),
  };
}

export interface CancelWorkflowRequest {
  workflowExecution: WorkflowExecution;
  reason?: string;
}

export function cancelWorkflowRequestToProto(
  model: CancelWorkflowRequest | null | undefined,
): temporal.api.workflowservice.v1.IRequestCancelWorkflowExecutionRequest | undefined {
  if (model == null) {
    return undefined;
  }
  return {
    workflowExecution:
      workflowExecutionToProto(
        requiredField(
          model.workflowExecution,
          "CancelWorkflowRequest",
          "workflowExecution",
        ),
      ) ?? {},
    reason: model.reason,
    namespace: workflowNamespace(),
  };
}

export interface WorkflowExecution {
  workflowId: string;
  runId?: string;
}

export function workflowExecutionFromProto(
  proto: temporal.api.common.v1.IWorkflowExecution | null | undefined,
): WorkflowExecution | undefined {
  if (proto == null) {
    return undefined;
  }
  return {
    workflowId: requiredField(
      proto.workflowId === "" ? undefined : proto.workflowId,
      "WorkflowExecution",
      "workflowId",
    ),
    runId: proto.runId ?? undefined,
  };
}

export function workflowExecutionToProto(
  model: WorkflowExecution | null | undefined,
): temporal.api.common.v1.IWorkflowExecution | undefined {
  if (model == null) {
    return undefined;
  }
  return {
    workflowId: requiredField(model.workflowId, "WorkflowExecution", "workflowId"),
    runId: model.runId,
  };
}

export type CancelWorkflowResponse = Record<string, never>;

export function cancelWorkflowResponseFromProto(
  proto:
    | temporal.api.workflowservice.v1.IRequestCancelWorkflowExecutionResponse
    | null
    | undefined,
): CancelWorkflowResponse | undefined {
  if (proto == null) {
    return undefined;
  }
  return {};
}

export function cancelWorkflowResponseToProto(
  model: CancelWorkflowResponse | null | undefined,
): temporal.api.workflowservice.v1.IRequestCancelWorkflowExecutionResponse | undefined {
  if (model == null) {
    return undefined;
  }
  return {};
}
