// Generated by nex-gen. DO NOT EDIT!

import type * as common from "@temporalio/common";
import { markNexusResource, registerNexusType } from "../nex-gen-runtime";
import { restartWorkflow } from "./operations/restart-workflow";
import { cancelWorkflow } from "./operations/cancel-workflow";

export class StartedWorkflow {
  public constructor(
    public readonly namespace: string,
    public readonly workflowId: string,
    public readonly runId: string | undefined,
  ) {}

  public async cancel(reason?: string): Promise<void> {
    const handle = await cancelWorkflow({
      workflowExecution: { workflowId: this.workflowId, runId: this.runId },
      reason: reason,
    });
    await handle.result();
  }

  public async restartWorkflow(
    workflow: string | ((...args: any[]) => Promise<any>),
    taskQueue: string,
  ): Promise<StartedWorkflow> {
    if (typeof workflow === "string") {
      return await restartWorkflow({
        workflowId: this.workflowId,
        workflow: workflow,
        taskQueue: taskQueue,
      });
    } else {
      return await restartWorkflow({
        workflowId: this.workflowId,
        workflow: workflow,
        taskQueue: taskQueue,
      });
    }
  }

  public async getResult(): Promise<common.Payload[]> {
    throw new Error("started-workflow.getResult is not yet implemented");
  }
}

registerNexusType("StartWorkflowService::resource::started-workflow", {
  fields: {
    namespace: { wire: "namespace", schema: { kind: "scalar" } },
    workflowId: { wire: "workflow-id", schema: { kind: "scalar" } },
    runId: { wire: "run-id", schema: { kind: "scalar" } },
  },
  factory: (fields): StartedWorkflow => {
    return new StartedWorkflow(
      fields.namespace as string,
      fields.workflowId as string,
      fields.runId as string | undefined,
    );
  },
});
markNexusResource(StartedWorkflow, "StartWorkflowService::resource::started-workflow");
