# Generated by nex-gen. DO NOT EDIT!

from __future__ import annotations

import typing
import pydantic

from .._json import (
    SpecInt,
    _emit_set_fields,
)

if typing.TYPE_CHECKING:
    from ..content.block.models import (
        Block,
        BlockStyle,
    )
    from ..content.page.models import (
        Page,
        PageMeta,
    )
    from ..tree.category.models import Category


class GetCategoryTreeInput(pydantic.BaseModel):
    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        strict=True, populate_by_name=True, extra="forbid"
    )

    root_id: str = pydantic.Field(alias="rootId")

    @pydantic.model_serializer(mode="wrap")
    def _serialize(
        self,
        handler: typing.Callable[[pydantic.BaseModel], typing.Any],
    ) -> dict[str, object]:
        return _emit_set_fields(self, handler)


class GetPageInput(pydantic.BaseModel):
    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        strict=True, populate_by_name=True, extra="forbid"
    )

    page_id: str = pydantic.Field(alias="pageId")

    @pydantic.model_serializer(mode="wrap")
    def _serialize(
        self,
        handler: typing.Callable[[pydantic.BaseModel], typing.Any],
    ) -> dict[str, object]:
        return _emit_set_fields(self, handler)


class PutBlockOutput(pydantic.BaseModel):
    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        strict=True, populate_by_name=True, extra="forbid"
    )

    block_id: str = pydantic.Field(alias="blockId")

    revision: SpecInt = pydantic.Field()

    @pydantic.model_serializer(mode="wrap")
    def _serialize(
        self,
        handler: typing.Callable[[pydantic.BaseModel], typing.Any],
    ) -> dict[str, object]:
        return _emit_set_fields(self, handler)
