# Generated by nex-gen. DO NOT EDIT!

from __future__ import annotations

from nexusrpc import Operation, service
from .models import (
    GetCategoryTreeInput,
    GetPageInput,
    PutBlockOutput,
)
from ..content.block.models import Block
from ..content.page.models import Page
from ..tree.category.models import Category


@service(name="example.kb.v1.KnowledgeBaseService")
class KnowledgeBaseService:
    """Fetch and update pages, blocks, and the category tree."""

    get_page: Operation[
        GetPageInput,
        Page,
    ] = Operation(name="GetPage")
    """Fetch a page by id."""

    put_block: Operation[
        Block,
        PutBlockOutput,
    ] = Operation(name="PutBlock")
    """Create or update a content block."""

    get_category_tree: Operation[
        GetCategoryTreeInput,
        Category,
    ] = Operation(name="GetCategoryTree")
    """Fetch the category tree rooted at a category."""
