// Generated by nex-gen. DO NOT EDIT!

import { registerNexusType } from "../nex-gen-runtime";

export function requiredField<T>(
  value: T | null | undefined,
  owner: string,
  field: string,
): T {
  if (value == null) {
    throw new Error(`missing required field ${owner}.${field}`);
  }
  return value;
}

export interface GetUserRequest {
  userId: string;
}

export interface UpdateEmailRequest {
  userId: string;
  email: string;
}

registerNexusType("user-service.get-user-request", {
  fields: {
    userId: { wire: "user-id", schema: { kind: "scalar" } },
  },
});

registerNexusType("user-service.update-email-request", {
  fields: {
    userId: { wire: "user-id", schema: { kind: "scalar" } },
    email: { wire: "email", schema: { kind: "scalar" } },
  },
});
