// Generated by nexgen v0.2.1. DO NOT EDIT!

/** A single constraint failure, located by JSON path. */
export interface Violation {
  readonly path: string;
  readonly reason: string;
}

export class ValidationError extends Error {
  public constructor(public readonly violations: Violation[]) {
    super(
      `${violations.length} validation error(s): ` +
        violations.map((v) => `${v.path}: ${v.reason}`).join("; "),
    );
    this.name = "ValidationError";
  }
}

export function isPlainObject(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

export function collect(violations: Violation[], path: string, error: unknown): void {
  if (error instanceof ValidationError) {
    for (const inner of error.violations) {
      const nested = !inner.path
        ? path
        : inner.path.startsWith("[")
          ? `${path}${inner.path}`
          : `${path}.${inner.path}`;
      violations.push({ path: nested, reason: inner.reason });
    }
  } else {
    violations.push({ path, reason: String(error) });
  }
}
