// Code generated by nex-gen. DO NOT EDIT.

package kb

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"math"
	"strings"
)

// ---------------------------------------------------------------------------
// Shared validator core (emitted once per package).
// ---------------------------------------------------------------------------

// Violation is a single constraint failure. Path is the JSON member path
// (dotted for nested members); Reason is a human-readable message.
type Violation struct {
	Path   string
	Reason string
}

func (v Violation) String() string {
	if v.Path == "" {
		return v.Reason
	}
	return v.Path + ": " + v.Reason
}

// ValidationError aggregates every Violation found while (de)serializing a
// value, surfacing them all in one error (never a partial first-failure).
// It is the Go analog of Java's ValidationException / Python's
// pydantic.ValidationError.
type ValidationError struct {
	Violations []Violation
}

func (e *ValidationError) Error() string {
	parts := make([]string, len(e.Violations))
	for i, v := range e.Violations {
		parts[i] = v.String()
	}
	return fmt.Sprintf("%d validation error(s): %s", len(e.Violations), strings.Join(parts, "; "))
}

// addViolations folds a child error's violations into errs at the same path
// scope (no prefix) — used to merge a same-object Validate() result.
func addViolations(errs *[]Violation, err error) {
	if err == nil {
		return
	}
	var ve *ValidationError
	if errors.As(err, &ve) {
		*errs = append(*errs, ve.Violations...)
		return
	}
	*errs = append(*errs, Violation{"", err.Error()})
}

// mergeNested appends a child value's violations under a dotted parent path.
func mergeNested(errs *[]Violation, path string, err error) {
	if err == nil {
		return
	}
	var ve *ValidationError
	if errors.As(err, &ve) {
		for _, v := range ve.Violations {
			p := v.Path
			if p == "" {
				p = path
			} else {
				p = path + "." + v.Path
			}
			*errs = append(*errs, Violation{p, v.Reason})
		}
		return
	}
	*errs = append(*errs, Violation{path, err.Error()})
}

// IntegerCap is the cross-language integer bound, ±(2^53-1), equal to
// JavaScript's Number.MAX_SAFE_INTEGER. Every target agrees on this range.
const IntegerCap = 1<<53 - 1

var (
	errFractional = errors.New("not an integer")
	errRange      = errors.New("exceeds ±(2^53-1) integer cap")
)

// parseSpecInteger accepts spec-valid integers ("1", "1.0", "1e2"), rejects
// fractional values ("1.5"), and enforces the ±(2^53-1) cap.
func parseSpecInteger(n json.Number) (int64, error) {
	f, err := n.Float64()
	if err != nil {
		return 0, err
	}
	if f != math.Trunc(f) {
		return 0, errFractional
	}
	if f < -IntegerCap || f > IntegerCap {
		return 0, errRange
	}
	i, err := n.Int64()
	if err != nil {
		return 0, err // belt-and-suspenders
	}
	return i, nil
}

// isNull reports whether a captured raw member is the JSON null literal.
func isNull(raw json.RawMessage) bool {
	return bytes.Equal(bytes.TrimSpace(raw), []byte("null"))
}

// parseStringField applies the absent/null/value three-way for a string
// member. Returns (value, present); on a violation it appends to errs.
func parseStringField(raw *json.RawMessage, path string, required, nullable bool, errs *[]Violation) (string, bool) {
	if raw == nil {
		if required {
			*errs = append(*errs, Violation{path, "required"})
		}
		return "", false
	}
	if isNull(*raw) {
		if !nullable {
			*errs = append(*errs, Violation{path, "explicit null not allowed"})
		}
		return "", false
	}
	var s string
	if err := json.Unmarshal(*raw, &s); err != nil {
		*errs = append(*errs, Violation{path, "expected string"})
		return "", false
	}
	return s, true
}

// parseIntegerField applies the three-way and the spec-integer parse.
func parseIntegerField(raw *json.RawMessage, path string, required, nullable bool, errs *[]Violation) (int64, bool) {
	if raw == nil {
		if required {
			*errs = append(*errs, Violation{path, "required"})
		}
		return 0, false
	}
	if isNull(*raw) {
		if !nullable {
			*errs = append(*errs, Violation{path, "explicit null not allowed"})
		}
		return 0, false
	}
	dec := json.NewDecoder(bytes.NewReader(*raw))
	dec.UseNumber()
	var n json.Number
	if err := dec.Decode(&n); err != nil {
		*errs = append(*errs, Violation{path, "expected integer"})
		return 0, false
	}
	v, err := parseSpecInteger(n)
	if err != nil {
		*errs = append(*errs, Violation{path, err.Error()})
		return 0, false
	}
	return v, true
}

// parseBoolField applies the absent/null/value three-way for a boolean
// member. Returns (value, present); on a violation it appends to errs.
func parseBoolField(raw *json.RawMessage, path string, required, nullable bool, errs *[]Violation) (bool, bool) {
	if raw == nil {
		if required {
			*errs = append(*errs, Violation{path, "required"})
		}
		return false, false
	}
	if isNull(*raw) {
		if !nullable {
			*errs = append(*errs, Violation{path, "explicit null not allowed"})
		}
		return false, false
	}
	var b bool
	if err := json.Unmarshal(*raw, &b); err != nil {
		*errs = append(*errs, Violation{path, "expected boolean"})
		return false, false
	}
	return b, true
}

// marshalField encodes v and stores it under key, collecting any violations
// (a nested type's MarshalJSON returns a *ValidationError) under key's path.
func marshalField(out map[string]json.RawMessage, key string, v any, errs *[]Violation) {
	b, err := json.Marshal(v)
	if err != nil {
		mergeNested(errs, key, err)
		return
	}
	out[key] = b
}
