// <auto-generated />
// Generated by nexgen v0.2.3. DO NOT EDIT!
#nullable enable
#pragma warning disable CS1591

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;

namespace Nexgen.UserService
{

    [GeneratedCode("nexgen", null)]
    public record GetUserRequest
    {
        public GetUserRequest(string userId)
        {
            UserId = userId;
        }

        public string UserId { get; init; }
    }

    [GeneratedCode("nexgen", null)]
    public record UpdateEmailRequest
    {
        public UpdateEmailRequest(string userId, string email)
        {
            UserId = userId;
            Email = email;
        }

        public string UserId { get; init; }
        public string Email { get; init; }
    }

}
