// Generated by nex-gen. DO NOT EDIT!

import * as workflow from "@temporalio/workflow";
import { UserService } from "../service.ts";
import type { UpdateEmailRequest } from "../models.ts";
import "../resources.ts";
import type { User } from "../resources.ts";
import { nexusValue } from "../../nex-gen-runtime.ts";

/**
 * @param request - Request for the operation.
 */
export async function updateEmail(request: UpdateEmailRequest): Promise<User> {
  const client = workflow.createNexusServiceClient({
    service: UserService,
    endpoint: "user-service",
  });
  const requestProto = nexusValue("user-service.update-email-request", request);
  const handle = await client.startOperation(
    UserService.operations.updateEmail,
    requestProto,
  );
  return await handle.result();
}
