// Generated by nex-gen. DO NOT EDIT!

package com.example.kb;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonDeserializer;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.JsonSerializer;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import org.jspecify.annotations.NullMarked;

/**
 * Synthesized from the inline {@code input} of the {@code getCategoryTree}
 * operation. Closed struct.
 */
@NullMarked
@JsonDeserialize(using = GetCategoryTreeInput.Deserializer.class)
@JsonSerialize(using = GetCategoryTreeInput.Serializer.class)
public final class GetCategoryTreeInput {
  private final String rootId;

  public GetCategoryTreeInput(String rootId) {
    this.rootId = rootId;
  }

  public String getRootId() {
    return rootId;
  }

  public static final class Deserializer extends JsonDeserializer<GetCategoryTreeInput> {
    @Override
    public GetCategoryTreeInput deserialize(JsonParser p, DeserializationContext ctx)
        throws IOException {
      JsonNode root = p.readValueAsTree();
      List<Violation> errs = new ArrayList<>();

      String rootId = null;
      JsonNode n = root.get("rootId");
      if (n == null || n.isNull()) {
        errs.add(new Violation("rootId", "required"));
      } else if (!n.isTextual()) {
        errs.add(new Violation("rootId", "expected string"));
      } else {
        rootId = n.asText();
      }

      Iterator<String> it = root.fieldNames();
      while (it.hasNext()) {
        String k = it.next();
        if (!k.equals("rootId")) {
          errs.add(new Violation(k, "unknown field"));
        }
      }

      if (!errs.isEmpty()) {
        throw new ValidationException(p, errs);
      }
      return new GetCategoryTreeInput(rootId);
    }
  }

  public static final class Serializer extends JsonSerializer<GetCategoryTreeInput> {
    @Override
    public void serialize(GetCategoryTreeInput v, JsonGenerator gen, SerializerProvider sp)
        throws IOException {
      if (v.rootId == null) {
        throw new ValidationException(null, List.of(new Violation("rootId", "required")));
      }
      gen.writeStartObject();
      gen.writeStringField("rootId", v.rootId);
      gen.writeEndObject();
    }
  }
}
