// Generated by nex-gen. DO NOT EDIT!

package com.example.kb;

import io.nexusrpc.Operation;
import io.nexusrpc.Service;
import org.jspecify.annotations.NullMarked;

/**
 * Fetch and update pages, blocks, and the category tree.
 *
 * <p>The wire name is emitted explicitly ({@code example.kb.v1.KnowledgeBaseService})
 * so every language agrees byte-for-byte regardless of SDK defaults.
 */
@NullMarked
@Service(name = "example.kb.v1.KnowledgeBaseService")
public interface KnowledgeBaseService {
  /**
   * Fetch a page by id.
   */
  @Operation(name = "GetPage")
  Page getPage(GetPageInput input);

  /**
   * Create or update a content block.
   */
  @Operation(name = "PutBlock")
  PutBlockOutput putBlock(Block input);

  /**
   * Fetch the category tree rooted at a category.
   */
  @Operation(name = "GetCategoryTree")
  Category getCategoryTree(GetCategoryTreeInput input);
}
