// Generated by nex-gen. DO NOT EDIT!

package com.example.kb;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonDeserializer;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.JsonSerializer;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Objects;
import org.jspecify.annotations.NullMarked;
import org.jspecify.annotations.Nullable;

/**
 * Non-cyclic helper. Referenced only by {@link Page}, references nothing
 * recursive. Closed struct.
 */
@NullMarked
@JsonDeserialize(using = PageMeta.Deserializer.class)
@JsonSerialize(using = PageMeta.Serializer.class)
public final class PageMeta {
  private final String author;
  private final @Nullable Long wordCount; // optional integer

  public PageMeta(String author, @Nullable Long wordCount) {
    this.author = author;
    this.wordCount = wordCount;
  }

  public String getAuthor() {
    return author;
  }

  public @Nullable Long getWordCount() {
    return wordCount;
  }

  public static final class Deserializer extends JsonDeserializer<PageMeta> {
    @Override
    public PageMeta deserialize(JsonParser p, DeserializationContext ctx) throws IOException {
      JsonNode root = p.readValueAsTree();
      List<Violation> errs = new ArrayList<>();

      String author = null;
      JsonNode authorNode = root.get("author");
      if (authorNode == null || authorNode.isNull()) {
        errs.add(new Violation("author", "required"));
      } else if (!authorNode.isTextual()) {
        errs.add(new Violation("author", "expected string"));
      } else {
        author = authorNode.asText();
      }

      // wordCount: optional integer.
      Long wordCount = null;
      JsonNode wcNode = root.get("wordCount");
      if (wcNode != null && !wcNode.isNull()) {
        wordCount = SpecNumbers.specLong(wcNode, "wordCount", errs);
      }

      Iterator<String> it = root.fieldNames();
      while (it.hasNext()) {
        String k = it.next();
        if (!k.equals("author") && !k.equals("wordCount")) {
          errs.add(new Violation(k, "unknown field"));
        }
      }

      if (!errs.isEmpty()) {
        throw new ValidationException(p, errs);
      }
      return new PageMeta(Objects.requireNonNull(author), wordCount);
    }
  }

  public static final class Serializer extends JsonSerializer<PageMeta> {
    @Override
    public void serialize(PageMeta v, JsonGenerator gen, SerializerProvider sp) throws IOException {
      List<Violation> errs = new ArrayList<>();
      if (v.author == null) {
        errs.add(new Violation("author", "required"));
      }
      if (v.wordCount != null && Math.abs(v.wordCount) > SpecNumbers.CAP) {
        errs.add(new Violation("wordCount", "integer exceeds +/-(2^53-1) cap"));
      }
      if (!errs.isEmpty()) {
        throw new ValidationException(null, errs);
      }
      gen.writeStartObject();
      gen.writeStringField("author", v.author);
      // optional: omit when unset.
      if (v.wordCount != null) {
        gen.writeNumberField("wordCount", v.wordCount);
      }
      gen.writeEndObject();
    }
  }
}
