// Generated by nex-gen. DO NOT EDIT!

package com.example.kb;

import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.JsonMappingException;
import java.util.Collections;
import java.util.List;
import org.jspecify.annotations.NullMarked;
import org.jspecify.annotations.Nullable;

/**
 * Aggregated validation failure thrown by a generated collecting
 * (de)serializer. Holds every {@link Violation} found while binding or
 * emitting a single payload, so a caller sees all problems at once rather
 * than only the first.
 *
 * <p>It extends {@link JsonMappingException} so it propagates verbatim
 * through the default Temporal data converter as the cause of a
 * {@code DataConverterException}; a Nexus handler can walk the cause chain,
 * pull {@link #getViolations()}, and map them onto a single
 * {@code BAD_REQUEST} {@code HandlerError}.
 */
@NullMarked
public final class ValidationException extends JsonMappingException {
  private final List<Violation> violations;

  public ValidationException(@Nullable JsonParser p, List<Violation> violations) {
    super(p, summarize(violations));
    this.violations = Collections.unmodifiableList(violations);
  }

  public List<Violation> getViolations() {
    return violations;
  }

  private static String summarize(List<Violation> violations) {
    StringBuilder sb = new StringBuilder(violations.size() + " validation error(s):");
    for (Violation v : violations) {
      sb.append("\n  ").append(v);
    }
    return sb.toString();
  }
}
