// Generated by nexgen. DO NOT EDIT!

import * as workflow from "@temporalio/workflow";
import { functionExecution } from "../services";
import type {
  ExecuteNamedFunctionResult,
  ExecuteNamedFunctionRequest,
} from "../models";

/**
 * @param request - Request for the operation.
 */
export async function executeNamedFunction<
  FunctionFn extends (name: string, enabled: boolean) => string = (
    name: string,
    enabled: boolean,
  ) => string,
>(
  request: ExecuteNamedFunctionRequest<FunctionFn>,
): Promise<workflow.NexusOperationHandle<ExecuteNamedFunctionResult>> {
  const client = workflow.createNexusServiceClient({
    service: functionExecution,
    endpoint: "function-execution",
  });
  return await client.startOperation(
    functionExecution.operations.executeNamedFunction,
    request,
  );
}
