// Code generated by nex-gen. DO NOT EDIT.
package userservice

import (
	"go.temporal.io/sdk/workflow"
)

// --- Datatypes ---

type getUserRequest struct {
	// Required.
	UserId string
}

type updateEmailRequest struct {
	// Required.
	UserId string
	// Required.
	Email string
}

// --- Resources ---

type User struct {
	// Required.
	UserId string
	// Required.
	Email string
}

func (u *User) UpdateEmail(ctx workflow.Context, email string) workflow.NexusOperationFuture {
	return updateEmail(ctx, updateEmailRequest{UserId: u.UserId, Email: email})
}

// --- Operations (internal) ---

func getUser(ctx workflow.Context, request getUserRequest) workflow.NexusOperationFuture {
	c := workflow.NewNexusClient("user-service", "UserService")
	fut := c.ExecuteOperation(ctx, "GetUser", request, workflow.NexusOperationOptions{})
	return fut
}

func updateEmail(ctx workflow.Context, request updateEmailRequest) workflow.NexusOperationFuture {
	c := workflow.NewNexusClient("user-service", "UserService")
	fut := c.ExecuteOperation(ctx, "UpdateEmail", request, workflow.NexusOperationOptions{})
	return fut
}

// --- Operations (public API) ---

func GetUser(ctx workflow.Context, userId string) workflow.NexusOperationFuture {
	return getUser(ctx, getUserRequest{
		UserId: userId,
	})
}

func UpdateEmail(ctx workflow.Context, userId string, email string) workflow.NexusOperationFuture {
	return updateEmail(ctx, updateEmailRequest{
		UserId: userId,
		Email:  email,
	})
}
