// Generated by nexus-api-gen. DO NOT EDIT!

import { markNexusResource, registerNexusResource } from "../nexus-api-gen-runtime.ts";
import { updateEmail } from "./operations/update-email.ts";

export class User {
  public constructor(
    public readonly userId: string,
    public readonly email: string,
  ) {}

  public async updateEmail(email: string): Promise<User> {
    return await updateEmail({ userId: this.userId, email: email });
  }
}

registerNexusResource("UserService::resource::user", (fields): User => {
  return new User(fields.userId as string, fields.email as string);
});
markNexusResource(User, "UserService::resource::user");
