// Generated by nexgen v0.2.2. DO NOT EDIT.
package json_schema.definitions.showcase;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.jspecify.annotations.Nullable;

/**
 * A typed map of referenced Address models.
 */
@JsonSerialize(using = AddressBook.Serializer.class)
@JsonDeserialize(using = AddressBook.Deserializer.class)
public final class AddressBook {
    private final Map<String, Address> additionalProperties;

    public AddressBook(Map<String, Address> additionalProperties) {
        this.additionalProperties = additionalProperties;
    }

    public Map<String, Address> getAdditionalProperties() {
        return additionalProperties;
    }

    @Override
    public boolean equals(@Nullable Object other) {
        if (this == other) {
            return true;
        }
        if (!(other instanceof AddressBook)) {
            return false;
        }
        return Objects.equals(this.additionalProperties, ((AddressBook) other).additionalProperties);
    }

    @Override
    public int hashCode() {
        return Objects.hash(additionalProperties);
    }

    @Override
    public String toString() {
        return "AddressBook{"
            + "additionalProperties=" + additionalProperties
            + "}";
    }

    public static final class Serializer extends com.fasterxml.jackson.databind.JsonSerializer<AddressBook> {
        @Override
        public void serialize(AddressBook value, JsonGenerator gen, SerializerProvider serializers) throws IOException {
            gen.writeStartObject();
            for (Map.Entry<String, Address> entry : value.additionalProperties.entrySet()) {
                gen.writeFieldName(entry.getKey());
                serializers.defaultSerializeValue(entry.getValue(), gen);
            }
            gen.writeEndObject();
        }
    }

    public static final class Deserializer extends com.fasterxml.jackson.databind.JsonDeserializer<AddressBook> {
        @Override
        public AddressBook deserialize(JsonParser parser, DeserializationContext context) throws IOException {
            JsonNode node = parser.readValueAsTree();
            List<Violation> violations = new ArrayList<>();
            if (node == null || !node.isObject()) {
                violations.add(new Violation("", "expected object"));
                throw new ValidationException(violations);
            }
            Map<String, Address> additionalProperties = new LinkedHashMap<>();
            Iterator<String> fieldNames = node.fieldNames();
            while (fieldNames.hasNext()) {
                String key = fieldNames.next();
                JsonNode element = node.get(key);
                if (element.isNull()) {
                    violations.add(new Violation(key, "explicit null not allowed"));
                    continue;
                }
                try {
                    additionalProperties.put(key, context.readTreeAsValue(element, Address.class));
                } catch (ValidationException nested) {
                    for (Violation violation : nested.getViolations()) {
                        violations.add(violation.withPathPrefix(key));
                    }
                } catch (IOException nested) {
                    violations.add(new Violation(key, nested.getMessage()));
                }
            }
            if (!violations.isEmpty()) {
                throw new ValidationException(violations);
            }
            return new AddressBook(additionalProperties);
        }
    }
}
