// Generated by nexgen latest. DO NOT EDIT.
package json_schema.definitions.showcase;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.temporal.failure.ApplicationFailure;
import java.io.IOException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.jspecify.annotations.Nullable;

/**
 * A typed map of materialized calendar dates.
 */
@JsonSerialize(using = DateIndex.Serializer.class)
@JsonDeserialize(using = DateIndex.Deserializer.class)
public final class DateIndex {
    private final Map<String, LocalDate> additionalProperties;

    public DateIndex(Map<String, LocalDate> additionalProperties) {
        this.additionalProperties = additionalProperties;
    }

    public Map<String, LocalDate> getAdditionalProperties() {
        return additionalProperties;
    }

    @Override
    public boolean equals(@Nullable Object other) {
        if (this == other) {
            return true;
        }
        if (!(other instanceof DateIndex)) {
            return false;
        }
        return Objects.equals(this.additionalProperties, ((DateIndex) other).additionalProperties);
    }

    @Override
    public int hashCode() {
        return Objects.hash(additionalProperties);
    }

    @Override
    public String toString() {
        return "DateIndex{"
            + "additionalProperties=" + additionalProperties
            + "}";
    }

    public static final class Serializer extends com.fasterxml.jackson.databind.JsonSerializer<DateIndex> {
        @Override
        public void serialize(DateIndex value, JsonGenerator gen, SerializerProvider serializers) throws IOException {
            List<Violation> violations = new ArrayList<>();
            for (Map.Entry<String, LocalDate> entry : value.additionalProperties.entrySet()) {
                TemporalSupport.checkDate(entry.getValue(), Violation.memberPath(entry.getKey()), violations);
            }
            if (!violations.isEmpty()) {
                // TODO: Use PayloadValidationException.newPayloadValidationException once it is available in an SDK release.
                throw ApplicationFailure.newNonRetryableFailure("Payload validation failed", "PayloadValidationError", violations);
            }
            gen.writeStartObject();
            for (Map.Entry<String, LocalDate> entry : value.additionalProperties.entrySet()) {
                gen.writeStringField(entry.getKey(), TemporalSupport.formatDate(entry.getValue()));
            }
            gen.writeEndObject();
        }
    }

    public static final class Deserializer extends com.fasterxml.jackson.databind.JsonDeserializer<DateIndex> {
        @Override
        public DateIndex deserialize(JsonParser parser, DeserializationContext context) throws IOException {
            JsonNode node = SpecNumbers.readExactTree(parser);
            List<Violation> violations = new ArrayList<>();
            if (node == null || !node.isObject()) {
                violations.add(new Violation("", "expected object"));
                // TODO: Use PayloadValidationException.newPayloadValidationException once it is available in an SDK release.
                throw ApplicationFailure.newNonRetryableFailure("Payload validation failed", "PayloadValidationError", violations);
            }
            Map<String, LocalDate> additionalProperties = new LinkedHashMap<>();
            Iterator<String> fieldNames = node.fieldNames();
            while (fieldNames.hasNext()) {
                String key = fieldNames.next();
                String path = Violation.memberPath(key);
                JsonNode element = node.get(key);
                if (element.isNull()) {
                    violations.add(new Violation(path, "explicit null not allowed"));
                    continue;
                }
                if (!element.isTextual()) {
                    violations.add(new Violation(path, "expected string value"));
                } else {
                    LocalDate parsed = TemporalSupport.parseDate(element.textValue(), path, violations);
                    if (parsed != null) {
                        additionalProperties.put(key, parsed);
                    }
                }
            }
            if (!violations.isEmpty()) {
                // TODO: Use PayloadValidationException.newPayloadValidationException once it is available in an SDK release.
                throw ApplicationFailure.newNonRetryableFailure("Payload validation failed", "PayloadValidationError", violations);
            }
            return new DateIndex(additionalProperties);
        }
    }
}
