# Generated by nex-gen. DO NOT EDIT!

from __future__ import annotations

from . import service as _service
from .operations.send_message import send_message
from .operations.get_room import get_room
from .operations.ping import ping

__all__ = [
    "get_room",
    "ping",
    "send_message",
]


__nexus_operation_registry__ = {
    (
        "example.chat.v1.ChatService",
        "SendMessage",
    ): _service.ChatService.send_message,
    (
        "example.chat.v1.ChatService",
        "GetRoom",
    ): _service.ChatService.get_room,
    (
        "example.chat.v1.ChatService",
        "Ping",
    ): _service.ChatService.ping,
}
