// Code generated by nex-gen. DO NOT EDIT.
package temporalsystem

import (
	"time"

	activity "go.temporal.io/api/activity/v1"
	common "go.temporal.io/api/common/v1"
	"go.temporal.io/sdk/temporal"
	"go.temporal.io/sdk/workflow"
)

// --- Operations (internal) ---

func retryPolicyOperation(ctx workflow.Context, request temporal.RetryPolicy) (*temporal.RetryPolicy, error) {
	requestProto, err := retryPolicyToProto(ctx, &request)
	if err != nil {
		return nil, err
	}
	c := workflow.NewNexusClient("temporal-system", "TypeRoundtripService")
	fut := c.ExecuteOperation(ctx, "RetryPolicyOperation", requestProto, workflow.NexusOperationOptions{})
	var result common.RetryPolicy
	if err := fut.Get(ctx, &result); err != nil {
		return nil, err
	}
	value, err := retryPolicyFromProto(ctx, &result)
	if err != nil {
		return nil, err
	}
	return value, nil
}

func activityOptionsOperation(ctx workflow.Context, request ActivityOptions) (*ActivityOptions, error) {
	requestProto, err := request.toProto(ctx)
	if err != nil {
		return nil, err
	}
	c := workflow.NewNexusClient("temporal-system", "TypeRoundtripService")
	fut := c.ExecuteOperation(ctx, "ActivityOptionsOperation", requestProto, workflow.NexusOperationOptions{})
	var result activity.ActivityOptions
	if err := fut.Get(ctx, &result); err != nil {
		return nil, err
	}
	value, err := activityOptionsFromProto(ctx, &result)
	if err != nil {
		return nil, err
	}
	return &value, nil
}

// --- Operations (public API) ---

type ActivityOptions struct {
	TaskQueue *string
	// Required.
	RetryPolicy            temporal.RetryPolicy
	ScheduleToCloseTimeout *time.Duration
	Priority               *temporal.Priority
}

func (m ActivityOptions) toProto(ctx workflow.Context) (*activity.ActivityOptions, error) {
	message := &activity.ActivityOptions{}
	{
		converted, err := taskQueueToProto(ctx, m.TaskQueue)
		if err != nil {
			return nil, err
		}
		message.TaskQueue = converted
	}
	{
		converted, err := retryPolicyToProto(ctx, &m.RetryPolicy)
		if err != nil {
			return nil, err
		}
		message.RetryPolicy = converted
	}
	{
		converted, err := durationToProto(ctx, m.ScheduleToCloseTimeout)
		if err != nil {
			return nil, err
		}
		message.ScheduleToCloseTimeout = converted
	}
	{
		converted, err := priorityToProto(ctx, m.Priority)
		if err != nil {
			return nil, err
		}
		message.Priority = converted
	}
	return message, nil
}

func activityOptionsFromProto(ctx workflow.Context, proto *activity.ActivityOptions) (ActivityOptions, error) {
	value := ActivityOptions{}
	{
		converted, err := taskQueueFromProto(ctx, proto.GetTaskQueue())
		if err != nil {
			return value, err
		}
		value.TaskQueue = converted
	}
	{
		converted, err := retryPolicyFromProto(ctx, proto.GetRetryPolicy())
		if err != nil {
			return value, err
		}
		if converted != nil {
			value.RetryPolicy = *converted
		}
	}
	{
		converted, err := durationFromProto(ctx, proto.GetScheduleToCloseTimeout())
		if err != nil {
			return value, err
		}
		value.ScheduleToCloseTimeout = converted
	}
	{
		converted, err := priorityFromProto(ctx, proto.GetPriority())
		if err != nil {
			return value, err
		}
		value.Priority = converted
	}
	return value, nil
}

func RetryPolicyOperation(ctx workflow.Context, request temporal.RetryPolicy) (*temporal.RetryPolicy, error) {
	return retryPolicyOperation(ctx, request)
}

type ActivityOptionsOperationOptions struct {
	TaskQueue              *string
	ScheduleToCloseTimeout *time.Duration
	Priority               *temporal.Priority
}

func ActivityOptionsOperation(ctx workflow.Context, retryPolicy temporal.RetryPolicy, opts ActivityOptionsOperationOptions) (*ActivityOptions, error) {
	return activityOptionsOperation(ctx, ActivityOptions{
		TaskQueue:              opts.TaskQueue,
		RetryPolicy:            retryPolicy,
		ScheduleToCloseTimeout: opts.ScheduleToCloseTimeout,
		Priority:               opts.Priority,
	})
}
