// Code generated by nexus-api-gen. DO NOT EDIT.
package userservice

const ServiceName = "UserService"
const Endpoint = "user-service"

const GetUserOp = "GetUser"
const UpdateEmailOp = "UpdateEmail"

type GetUserRequest struct {
	UserId string // required
}

type UpdateEmailRequest struct {
	UserId string // required
	Email  string // required
}

type User struct {
	UserId string // required
	Email  string // required
}
