// Generated by nex-gen. DO NOT EDIT!

export { TypeShowcase } from "./service.ts";
export { getUser } from "./operations/get-user.ts";
export { updateEmail } from "./operations/update-email.ts";
export { rename } from "./operations/rename.ts";
export { setProfile } from "./operations/set-profile.ts";
export { deactivate } from "./operations/deactivate.ts";
export { UserStatus, UserCapability } from "./models.ts";
export type {
  NotificationTarget,
  GetUserRequest,
  UpdateEmailRequest,
  RenameRequest,
  SetProfileRequest,
  UserProfile,
  PostalAddress,
  DeactivateRequest,
} from "./models.ts";
export { User } from "./resources.ts";
