# Generated by nex-gen. DO NOT EDIT!

from __future__ import annotations

import dataclasses
import typing
import nex_gen_runtime
import temporalio.workflow

from ..models import UpdateEmailRequest


@dataclasses.dataclass
class User:
    user_id: str
    email: str

    async def update_email(
        self,
        email: str,
    ) -> User:
        request = UpdateEmailRequest(
            user_id=self.user_id,
            email=email,
        )
        return await update_email_request(
            typing.cast(str, getattr(self, "_endpoint")), request
        )


async def update_email_request(
    endpoint: str,
    request: UpdateEmailRequest,
) -> User:
    nexus_client = temporalio.workflow.create_nexus_client(
        service="UserService",
        endpoint=endpoint,
    )
    handle = await nexus_client.start_operation(
        operation="UpdateEmail",
        input=request,
        output_type=User,
    )
    resource = await handle
    setattr(resource, "_endpoint", endpoint)
    return resource


nex_gen_runtime.register_nexus_type(User, "UserService::resource::user")
